[package]
name = "talaria-workspace-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
talaria-agent-auth = { workspace = true }
sqlx = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
talaria-audit = { workspace = true }
talaria-secretbox = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
