[package]
name = "talaria-fleet-cascade"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
talaria-agent-defs = { workspace = true }
talaria-fleet-create = { workspace = true }
talaria-fleet-docker = { workspace = true }
talaria-secretbox = { workspace = true }
