// Byte-exact fixtures for the yaml emitter (api/src/yaml_string.rs ⇄ the npm
// `yaml` package, ^2.9.0). The fixture is generated by
// scripts/gen-yaml-vectors.mjs against the real package — the only thing that
// writes it — so these assertions are the package's own output, not a
// hand-transcription. If one fails, the port diverged from the grammar; fix
// the port (or, if the case list grew, regenerate), never the expectation by
// hand.

use serde_json::Value;
use talaria_api::yaml_string::stringify;

#[test]
fn matches_the_package_byte_for_byte() {
    let fixture = include_str!("fixtures/yaml-stringify.json");
    let parsed: Value = serde_json::from_str(fixture).expect("fixture parses");
    let cases = parsed["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "fixture must not be empty");
    let mut failures: Vec<String> = Vec::new();
    for case in cases {
        let name = case["name"].as_str().unwrap_or("?");
        let input: Value = serde_json::from_str(case["input"].as_str().expect("input json"))
            .expect("input parses");
        let want = case["yaml"].as_str().expect("yaml text");
        let got = stringify(&input);
        if got != want {
            failures.push(format!(
                "case {name}:\n  want: {:?}\n  got:  {:?}",
                want, got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} yaml cases diverged:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
