/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiInferenceRouteImport } from './routes/api/inference'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFleetRouteImport } from './routes/api/fleet'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChannelsRouteImport } from './routes/api/channels'
import { Route as ApiBoardsRouteImport } from './routes/api/boards'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppModelsRouteImport } from './routes/_app/models'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppMcpRouteImport } from './routes/_app/mcp'
import { Route as AppInferenceRouteImport } from './routes/_app/inference'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppCostRouteImport } from './routes/_app/cost'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppBoardsIndexRouteImport } from './routes/_app/boards/index'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads.$id'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiMemoryIdRouteImport } from './routes/api/memory.$id'
import { Route as ApiMcpTestRouteImport } from './routes/api/mcp.test'
import { Route as ApiKeysIdRouteImport } from './routes/api/keys.$id'
import { Route as ApiFleetRenderRouteImport } from './routes/api/fleet.render'
import { Route as ApiFleetReconcileRouteImport } from './routes/api/fleet.reconcile'
import { Route as ApiFleetEndpointsRouteImport } from './routes/api/fleet.endpoints'
import { Route as ApiFleetDefsRouteImport } from './routes/api/fleet.defs'
import { Route as ApiFleetCreateRouteImport } from './routes/api/fleet.create'
import { Route as ApiFleetContainersRouteImport } from './routes/api/fleet.containers'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations.$id'
import { Route as ApiChannelsIdRouteImport } from './routes/api/channels.$id'
import { Route as ApiBoardsIdRouteImport } from './routes/api/boards.$id'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAgentsRegisterRouteImport } from './routes/api/agents.register'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin.users'
import { Route as AppBoardsBoardIdRouteImport } from './routes/_app/boards/$boardId'
import { Route as ApiTeamsIdMembersRouteImport } from './routes/api/teams.$id.members'
import { Route as ApiTasksIdWatchersRouteImport } from './routes/api/tasks.$id.watchers'
import { Route as ApiTasksIdUsageRouteImport } from './routes/api/tasks.$id.usage'
import { Route as ApiTasksIdReviewRouteImport } from './routes/api/tasks.$id.review'
import { Route as ApiTasksIdDependenciesRouteImport } from './routes/api/tasks.$id.dependencies'
import { Route as ApiTasksIdCommentsRouteImport } from './routes/api/tasks.$id.comments'
import { Route as ApiSkillsOwnerNameRouteImport } from './routes/api/skills.$owner.$name'
import { Route as ApiLlmV1ModelsRouteImport } from './routes/api/llm.v1.models'
import { Route as ApiFleetEndpointsIdRouteImport } from './routes/api/fleet.endpoints.$id'
import { Route as ApiFleetDefsIdRouteImport } from './routes/api/fleet.defs.$id'
import { Route as ApiChannelsIdPlanRouteImport } from './routes/api/channels.$id.plan'
import { Route as ApiChannelsIdMessagesRouteImport } from './routes/api/channels.$id.messages'
import { Route as ApiChannelsIdMembersRouteImport } from './routes/api/channels.$id.members'
import { Route as ApiChannelsIdEventsRouteImport } from './routes/api/channels.$id.events'
import { Route as ApiChannelsIdAgentsRouteImport } from './routes/api/channels.$id.agents'
import { Route as ApiBoardsIdTasksRouteImport } from './routes/api/boards.$id.tasks'
import { Route as ApiBoardsIdMembersRouteImport } from './routes/api/boards.$id.members'
import { Route as ApiBoardsIdEventsRouteImport } from './routes/api/boards.$id.events'
import { Route as ApiBoardsIdAgentsRouteImport } from './routes/api/boards.$id.agents'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'
import { Route as ApiAgentsIdHeartbeatRouteImport } from './routes/api/agents.$id.heartbeat'
import { Route as AppBoardsBoardIdTaskIdRouteImport } from './routes/_app/boards/$boardId.$taskId'
import { Route as ApiLlmV1ChatCompletionsRouteImport } from './routes/api/llm.v1.chat.completions'
import { Route as ApiFleetEndpointsIdAvailableRouteImport } from './routes/api/fleet.endpoints.$id.available'
import { Route as ApiFleetDefsIdVersionsRouteImport } from './routes/api/fleet.defs.$id.versions'
import { Route as ApiFleetDefsIdMcpRouteImport } from './routes/api/fleet.defs.$id.mcp'
import { Route as ApiFleetDefsIdEditRouteImport } from './routes/api/fleet.defs.$id.edit'
import { Route as ApiFleetAgentsIdControlRouteImport } from './routes/api/fleet.agents.$id.control'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInferenceRoute = ApiInferenceRouteImport.update({
  id: '/api/inference',
  path: '/api/inference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetRoute = ApiFleetRouteImport.update({
  id: '/api/fleet',
  path: '/api/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsRoute = ApiChannelsRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppInferenceRoute = AppInferenceRouteImport.update({
  id: '/inference',
  path: '/inference',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppCostRoute = AppCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardsIndexRoute = AppBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryIdRoute = ApiMemoryIdRouteImport.update({
  id: '/api/memory/$id',
  path: '/api/memory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiMcpRoute,
} as any)
const ApiKeysIdRoute = ApiKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiKeysRoute,
} as any)
const ApiFleetRenderRoute = ApiFleetRenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiFleetReconcileRoute = ApiFleetReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiFleetEndpointsRoute = ApiFleetEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiFleetDefsRoute = ApiFleetDefsRouteImport.update({
  id: '/defs',
  path: '/defs',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiFleetCreateRoute = ApiFleetCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiFleetContainersRoute = ApiFleetContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => ApiFleetRoute,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiChannelsIdRoute = ApiChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChannelsRoute,
} as any)
const ApiBoardsIdRoute = ApiBoardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBoardsRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRegisterRoute = ApiAgentsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoardsBoardIdRoute = AppBoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => AppRoute,
} as any)
const ApiTeamsIdMembersRoute = ApiTeamsIdMembersRouteImport.update({
  id: '/$id/members',
  path: '/$id/members',
  getParentRoute: () => ApiTeamsRoute,
} as any)
const ApiTasksIdWatchersRoute = ApiTasksIdWatchersRouteImport.update({
  id: '/watchers',
  path: '/watchers',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdUsageRoute = ApiTasksIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdReviewRoute = ApiTasksIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdDependenciesRoute = ApiTasksIdDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdCommentsRoute = ApiTasksIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiSkillsOwnerNameRoute = ApiSkillsOwnerNameRouteImport.update({
  id: '/$owner/$name',
  path: '/$owner/$name',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiLlmV1ModelsRoute = ApiLlmV1ModelsRouteImport.update({
  id: '/api/llm/v1/models',
  path: '/api/llm/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetEndpointsIdRoute = ApiFleetEndpointsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFleetEndpointsRoute,
} as any)
const ApiFleetDefsIdRoute = ApiFleetDefsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFleetDefsRoute,
} as any)
const ApiChannelsIdPlanRoute = ApiChannelsIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdMessagesRoute = ApiChannelsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdMembersRoute = ApiChannelsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdEventsRoute = ApiChannelsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdAgentsRoute = ApiChannelsIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiBoardsIdTasksRoute = ApiBoardsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdMembersRoute = ApiBoardsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdEventsRoute = ApiBoardsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdAgentsRoute = ApiBoardsIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAgentsIdHeartbeatRoute = ApiAgentsIdHeartbeatRouteImport.update({
  id: '/$id/heartbeat',
  path: '/$id/heartbeat',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const AppBoardsBoardIdTaskIdRoute = AppBoardsBoardIdTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppBoardsBoardIdRoute,
} as any)
const ApiLlmV1ChatCompletionsRoute = ApiLlmV1ChatCompletionsRouteImport.update({
  id: '/api/llm/v1/chat/completions',
  path: '/api/llm/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetEndpointsIdAvailableRoute =
  ApiFleetEndpointsIdAvailableRouteImport.update({
    id: '/available',
    path: '/available',
    getParentRoute: () => ApiFleetEndpointsIdRoute,
  } as any)
const ApiFleetDefsIdVersionsRoute = ApiFleetDefsIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiFleetDefsIdRoute,
} as any)
const ApiFleetDefsIdMcpRoute = ApiFleetDefsIdMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ApiFleetDefsIdRoute,
} as any)
const ApiFleetDefsIdEditRoute = ApiFleetDefsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApiFleetDefsIdRoute,
} as any)
const ApiFleetAgentsIdControlRoute = ApiFleetAgentsIdControlRouteImport.update({
  id: '/agents/$id/control',
  path: '/agents/$id/control',
  getParentRoute: () => ApiFleetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/channels': typeof AppChannelsRoute
  '/chat': typeof AppChatRoute
  '/cost': typeof AppCostRoute
  '/fleet': typeof AppFleetRoute
  '/inbox': typeof AppInboxRoute
  '/inference': typeof AppInferenceRoute
  '/mcp': typeof AppMcpRoute
  '/memory': typeof AppMemoryRoute
  '/models': typeof AppModelsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/alerts': typeof ApiAlertsRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/home': typeof ApiHomeRoute
  '/api/inference': typeof ApiInferenceRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/fleet/containers': typeof ApiFleetContainersRoute
  '/api/fleet/create': typeof ApiFleetCreateRoute
  '/api/fleet/defs': typeof ApiFleetDefsRouteWithChildren
  '/api/fleet/endpoints': typeof ApiFleetEndpointsRouteWithChildren
  '/api/fleet/reconcile': typeof ApiFleetReconcileRoute
  '/api/fleet/render': typeof ApiFleetRenderRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/memory/$id': typeof ApiMemoryIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/boards/': typeof AppBoardsIndexRoute
  '/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/channels/$id/plan': typeof ApiChannelsIdPlanRoute
  '/api/fleet/defs/$id': typeof ApiFleetDefsIdRouteWithChildren
  '/api/fleet/endpoints/$id': typeof ApiFleetEndpointsIdRouteWithChildren
  '/api/llm/v1/models': typeof ApiLlmV1ModelsRoute
  '/api/skills/$owner/$name': typeof ApiSkillsOwnerNameRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/usage': typeof ApiTasksIdUsageRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
  '/api/fleet/agents/$id/control': typeof ApiFleetAgentsIdControlRoute
  '/api/fleet/defs/$id/edit': typeof ApiFleetDefsIdEditRoute
  '/api/fleet/defs/$id/mcp': typeof ApiFleetDefsIdMcpRoute
  '/api/fleet/defs/$id/versions': typeof ApiFleetDefsIdVersionsRoute
  '/api/fleet/endpoints/$id/available': typeof ApiFleetEndpointsIdAvailableRoute
  '/api/llm/v1/chat/completions': typeof ApiLlmV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/channels': typeof AppChannelsRoute
  '/chat': typeof AppChatRoute
  '/cost': typeof AppCostRoute
  '/fleet': typeof AppFleetRoute
  '/inbox': typeof AppInboxRoute
  '/inference': typeof AppInferenceRoute
  '/mcp': typeof AppMcpRoute
  '/memory': typeof AppMemoryRoute
  '/models': typeof AppModelsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/alerts': typeof ApiAlertsRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/home': typeof ApiHomeRoute
  '/api/inference': typeof ApiInferenceRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/': typeof AppIndexRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/fleet/containers': typeof ApiFleetContainersRoute
  '/api/fleet/create': typeof ApiFleetCreateRoute
  '/api/fleet/defs': typeof ApiFleetDefsRouteWithChildren
  '/api/fleet/endpoints': typeof ApiFleetEndpointsRouteWithChildren
  '/api/fleet/reconcile': typeof ApiFleetReconcileRoute
  '/api/fleet/render': typeof ApiFleetRenderRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/memory/$id': typeof ApiMemoryIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/boards': typeof AppBoardsIndexRoute
  '/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/channels/$id/plan': typeof ApiChannelsIdPlanRoute
  '/api/fleet/defs/$id': typeof ApiFleetDefsIdRouteWithChildren
  '/api/fleet/endpoints/$id': typeof ApiFleetEndpointsIdRouteWithChildren
  '/api/llm/v1/models': typeof ApiLlmV1ModelsRoute
  '/api/skills/$owner/$name': typeof ApiSkillsOwnerNameRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/usage': typeof ApiTasksIdUsageRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
  '/api/fleet/agents/$id/control': typeof ApiFleetAgentsIdControlRoute
  '/api/fleet/defs/$id/edit': typeof ApiFleetDefsIdEditRoute
  '/api/fleet/defs/$id/mcp': typeof ApiFleetDefsIdMcpRoute
  '/api/fleet/defs/$id/versions': typeof ApiFleetDefsIdVersionsRoute
  '/api/fleet/endpoints/$id/available': typeof ApiFleetEndpointsIdAvailableRoute
  '/api/llm/v1/chat/completions': typeof ApiLlmV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/cost': typeof AppCostRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/inference': typeof AppInferenceRoute
  '/_app/mcp': typeof AppMcpRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/alerts': typeof ApiAlertsRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/home': typeof ApiHomeRoute
  '/api/inference': typeof ApiInferenceRoute
  '/api/keys': typeof ApiKeysRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/fleet/containers': typeof ApiFleetContainersRoute
  '/api/fleet/create': typeof ApiFleetCreateRoute
  '/api/fleet/defs': typeof ApiFleetDefsRouteWithChildren
  '/api/fleet/endpoints': typeof ApiFleetEndpointsRouteWithChildren
  '/api/fleet/reconcile': typeof ApiFleetReconcileRoute
  '/api/fleet/render': typeof ApiFleetRenderRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/memory/$id': typeof ApiMemoryIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/_app/boards/': typeof AppBoardsIndexRoute
  '/_app/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/channels/$id/plan': typeof ApiChannelsIdPlanRoute
  '/api/fleet/defs/$id': typeof ApiFleetDefsIdRouteWithChildren
  '/api/fleet/endpoints/$id': typeof ApiFleetEndpointsIdRouteWithChildren
  '/api/llm/v1/models': typeof ApiLlmV1ModelsRoute
  '/api/skills/$owner/$name': typeof ApiSkillsOwnerNameRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/usage': typeof ApiTasksIdUsageRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
  '/api/fleet/agents/$id/control': typeof ApiFleetAgentsIdControlRoute
  '/api/fleet/defs/$id/edit': typeof ApiFleetDefsIdEditRoute
  '/api/fleet/defs/$id/mcp': typeof ApiFleetDefsIdMcpRoute
  '/api/fleet/defs/$id/versions': typeof ApiFleetDefsIdVersionsRoute
  '/api/fleet/endpoints/$id/available': typeof ApiFleetEndpointsIdAvailableRoute
  '/api/llm/v1/chat/completions': typeof ApiLlmV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/channels'
    | '/chat'
    | '/cost'
    | '/fleet'
    | '/inbox'
    | '/inference'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/settings'
    | '/skills'
    | '/api/activity'
    | '/api/agents'
    | '/api/alerts'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/history'
    | '/api/home'
    | '/api/inference'
    | '/api/keys'
    | '/api/mcp'
    | '/api/notifications'
    | '/api/profile'
    | '/api/skills'
    | '/api/teams'
    | '/api/uploads'
    | '/api/users'
    | '/boards/$boardId'
    | '/api/admin/users'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/fleet/containers'
    | '/api/fleet/create'
    | '/api/fleet/defs'
    | '/api/fleet/endpoints'
    | '/api/fleet/reconcile'
    | '/api/fleet/render'
    | '/api/keys/$id'
    | '/api/mcp/test'
    | '/api/memory/$id'
    | '/api/tasks/$id'
    | '/api/uploads/$id'
    | '/boards/'
    | '/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/channels/$id/plan'
    | '/api/fleet/defs/$id'
    | '/api/fleet/endpoints/$id'
    | '/api/llm/v1/models'
    | '/api/skills/$owner/$name'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/usage'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
    | '/api/fleet/agents/$id/control'
    | '/api/fleet/defs/$id/edit'
    | '/api/fleet/defs/$id/mcp'
    | '/api/fleet/defs/$id/versions'
    | '/api/fleet/endpoints/$id/available'
    | '/api/llm/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/channels'
    | '/chat'
    | '/cost'
    | '/fleet'
    | '/inbox'
    | '/inference'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/settings'
    | '/skills'
    | '/api/activity'
    | '/api/agents'
    | '/api/alerts'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/history'
    | '/api/home'
    | '/api/inference'
    | '/api/keys'
    | '/api/mcp'
    | '/api/notifications'
    | '/api/profile'
    | '/api/skills'
    | '/api/teams'
    | '/api/uploads'
    | '/api/users'
    | '/'
    | '/boards/$boardId'
    | '/api/admin/users'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/fleet/containers'
    | '/api/fleet/create'
    | '/api/fleet/defs'
    | '/api/fleet/endpoints'
    | '/api/fleet/reconcile'
    | '/api/fleet/render'
    | '/api/keys/$id'
    | '/api/mcp/test'
    | '/api/memory/$id'
    | '/api/tasks/$id'
    | '/api/uploads/$id'
    | '/boards'
    | '/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/channels/$id/plan'
    | '/api/fleet/defs/$id'
    | '/api/fleet/endpoints/$id'
    | '/api/llm/v1/models'
    | '/api/skills/$owner/$name'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/usage'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
    | '/api/fleet/agents/$id/control'
    | '/api/fleet/defs/$id/edit'
    | '/api/fleet/defs/$id/mcp'
    | '/api/fleet/defs/$id/versions'
    | '/api/fleet/endpoints/$id/available'
    | '/api/llm/v1/chat/completions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/agents'
    | '/_app/alerts'
    | '/_app/channels'
    | '/_app/chat'
    | '/_app/cost'
    | '/_app/fleet'
    | '/_app/inbox'
    | '/_app/inference'
    | '/_app/mcp'
    | '/_app/memory'
    | '/_app/models'
    | '/_app/settings'
    | '/_app/skills'
    | '/api/activity'
    | '/api/agents'
    | '/api/alerts'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/history'
    | '/api/home'
    | '/api/inference'
    | '/api/keys'
    | '/api/mcp'
    | '/api/notifications'
    | '/api/profile'
    | '/api/skills'
    | '/api/teams'
    | '/api/uploads'
    | '/api/users'
    | '/_app/'
    | '/_app/boards/$boardId'
    | '/api/admin/users'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/fleet/containers'
    | '/api/fleet/create'
    | '/api/fleet/defs'
    | '/api/fleet/endpoints'
    | '/api/fleet/reconcile'
    | '/api/fleet/render'
    | '/api/keys/$id'
    | '/api/mcp/test'
    | '/api/memory/$id'
    | '/api/tasks/$id'
    | '/api/uploads/$id'
    | '/_app/boards/'
    | '/_app/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/channels/$id/plan'
    | '/api/fleet/defs/$id'
    | '/api/fleet/endpoints/$id'
    | '/api/llm/v1/models'
    | '/api/skills/$owner/$name'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/usage'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
    | '/api/fleet/agents/$id/control'
    | '/api/fleet/defs/$id/edit'
    | '/api/fleet/defs/$id/mcp'
    | '/api/fleet/defs/$id/versions'
    | '/api/fleet/endpoints/$id/available'
    | '/api/llm/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiBoardsRoute: typeof ApiBoardsRouteWithChildren
  ApiChannelsRoute: typeof ApiChannelsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiCostRoute: typeof ApiCostRoute
  ApiFleetRoute: typeof ApiFleetRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiHomeRoute: typeof ApiHomeRoute
  ApiInferenceRoute: typeof ApiInferenceRoute
  ApiKeysRoute: typeof ApiKeysRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiTeamsRoute: typeof ApiTeamsRouteWithChildren
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiMemoryIdRoute: typeof ApiMemoryIdRoute
  ApiTasksIdRoute: typeof ApiTasksIdRouteWithChildren
  ApiLlmV1ModelsRoute: typeof ApiLlmV1ModelsRoute
  ApiLlmV1ChatCompletionsRoute: typeof ApiLlmV1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inference': {
      id: '/api/inference'
      path: '/api/inference'
      fullPath: '/api/inference'
      preLoaderRoute: typeof ApiInferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet': {
      id: '/api/fleet'
      path: '/api/fleet'
      fullPath: '/api/fleet'
      preLoaderRoute: typeof ApiFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inference': {
      id: '/_app/inference'
      path: '/inference'
      fullPath: '/inference'
      preLoaderRoute: typeof AppInferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cost': {
      id: '/_app/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AppCostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/': {
      id: '/_app/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AppBoardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/$id': {
      id: '/api/memory/$id'
      path: '/api/memory/$id'
      fullPath: '/api/memory/$id'
      preLoaderRoute: typeof ApiMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/test': {
      id: '/api/mcp/test'
      path: '/test'
      fullPath: '/api/mcp/test'
      preLoaderRoute: typeof ApiMcpTestRouteImport
      parentRoute: typeof ApiMcpRoute
    }
    '/api/keys/$id': {
      id: '/api/keys/$id'
      path: '/$id'
      fullPath: '/api/keys/$id'
      preLoaderRoute: typeof ApiKeysIdRouteImport
      parentRoute: typeof ApiKeysRoute
    }
    '/api/fleet/render': {
      id: '/api/fleet/render'
      path: '/render'
      fullPath: '/api/fleet/render'
      preLoaderRoute: typeof ApiFleetRenderRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/fleet/reconcile': {
      id: '/api/fleet/reconcile'
      path: '/reconcile'
      fullPath: '/api/fleet/reconcile'
      preLoaderRoute: typeof ApiFleetReconcileRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/fleet/endpoints': {
      id: '/api/fleet/endpoints'
      path: '/endpoints'
      fullPath: '/api/fleet/endpoints'
      preLoaderRoute: typeof ApiFleetEndpointsRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/fleet/defs': {
      id: '/api/fleet/defs'
      path: '/defs'
      fullPath: '/api/fleet/defs'
      preLoaderRoute: typeof ApiFleetDefsRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/fleet/create': {
      id: '/api/fleet/create'
      path: '/create'
      fullPath: '/api/fleet/create'
      preLoaderRoute: typeof ApiFleetCreateRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/fleet/containers': {
      id: '/api/fleet/containers'
      path: '/containers'
      fullPath: '/api/fleet/containers'
      preLoaderRoute: typeof ApiFleetContainersRouteImport
      parentRoute: typeof ApiFleetRoute
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/channels/$id': {
      id: '/api/channels/$id'
      path: '/$id'
      fullPath: '/api/channels/$id'
      preLoaderRoute: typeof ApiChannelsIdRouteImport
      parentRoute: typeof ApiChannelsRoute
    }
    '/api/boards/$id': {
      id: '/api/boards/$id'
      path: '/$id'
      fullPath: '/api/boards/$id'
      preLoaderRoute: typeof ApiBoardsIdRouteImport
      parentRoute: typeof ApiBoardsRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/register': {
      id: '/api/agents/register'
      path: '/register'
      fullPath: '/api/agents/register'
      preLoaderRoute: typeof ApiAgentsRegisterRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/boards/$boardId': {
      id: '/_app/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AppBoardsBoardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/teams/$id/members': {
      id: '/api/teams/$id/members'
      path: '/$id/members'
      fullPath: '/api/teams/$id/members'
      preLoaderRoute: typeof ApiTeamsIdMembersRouteImport
      parentRoute: typeof ApiTeamsRoute
    }
    '/api/tasks/$id/watchers': {
      id: '/api/tasks/$id/watchers'
      path: '/watchers'
      fullPath: '/api/tasks/$id/watchers'
      preLoaderRoute: typeof ApiTasksIdWatchersRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/usage': {
      id: '/api/tasks/$id/usage'
      path: '/usage'
      fullPath: '/api/tasks/$id/usage'
      preLoaderRoute: typeof ApiTasksIdUsageRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/review': {
      id: '/api/tasks/$id/review'
      path: '/review'
      fullPath: '/api/tasks/$id/review'
      preLoaderRoute: typeof ApiTasksIdReviewRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/dependencies': {
      id: '/api/tasks/$id/dependencies'
      path: '/dependencies'
      fullPath: '/api/tasks/$id/dependencies'
      preLoaderRoute: typeof ApiTasksIdDependenciesRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/comments': {
      id: '/api/tasks/$id/comments'
      path: '/comments'
      fullPath: '/api/tasks/$id/comments'
      preLoaderRoute: typeof ApiTasksIdCommentsRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/skills/$owner/$name': {
      id: '/api/skills/$owner/$name'
      path: '/$owner/$name'
      fullPath: '/api/skills/$owner/$name'
      preLoaderRoute: typeof ApiSkillsOwnerNameRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/llm/v1/models': {
      id: '/api/llm/v1/models'
      path: '/api/llm/v1/models'
      fullPath: '/api/llm/v1/models'
      preLoaderRoute: typeof ApiLlmV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/endpoints/$id': {
      id: '/api/fleet/endpoints/$id'
      path: '/$id'
      fullPath: '/api/fleet/endpoints/$id'
      preLoaderRoute: typeof ApiFleetEndpointsIdRouteImport
      parentRoute: typeof ApiFleetEndpointsRoute
    }
    '/api/fleet/defs/$id': {
      id: '/api/fleet/defs/$id'
      path: '/$id'
      fullPath: '/api/fleet/defs/$id'
      preLoaderRoute: typeof ApiFleetDefsIdRouteImport
      parentRoute: typeof ApiFleetDefsRoute
    }
    '/api/channels/$id/plan': {
      id: '/api/channels/$id/plan'
      path: '/plan'
      fullPath: '/api/channels/$id/plan'
      preLoaderRoute: typeof ApiChannelsIdPlanRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/messages': {
      id: '/api/channels/$id/messages'
      path: '/messages'
      fullPath: '/api/channels/$id/messages'
      preLoaderRoute: typeof ApiChannelsIdMessagesRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/members': {
      id: '/api/channels/$id/members'
      path: '/members'
      fullPath: '/api/channels/$id/members'
      preLoaderRoute: typeof ApiChannelsIdMembersRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/events': {
      id: '/api/channels/$id/events'
      path: '/events'
      fullPath: '/api/channels/$id/events'
      preLoaderRoute: typeof ApiChannelsIdEventsRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/agents': {
      id: '/api/channels/$id/agents'
      path: '/agents'
      fullPath: '/api/channels/$id/agents'
      preLoaderRoute: typeof ApiChannelsIdAgentsRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/boards/$id/tasks': {
      id: '/api/boards/$id/tasks'
      path: '/tasks'
      fullPath: '/api/boards/$id/tasks'
      preLoaderRoute: typeof ApiBoardsIdTasksRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/members': {
      id: '/api/boards/$id/members'
      path: '/members'
      fullPath: '/api/boards/$id/members'
      preLoaderRoute: typeof ApiBoardsIdMembersRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/events': {
      id: '/api/boards/$id/events'
      path: '/events'
      fullPath: '/api/boards/$id/events'
      preLoaderRoute: typeof ApiBoardsIdEventsRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/agents': {
      id: '/api/boards/$id/agents'
      path: '/agents'
      fullPath: '/api/boards/$id/agents'
      preLoaderRoute: typeof ApiBoardsIdAgentsRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/agents/$id/heartbeat': {
      id: '/api/agents/$id/heartbeat'
      path: '/$id/heartbeat'
      fullPath: '/api/agents/$id/heartbeat'
      preLoaderRoute: typeof ApiAgentsIdHeartbeatRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/_app/boards/$boardId/$taskId': {
      id: '/_app/boards/$boardId/$taskId'
      path: '/$taskId'
      fullPath: '/boards/$boardId/$taskId'
      preLoaderRoute: typeof AppBoardsBoardIdTaskIdRouteImport
      parentRoute: typeof AppBoardsBoardIdRoute
    }
    '/api/llm/v1/chat/completions': {
      id: '/api/llm/v1/chat/completions'
      path: '/api/llm/v1/chat/completions'
      fullPath: '/api/llm/v1/chat/completions'
      preLoaderRoute: typeof ApiLlmV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/endpoints/$id/available': {
      id: '/api/fleet/endpoints/$id/available'
      path: '/available'
      fullPath: '/api/fleet/endpoints/$id/available'
      preLoaderRoute: typeof ApiFleetEndpointsIdAvailableRouteImport
      parentRoute: typeof ApiFleetEndpointsIdRoute
    }
    '/api/fleet/defs/$id/versions': {
      id: '/api/fleet/defs/$id/versions'
      path: '/versions'
      fullPath: '/api/fleet/defs/$id/versions'
      preLoaderRoute: typeof ApiFleetDefsIdVersionsRouteImport
      parentRoute: typeof ApiFleetDefsIdRoute
    }
    '/api/fleet/defs/$id/mcp': {
      id: '/api/fleet/defs/$id/mcp'
      path: '/mcp'
      fullPath: '/api/fleet/defs/$id/mcp'
      preLoaderRoute: typeof ApiFleetDefsIdMcpRouteImport
      parentRoute: typeof ApiFleetDefsIdRoute
    }
    '/api/fleet/defs/$id/edit': {
      id: '/api/fleet/defs/$id/edit'
      path: '/edit'
      fullPath: '/api/fleet/defs/$id/edit'
      preLoaderRoute: typeof ApiFleetDefsIdEditRouteImport
      parentRoute: typeof ApiFleetDefsIdRoute
    }
    '/api/fleet/agents/$id/control': {
      id: '/api/fleet/agents/$id/control'
      path: '/agents/$id/control'
      fullPath: '/api/fleet/agents/$id/control'
      preLoaderRoute: typeof ApiFleetAgentsIdControlRouteImport
      parentRoute: typeof ApiFleetRoute
    }
  }
}

interface AppBoardsBoardIdRouteChildren {
  AppBoardsBoardIdTaskIdRoute: typeof AppBoardsBoardIdTaskIdRoute
}

const AppBoardsBoardIdRouteChildren: AppBoardsBoardIdRouteChildren = {
  AppBoardsBoardIdTaskIdRoute: AppBoardsBoardIdTaskIdRoute,
}

const AppBoardsBoardIdRouteWithChildren =
  AppBoardsBoardIdRoute._addFileChildren(AppBoardsBoardIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppChatRoute: typeof AppChatRoute
  AppCostRoute: typeof AppCostRoute
  AppFleetRoute: typeof AppFleetRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInferenceRoute: typeof AppInferenceRoute
  AppMcpRoute: typeof AppMcpRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppModelsRoute: typeof AppModelsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBoardsBoardIdRoute: typeof AppBoardsBoardIdRouteWithChildren
  AppBoardsIndexRoute: typeof AppBoardsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppChatRoute: AppChatRoute,
  AppCostRoute: AppCostRoute,
  AppFleetRoute: AppFleetRoute,
  AppInboxRoute: AppInboxRoute,
  AppInferenceRoute: AppInferenceRoute,
  AppMcpRoute: AppMcpRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppModelsRoute: AppModelsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBoardsBoardIdRoute: AppBoardsBoardIdRouteWithChildren,
  AppBoardsIndexRoute: AppBoardsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAgentsRouteChildren {
  ApiAgentsRegisterRoute: typeof ApiAgentsRegisterRoute
  ApiAgentsIdHeartbeatRoute: typeof ApiAgentsIdHeartbeatRoute
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsRegisterRoute: ApiAgentsRegisterRoute,
  ApiAgentsIdHeartbeatRoute: ApiAgentsIdHeartbeatRoute,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiBoardsIdRouteChildren {
  ApiBoardsIdAgentsRoute: typeof ApiBoardsIdAgentsRoute
  ApiBoardsIdEventsRoute: typeof ApiBoardsIdEventsRoute
  ApiBoardsIdMembersRoute: typeof ApiBoardsIdMembersRoute
  ApiBoardsIdTasksRoute: typeof ApiBoardsIdTasksRoute
}

const ApiBoardsIdRouteChildren: ApiBoardsIdRouteChildren = {
  ApiBoardsIdAgentsRoute: ApiBoardsIdAgentsRoute,
  ApiBoardsIdEventsRoute: ApiBoardsIdEventsRoute,
  ApiBoardsIdMembersRoute: ApiBoardsIdMembersRoute,
  ApiBoardsIdTasksRoute: ApiBoardsIdTasksRoute,
}

const ApiBoardsIdRouteWithChildren = ApiBoardsIdRoute._addFileChildren(
  ApiBoardsIdRouteChildren,
)

interface ApiBoardsRouteChildren {
  ApiBoardsIdRoute: typeof ApiBoardsIdRouteWithChildren
}

const ApiBoardsRouteChildren: ApiBoardsRouteChildren = {
  ApiBoardsIdRoute: ApiBoardsIdRouteWithChildren,
}

const ApiBoardsRouteWithChildren = ApiBoardsRoute._addFileChildren(
  ApiBoardsRouteChildren,
)

interface ApiChannelsIdRouteChildren {
  ApiChannelsIdAgentsRoute: typeof ApiChannelsIdAgentsRoute
  ApiChannelsIdEventsRoute: typeof ApiChannelsIdEventsRoute
  ApiChannelsIdMembersRoute: typeof ApiChannelsIdMembersRoute
  ApiChannelsIdMessagesRoute: typeof ApiChannelsIdMessagesRoute
  ApiChannelsIdPlanRoute: typeof ApiChannelsIdPlanRoute
}

const ApiChannelsIdRouteChildren: ApiChannelsIdRouteChildren = {
  ApiChannelsIdAgentsRoute: ApiChannelsIdAgentsRoute,
  ApiChannelsIdEventsRoute: ApiChannelsIdEventsRoute,
  ApiChannelsIdMembersRoute: ApiChannelsIdMembersRoute,
  ApiChannelsIdMessagesRoute: ApiChannelsIdMessagesRoute,
  ApiChannelsIdPlanRoute: ApiChannelsIdPlanRoute,
}

const ApiChannelsIdRouteWithChildren = ApiChannelsIdRoute._addFileChildren(
  ApiChannelsIdRouteChildren,
)

interface ApiChannelsRouteChildren {
  ApiChannelsIdRoute: typeof ApiChannelsIdRouteWithChildren
}

const ApiChannelsRouteChildren: ApiChannelsRouteChildren = {
  ApiChannelsIdRoute: ApiChannelsIdRouteWithChildren,
}

const ApiChannelsRouteWithChildren = ApiChannelsRoute._addFileChildren(
  ApiChannelsRouteChildren,
)

interface ApiConversationsRouteChildren {
  ApiConversationsIdRoute: typeof ApiConversationsIdRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdRoute: ApiConversationsIdRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiFleetDefsIdRouteChildren {
  ApiFleetDefsIdEditRoute: typeof ApiFleetDefsIdEditRoute
  ApiFleetDefsIdMcpRoute: typeof ApiFleetDefsIdMcpRoute
  ApiFleetDefsIdVersionsRoute: typeof ApiFleetDefsIdVersionsRoute
}

const ApiFleetDefsIdRouteChildren: ApiFleetDefsIdRouteChildren = {
  ApiFleetDefsIdEditRoute: ApiFleetDefsIdEditRoute,
  ApiFleetDefsIdMcpRoute: ApiFleetDefsIdMcpRoute,
  ApiFleetDefsIdVersionsRoute: ApiFleetDefsIdVersionsRoute,
}

const ApiFleetDefsIdRouteWithChildren = ApiFleetDefsIdRoute._addFileChildren(
  ApiFleetDefsIdRouteChildren,
)

interface ApiFleetDefsRouteChildren {
  ApiFleetDefsIdRoute: typeof ApiFleetDefsIdRouteWithChildren
}

const ApiFleetDefsRouteChildren: ApiFleetDefsRouteChildren = {
  ApiFleetDefsIdRoute: ApiFleetDefsIdRouteWithChildren,
}

const ApiFleetDefsRouteWithChildren = ApiFleetDefsRoute._addFileChildren(
  ApiFleetDefsRouteChildren,
)

interface ApiFleetEndpointsIdRouteChildren {
  ApiFleetEndpointsIdAvailableRoute: typeof ApiFleetEndpointsIdAvailableRoute
}

const ApiFleetEndpointsIdRouteChildren: ApiFleetEndpointsIdRouteChildren = {
  ApiFleetEndpointsIdAvailableRoute: ApiFleetEndpointsIdAvailableRoute,
}

const ApiFleetEndpointsIdRouteWithChildren =
  ApiFleetEndpointsIdRoute._addFileChildren(ApiFleetEndpointsIdRouteChildren)

interface ApiFleetEndpointsRouteChildren {
  ApiFleetEndpointsIdRoute: typeof ApiFleetEndpointsIdRouteWithChildren
}

const ApiFleetEndpointsRouteChildren: ApiFleetEndpointsRouteChildren = {
  ApiFleetEndpointsIdRoute: ApiFleetEndpointsIdRouteWithChildren,
}

const ApiFleetEndpointsRouteWithChildren =
  ApiFleetEndpointsRoute._addFileChildren(ApiFleetEndpointsRouteChildren)

interface ApiFleetRouteChildren {
  ApiFleetContainersRoute: typeof ApiFleetContainersRoute
  ApiFleetCreateRoute: typeof ApiFleetCreateRoute
  ApiFleetDefsRoute: typeof ApiFleetDefsRouteWithChildren
  ApiFleetEndpointsRoute: typeof ApiFleetEndpointsRouteWithChildren
  ApiFleetReconcileRoute: typeof ApiFleetReconcileRoute
  ApiFleetRenderRoute: typeof ApiFleetRenderRoute
  ApiFleetAgentsIdControlRoute: typeof ApiFleetAgentsIdControlRoute
}

const ApiFleetRouteChildren: ApiFleetRouteChildren = {
  ApiFleetContainersRoute: ApiFleetContainersRoute,
  ApiFleetCreateRoute: ApiFleetCreateRoute,
  ApiFleetDefsRoute: ApiFleetDefsRouteWithChildren,
  ApiFleetEndpointsRoute: ApiFleetEndpointsRouteWithChildren,
  ApiFleetReconcileRoute: ApiFleetReconcileRoute,
  ApiFleetRenderRoute: ApiFleetRenderRoute,
  ApiFleetAgentsIdControlRoute: ApiFleetAgentsIdControlRoute,
}

const ApiFleetRouteWithChildren = ApiFleetRoute._addFileChildren(
  ApiFleetRouteChildren,
)

interface ApiKeysRouteChildren {
  ApiKeysIdRoute: typeof ApiKeysIdRoute
}

const ApiKeysRouteChildren: ApiKeysRouteChildren = {
  ApiKeysIdRoute: ApiKeysIdRoute,
}

const ApiKeysRouteWithChildren =
  ApiKeysRoute._addFileChildren(ApiKeysRouteChildren)

interface ApiMcpRouteChildren {
  ApiMcpTestRoute: typeof ApiMcpTestRoute
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpTestRoute: ApiMcpTestRoute,
}

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren)

interface ApiSkillsRouteChildren {
  ApiSkillsOwnerNameRoute: typeof ApiSkillsOwnerNameRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsOwnerNameRoute: ApiSkillsOwnerNameRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiTeamsRouteChildren {
  ApiTeamsIdMembersRoute: typeof ApiTeamsIdMembersRoute
}

const ApiTeamsRouteChildren: ApiTeamsRouteChildren = {
  ApiTeamsIdMembersRoute: ApiTeamsIdMembersRoute,
}

const ApiTeamsRouteWithChildren = ApiTeamsRoute._addFileChildren(
  ApiTeamsRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

interface ApiTasksIdRouteChildren {
  ApiTasksIdCommentsRoute: typeof ApiTasksIdCommentsRoute
  ApiTasksIdDependenciesRoute: typeof ApiTasksIdDependenciesRoute
  ApiTasksIdReviewRoute: typeof ApiTasksIdReviewRoute
  ApiTasksIdUsageRoute: typeof ApiTasksIdUsageRoute
  ApiTasksIdWatchersRoute: typeof ApiTasksIdWatchersRoute
}

const ApiTasksIdRouteChildren: ApiTasksIdRouteChildren = {
  ApiTasksIdCommentsRoute: ApiTasksIdCommentsRoute,
  ApiTasksIdDependenciesRoute: ApiTasksIdDependenciesRoute,
  ApiTasksIdReviewRoute: ApiTasksIdReviewRoute,
  ApiTasksIdUsageRoute: ApiTasksIdUsageRoute,
  ApiTasksIdWatchersRoute: ApiTasksIdWatchersRoute,
}

const ApiTasksIdRouteWithChildren = ApiTasksIdRoute._addFileChildren(
  ApiTasksIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiBoardsRoute: ApiBoardsRouteWithChildren,
  ApiChannelsRoute: ApiChannelsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiCostRoute: ApiCostRoute,
  ApiFleetRoute: ApiFleetRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiHomeRoute: ApiHomeRoute,
  ApiInferenceRoute: ApiInferenceRoute,
  ApiKeysRoute: ApiKeysRouteWithChildren,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiTeamsRoute: ApiTeamsRouteWithChildren,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiUsersRoute: ApiUsersRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiMemoryIdRoute: ApiMemoryIdRoute,
  ApiTasksIdRoute: ApiTasksIdRouteWithChildren,
  ApiLlmV1ModelsRoute: ApiLlmV1ModelsRoute,
  ApiLlmV1ChatCompletionsRoute: ApiLlmV1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
