/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiFleetRouteImport } from './routes/api/fleet'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChannelsRouteImport } from './routes/api/channels'
import { Route as ApiBoardsRouteImport } from './routes/api/boards'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppMcpRouteImport } from './routes/_app/mcp'
import { Route as AppInferenceRouteImport } from './routes/_app/inference'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppCostRouteImport } from './routes/_app/cost'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppBoardsIndexRouteImport } from './routes/_app/boards/index'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations.$id'
import { Route as ApiChannelsIdRouteImport } from './routes/api/channels.$id'
import { Route as ApiBoardsIdRouteImport } from './routes/api/boards.$id'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAgentsRegisterRouteImport } from './routes/api/agents.register'
import { Route as AppBoardsBoardIdRouteImport } from './routes/_app/boards/$boardId'
import { Route as ApiTeamsIdMembersRouteImport } from './routes/api/teams.$id.members'
import { Route as ApiTasksIdWatchersRouteImport } from './routes/api/tasks.$id.watchers'
import { Route as ApiTasksIdReviewRouteImport } from './routes/api/tasks.$id.review'
import { Route as ApiTasksIdDependenciesRouteImport } from './routes/api/tasks.$id.dependencies'
import { Route as ApiTasksIdCommentsRouteImport } from './routes/api/tasks.$id.comments'
import { Route as ApiChannelsIdMessagesRouteImport } from './routes/api/channels.$id.messages'
import { Route as ApiChannelsIdMembersRouteImport } from './routes/api/channels.$id.members'
import { Route as ApiChannelsIdEventsRouteImport } from './routes/api/channels.$id.events'
import { Route as ApiChannelsIdAgentsRouteImport } from './routes/api/channels.$id.agents'
import { Route as ApiBoardsIdTasksRouteImport } from './routes/api/boards.$id.tasks'
import { Route as ApiBoardsIdMembersRouteImport } from './routes/api/boards.$id.members'
import { Route as ApiBoardsIdEventsRouteImport } from './routes/api/boards.$id.events'
import { Route as ApiBoardsIdAgentsRouteImport } from './routes/api/boards.$id.agents'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'
import { Route as ApiAgentsIdHeartbeatRouteImport } from './routes/api/agents.$id.heartbeat'
import { Route as AppBoardsBoardIdTaskIdRouteImport } from './routes/_app/boards/$boardId.$taskId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetRoute = ApiFleetRouteImport.update({
  id: '/api/fleet',
  path: '/api/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsRoute = ApiChannelsRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppInferenceRoute = AppInferenceRouteImport.update({
  id: '/inference',
  path: '/inference',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppCostRoute = AppCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardsIndexRoute = AppBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiChannelsIdRoute = ApiChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChannelsRoute,
} as any)
const ApiBoardsIdRoute = ApiBoardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBoardsRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRegisterRoute = ApiAgentsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const AppBoardsBoardIdRoute = AppBoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => AppRoute,
} as any)
const ApiTeamsIdMembersRoute = ApiTeamsIdMembersRouteImport.update({
  id: '/$id/members',
  path: '/$id/members',
  getParentRoute: () => ApiTeamsRoute,
} as any)
const ApiTasksIdWatchersRoute = ApiTasksIdWatchersRouteImport.update({
  id: '/watchers',
  path: '/watchers',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdReviewRoute = ApiTasksIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdDependenciesRoute = ApiTasksIdDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdCommentsRoute = ApiTasksIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiChannelsIdMessagesRoute = ApiChannelsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdMembersRoute = ApiChannelsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdEventsRoute = ApiChannelsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiChannelsIdAgentsRoute = ApiChannelsIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiBoardsIdTasksRoute = ApiBoardsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdMembersRoute = ApiBoardsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdEventsRoute = ApiBoardsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiBoardsIdAgentsRoute = ApiBoardsIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ApiBoardsIdRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAgentsIdHeartbeatRoute = ApiAgentsIdHeartbeatRouteImport.update({
  id: '/$id/heartbeat',
  path: '/$id/heartbeat',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const AppBoardsBoardIdTaskIdRoute = AppBoardsBoardIdTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppBoardsBoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/channels': typeof AppChannelsRoute
  '/cost': typeof AppCostRoute
  '/fleet': typeof AppFleetRoute
  '/inbox': typeof AppInboxRoute
  '/inference': typeof AppInferenceRoute
  '/mcp': typeof AppMcpRoute
  '/memory': typeof AppMemoryRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/boards/': typeof AppBoardsIndexRoute
  '/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/channels': typeof AppChannelsRoute
  '/cost': typeof AppCostRoute
  '/fleet': typeof AppFleetRoute
  '/inbox': typeof AppInboxRoute
  '/inference': typeof AppInferenceRoute
  '/mcp': typeof AppMcpRoute
  '/memory': typeof AppMemoryRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/': typeof AppIndexRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/boards': typeof AppBoardsIndexRoute
  '/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/cost': typeof AppCostRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/inference': typeof AppInferenceRoute
  '/_app/mcp': typeof AppMcpRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/channels': typeof ApiChannelsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/cost': typeof ApiCostRoute
  '/api/fleet': typeof ApiFleetRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/teams': typeof ApiTeamsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/boards/$boardId': typeof AppBoardsBoardIdRouteWithChildren
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/boards/$id': typeof ApiBoardsIdRouteWithChildren
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/_app/boards/': typeof AppBoardsIndexRoute
  '/_app/boards/$boardId/$taskId': typeof AppBoardsBoardIdTaskIdRoute
  '/api/agents/$id/heartbeat': typeof ApiAgentsIdHeartbeatRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/boards/$id/agents': typeof ApiBoardsIdAgentsRoute
  '/api/boards/$id/events': typeof ApiBoardsIdEventsRoute
  '/api/boards/$id/members': typeof ApiBoardsIdMembersRoute
  '/api/boards/$id/tasks': typeof ApiBoardsIdTasksRoute
  '/api/channels/$id/agents': typeof ApiChannelsIdAgentsRoute
  '/api/channels/$id/events': typeof ApiChannelsIdEventsRoute
  '/api/channels/$id/members': typeof ApiChannelsIdMembersRoute
  '/api/channels/$id/messages': typeof ApiChannelsIdMessagesRoute
  '/api/tasks/$id/comments': typeof ApiTasksIdCommentsRoute
  '/api/tasks/$id/dependencies': typeof ApiTasksIdDependenciesRoute
  '/api/tasks/$id/review': typeof ApiTasksIdReviewRoute
  '/api/tasks/$id/watchers': typeof ApiTasksIdWatchersRoute
  '/api/teams/$id/members': typeof ApiTeamsIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/channels'
    | '/cost'
    | '/fleet'
    | '/inbox'
    | '/inference'
    | '/mcp'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/api/agents'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/notifications'
    | '/api/profile'
    | '/api/teams'
    | '/api/users'
    | '/boards/$boardId'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/tasks/$id'
    | '/boards/'
    | '/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/channels'
    | '/cost'
    | '/fleet'
    | '/inbox'
    | '/inference'
    | '/mcp'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/api/agents'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/notifications'
    | '/api/profile'
    | '/api/teams'
    | '/api/users'
    | '/'
    | '/boards/$boardId'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/tasks/$id'
    | '/boards'
    | '/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/agents'
    | '/_app/alerts'
    | '/_app/channels'
    | '/_app/cost'
    | '/_app/fleet'
    | '/_app/inbox'
    | '/_app/inference'
    | '/_app/mcp'
    | '/_app/memory'
    | '/_app/settings'
    | '/_app/skills'
    | '/api/agents'
    | '/api/boards'
    | '/api/channels'
    | '/api/chat'
    | '/api/conversations'
    | '/api/cost'
    | '/api/fleet'
    | '/api/notifications'
    | '/api/profile'
    | '/api/teams'
    | '/api/users'
    | '/_app/'
    | '/_app/boards/$boardId'
    | '/api/agents/register'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/auth/providers'
    | '/api/auth/session'
    | '/api/boards/$id'
    | '/api/channels/$id'
    | '/api/conversations/$id'
    | '/api/tasks/$id'
    | '/_app/boards/'
    | '/_app/boards/$boardId/$taskId'
    | '/api/agents/$id/heartbeat'
    | '/api/auth/google/callback'
    | '/api/boards/$id/agents'
    | '/api/boards/$id/events'
    | '/api/boards/$id/members'
    | '/api/boards/$id/tasks'
    | '/api/channels/$id/agents'
    | '/api/channels/$id/events'
    | '/api/channels/$id/members'
    | '/api/channels/$id/messages'
    | '/api/tasks/$id/comments'
    | '/api/tasks/$id/dependencies'
    | '/api/tasks/$id/review'
    | '/api/tasks/$id/watchers'
    | '/api/teams/$id/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiBoardsRoute: typeof ApiBoardsRouteWithChildren
  ApiChannelsRoute: typeof ApiChannelsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiCostRoute: typeof ApiCostRoute
  ApiFleetRoute: typeof ApiFleetRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiTeamsRoute: typeof ApiTeamsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiTasksIdRoute: typeof ApiTasksIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet': {
      id: '/api/fleet'
      path: '/api/fleet'
      fullPath: '/api/fleet'
      preLoaderRoute: typeof ApiFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inference': {
      id: '/_app/inference'
      path: '/inference'
      fullPath: '/inference'
      preLoaderRoute: typeof AppInferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cost': {
      id: '/_app/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AppCostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/': {
      id: '/_app/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AppBoardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/channels/$id': {
      id: '/api/channels/$id'
      path: '/$id'
      fullPath: '/api/channels/$id'
      preLoaderRoute: typeof ApiChannelsIdRouteImport
      parentRoute: typeof ApiChannelsRoute
    }
    '/api/boards/$id': {
      id: '/api/boards/$id'
      path: '/$id'
      fullPath: '/api/boards/$id'
      preLoaderRoute: typeof ApiBoardsIdRouteImport
      parentRoute: typeof ApiBoardsRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/register': {
      id: '/api/agents/register'
      path: '/register'
      fullPath: '/api/agents/register'
      preLoaderRoute: typeof ApiAgentsRegisterRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/_app/boards/$boardId': {
      id: '/_app/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AppBoardsBoardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/teams/$id/members': {
      id: '/api/teams/$id/members'
      path: '/$id/members'
      fullPath: '/api/teams/$id/members'
      preLoaderRoute: typeof ApiTeamsIdMembersRouteImport
      parentRoute: typeof ApiTeamsRoute
    }
    '/api/tasks/$id/watchers': {
      id: '/api/tasks/$id/watchers'
      path: '/watchers'
      fullPath: '/api/tasks/$id/watchers'
      preLoaderRoute: typeof ApiTasksIdWatchersRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/review': {
      id: '/api/tasks/$id/review'
      path: '/review'
      fullPath: '/api/tasks/$id/review'
      preLoaderRoute: typeof ApiTasksIdReviewRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/dependencies': {
      id: '/api/tasks/$id/dependencies'
      path: '/dependencies'
      fullPath: '/api/tasks/$id/dependencies'
      preLoaderRoute: typeof ApiTasksIdDependenciesRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/comments': {
      id: '/api/tasks/$id/comments'
      path: '/comments'
      fullPath: '/api/tasks/$id/comments'
      preLoaderRoute: typeof ApiTasksIdCommentsRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/channels/$id/messages': {
      id: '/api/channels/$id/messages'
      path: '/messages'
      fullPath: '/api/channels/$id/messages'
      preLoaderRoute: typeof ApiChannelsIdMessagesRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/members': {
      id: '/api/channels/$id/members'
      path: '/members'
      fullPath: '/api/channels/$id/members'
      preLoaderRoute: typeof ApiChannelsIdMembersRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/events': {
      id: '/api/channels/$id/events'
      path: '/events'
      fullPath: '/api/channels/$id/events'
      preLoaderRoute: typeof ApiChannelsIdEventsRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/channels/$id/agents': {
      id: '/api/channels/$id/agents'
      path: '/agents'
      fullPath: '/api/channels/$id/agents'
      preLoaderRoute: typeof ApiChannelsIdAgentsRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/boards/$id/tasks': {
      id: '/api/boards/$id/tasks'
      path: '/tasks'
      fullPath: '/api/boards/$id/tasks'
      preLoaderRoute: typeof ApiBoardsIdTasksRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/members': {
      id: '/api/boards/$id/members'
      path: '/members'
      fullPath: '/api/boards/$id/members'
      preLoaderRoute: typeof ApiBoardsIdMembersRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/events': {
      id: '/api/boards/$id/events'
      path: '/events'
      fullPath: '/api/boards/$id/events'
      preLoaderRoute: typeof ApiBoardsIdEventsRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/boards/$id/agents': {
      id: '/api/boards/$id/agents'
      path: '/agents'
      fullPath: '/api/boards/$id/agents'
      preLoaderRoute: typeof ApiBoardsIdAgentsRouteImport
      parentRoute: typeof ApiBoardsIdRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/agents/$id/heartbeat': {
      id: '/api/agents/$id/heartbeat'
      path: '/$id/heartbeat'
      fullPath: '/api/agents/$id/heartbeat'
      preLoaderRoute: typeof ApiAgentsIdHeartbeatRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/_app/boards/$boardId/$taskId': {
      id: '/_app/boards/$boardId/$taskId'
      path: '/$taskId'
      fullPath: '/boards/$boardId/$taskId'
      preLoaderRoute: typeof AppBoardsBoardIdTaskIdRouteImport
      parentRoute: typeof AppBoardsBoardIdRoute
    }
  }
}

interface AppBoardsBoardIdRouteChildren {
  AppBoardsBoardIdTaskIdRoute: typeof AppBoardsBoardIdTaskIdRoute
}

const AppBoardsBoardIdRouteChildren: AppBoardsBoardIdRouteChildren = {
  AppBoardsBoardIdTaskIdRoute: AppBoardsBoardIdTaskIdRoute,
}

const AppBoardsBoardIdRouteWithChildren =
  AppBoardsBoardIdRoute._addFileChildren(AppBoardsBoardIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppCostRoute: typeof AppCostRoute
  AppFleetRoute: typeof AppFleetRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInferenceRoute: typeof AppInferenceRoute
  AppMcpRoute: typeof AppMcpRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBoardsBoardIdRoute: typeof AppBoardsBoardIdRouteWithChildren
  AppBoardsIndexRoute: typeof AppBoardsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppCostRoute: AppCostRoute,
  AppFleetRoute: AppFleetRoute,
  AppInboxRoute: AppInboxRoute,
  AppInferenceRoute: AppInferenceRoute,
  AppMcpRoute: AppMcpRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBoardsBoardIdRoute: AppBoardsBoardIdRouteWithChildren,
  AppBoardsIndexRoute: AppBoardsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAgentsRouteChildren {
  ApiAgentsRegisterRoute: typeof ApiAgentsRegisterRoute
  ApiAgentsIdHeartbeatRoute: typeof ApiAgentsIdHeartbeatRoute
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsRegisterRoute: ApiAgentsRegisterRoute,
  ApiAgentsIdHeartbeatRoute: ApiAgentsIdHeartbeatRoute,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiBoardsIdRouteChildren {
  ApiBoardsIdAgentsRoute: typeof ApiBoardsIdAgentsRoute
  ApiBoardsIdEventsRoute: typeof ApiBoardsIdEventsRoute
  ApiBoardsIdMembersRoute: typeof ApiBoardsIdMembersRoute
  ApiBoardsIdTasksRoute: typeof ApiBoardsIdTasksRoute
}

const ApiBoardsIdRouteChildren: ApiBoardsIdRouteChildren = {
  ApiBoardsIdAgentsRoute: ApiBoardsIdAgentsRoute,
  ApiBoardsIdEventsRoute: ApiBoardsIdEventsRoute,
  ApiBoardsIdMembersRoute: ApiBoardsIdMembersRoute,
  ApiBoardsIdTasksRoute: ApiBoardsIdTasksRoute,
}

const ApiBoardsIdRouteWithChildren = ApiBoardsIdRoute._addFileChildren(
  ApiBoardsIdRouteChildren,
)

interface ApiBoardsRouteChildren {
  ApiBoardsIdRoute: typeof ApiBoardsIdRouteWithChildren
}

const ApiBoardsRouteChildren: ApiBoardsRouteChildren = {
  ApiBoardsIdRoute: ApiBoardsIdRouteWithChildren,
}

const ApiBoardsRouteWithChildren = ApiBoardsRoute._addFileChildren(
  ApiBoardsRouteChildren,
)

interface ApiChannelsIdRouteChildren {
  ApiChannelsIdAgentsRoute: typeof ApiChannelsIdAgentsRoute
  ApiChannelsIdEventsRoute: typeof ApiChannelsIdEventsRoute
  ApiChannelsIdMembersRoute: typeof ApiChannelsIdMembersRoute
  ApiChannelsIdMessagesRoute: typeof ApiChannelsIdMessagesRoute
}

const ApiChannelsIdRouteChildren: ApiChannelsIdRouteChildren = {
  ApiChannelsIdAgentsRoute: ApiChannelsIdAgentsRoute,
  ApiChannelsIdEventsRoute: ApiChannelsIdEventsRoute,
  ApiChannelsIdMembersRoute: ApiChannelsIdMembersRoute,
  ApiChannelsIdMessagesRoute: ApiChannelsIdMessagesRoute,
}

const ApiChannelsIdRouteWithChildren = ApiChannelsIdRoute._addFileChildren(
  ApiChannelsIdRouteChildren,
)

interface ApiChannelsRouteChildren {
  ApiChannelsIdRoute: typeof ApiChannelsIdRouteWithChildren
}

const ApiChannelsRouteChildren: ApiChannelsRouteChildren = {
  ApiChannelsIdRoute: ApiChannelsIdRouteWithChildren,
}

const ApiChannelsRouteWithChildren = ApiChannelsRoute._addFileChildren(
  ApiChannelsRouteChildren,
)

interface ApiConversationsRouteChildren {
  ApiConversationsIdRoute: typeof ApiConversationsIdRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdRoute: ApiConversationsIdRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiTeamsRouteChildren {
  ApiTeamsIdMembersRoute: typeof ApiTeamsIdMembersRoute
}

const ApiTeamsRouteChildren: ApiTeamsRouteChildren = {
  ApiTeamsIdMembersRoute: ApiTeamsIdMembersRoute,
}

const ApiTeamsRouteWithChildren = ApiTeamsRoute._addFileChildren(
  ApiTeamsRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

interface ApiTasksIdRouteChildren {
  ApiTasksIdCommentsRoute: typeof ApiTasksIdCommentsRoute
  ApiTasksIdDependenciesRoute: typeof ApiTasksIdDependenciesRoute
  ApiTasksIdReviewRoute: typeof ApiTasksIdReviewRoute
  ApiTasksIdWatchersRoute: typeof ApiTasksIdWatchersRoute
}

const ApiTasksIdRouteChildren: ApiTasksIdRouteChildren = {
  ApiTasksIdCommentsRoute: ApiTasksIdCommentsRoute,
  ApiTasksIdDependenciesRoute: ApiTasksIdDependenciesRoute,
  ApiTasksIdReviewRoute: ApiTasksIdReviewRoute,
  ApiTasksIdWatchersRoute: ApiTasksIdWatchersRoute,
}

const ApiTasksIdRouteWithChildren = ApiTasksIdRoute._addFileChildren(
  ApiTasksIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiBoardsRoute: ApiBoardsRouteWithChildren,
  ApiChannelsRoute: ApiChannelsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiCostRoute: ApiCostRoute,
  ApiFleetRoute: ApiFleetRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiTeamsRoute: ApiTeamsRouteWithChildren,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiTasksIdRoute: ApiTasksIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
