[package]
name = "talaria-fleet-resources"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
talaria-fleet-budget = { workspace = true }
talaria-fleet-docker = { workspace = true }
talaria-scheduler = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
