[package]
name = "talaria-mcp-jsonrpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
