// `talaria deploy` actions — the production compose wrappers. Plain
// `docker compose -f docker/compose.yml …` is the CANONICAL operator path
// (docs/CONTAINER.md); each leaf here runs exactly that argv — same relative
// -f, cwd the repo root, interpolation from docker/.env which compose loads
// automatically (the project directory is the compose file's own) — and
// prints the command before running it, so nothing the CLI does is hidden
// and every step stays copy-pasteable. A checkout is required either way
// (the image builds from the repo); bun is the only extra prerequisite.

import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import type { Ctx } from '../../ctx'
import type { Leaf } from '../../cli'
import { envWins, parseEnv, writeSecret } from '../../envfile'

const FILE = 'docker/compose.yml'
const DOCKER_SOCK = '/var/run/docker.sock'

/** The documented invocation. Relative -f on purpose: it is what
 *  CONTAINER.md tells operators to type, and keeping the real argv and the
 *  printed equivalent literally the same string is what makes the print
 *  honest — which is also why this doesn't go through compose()'s helper
 *  (absolute paths, cwd-inherited): parity beats reuse here. */
function deployCompose(ctx: Ctx, op: string[]): Promise<number> {
  return ctx.run('docker', ['compose', '-f', FILE, ...op], { cwd: ctx.root })
}

/** The copy-pasteable line for what is about to run. */
const plain = (envPrefix: string[], op: string[]): string =>
  [...envPrefix, 'docker', 'compose', '-f', FILE, ...op].join(' ')

/** docker/.env as compose will interpolate it, when present. */
export function dockerEnvFile(ctx: Ctx): Record<string, string> {
  const p = join(ctx.root, 'docker/.env')
  return existsSync(p) ? parseEnv(readFileSync(p, 'utf8')) : {}
}

/** GID of the docker socket — the `stat -c %g` half of the documented
 *  command. Null when the socket isn't there; never fatal on its own (the
 *  compose default of 999 applies, and a wrong guess fails loudly at the
 *  mount, not silently here). Injectable path for tests. */
export function socketGid(sock: string = DOCKER_SOCK): string | null {
  try {
    return String(statSync(sock).gid)
  } catch {
    return null
  }
}

/** Resolve DOCKER_GID unless the operator already supplied one — the shell
 *  and docker/.env are the override points, the CLI only fills the gap.
 *  Returns the env prefix the CLI itself added, so the printed equivalent
 *  shows exactly what a shell would have needed. */
function ensureDockerGid(ctx: Ctx, sock: string): string[] {
  if (ctx.env.DOCKER_GID || dockerEnvFile(ctx).DOCKER_GID) return []
  const gid = socketGid(sock)
  if (gid === null) {
    ctx.log.warn(`couldn't stat ${DOCKER_SOCK} — leaving DOCKER_GID to compose's default (999)`)
    return []
  }
  ctx.env.DOCKER_GID = gid
  return [`DOCKER_GID=${gid}`]
}

/** The SHARED secrets — the ones compose interpolates into BOTH the app and a
 *  sidecar (postgres password; the minio root pair), which is why no
 *  container's entrypoint can generate them: postgres and minio receive their
 *  values from compose interpolation at container-create time, before any
 *  entrypoint runs. docker/.env is the one file every compose invocation
 *  reads, and `deploy up` is the one moment something can run first. Generated
 *  ONCE — the up that first finds them missing — and persisted; values in the
 *  shell or already in the file always win (#267: without this, a compose
 *  instance that nobody configured runs on passwords published in the repo). */
const SHARED_SECRET_BYTES = 24 // hex → 48 chars, the openssl rand -hex 24 of the docs

const DOCKER_ENV_HEADER = `# Generated by \`talaria deploy up\` — first boot only. Compose interpolates
# this file into postgres, minio AND the app; back it up with the database.
# Real environment always wins over this file.
`

/** Does this instance already have its postgres data? POSTGRES_PASSWORD is
 *  pinned by initdb: a value that disagrees with the initialized cluster
 *  breaks auth, so an existing volume must keep the password it was born
 *  with (see ensureSharedSecrets). Injectable project for tests. */
async function pgDataExists(ctx: Ctx, volume: string): Promise<boolean> {
  return (await ctx.run('docker', ['volume', 'inspect', volume])) === 0
}

/** Fill docker/.env's shared-secret gaps before `up`. Returns nothing; the
 *  file (or its absence) is the state, and the log lines are the story. */
export async function ensureSharedSecrets(ctx: Ctx, pgVolume = 'talaria_pg-data'): Promise<void> {
  const path = join(ctx.root, 'docker/.env')
  const current = existsSync(path) ? readFileSync(path, 'utf8') : ''
  const fileVars = parseEnv(current)
  const missing = (name: string) => !(name in fileVars) && ctx.env[name] === undefined

  const lines: string[] = []
  const generated: string[] = []

  if (missing('POSTGRES_PASSWORD')) {
    if (await pgDataExists(ctx, pgVolume)) {
      // The cluster was initialized (before this safeguard existed) with the
      // published default. Write THAT, not a random — a random the data has
      // never heard of locks the app out — and say how to rotate for real.
      lines.push('# Your postgres data was initialized with the published default password;', '# rotate inside the DB, then edit this line to match:')
      lines.push(`POSTGRES_PASSWORD=talaria`)
      ctx.log.warn(
        'existing postgres data carries the published default password — pinned it in docker/.env; rotate with ALTER USER, then update the file',
      )
    } else {
      lines.push(`POSTGRES_PASSWORD=${randomBytes(SHARED_SECRET_BYTES).toString('hex')}`)
      generated.push('POSTGRES_PASSWORD')
    }
  }
  // MinIO's root pair comes from the environment at every boot (the data dir
  // stores IAM sub-users, not root), so a fresh pair rotates freely — both
  // consumers get the same interpolated value in the same `up`.
  for (const name of ['TALARIA_S3_ACCESS_KEY', 'TALARIA_S3_SECRET_KEY']) {
    if (missing(name)) {
      lines.push(`${name}=${randomBytes(SHARED_SECRET_BYTES).toString('hex')}`)
      generated.push(name)
    }
  }

  if (lines.length === 0) return
  const block = lines.join('\n')
  const body = current === '' ? `${DOCKER_ENV_HEADER}\n${block}\n` : `${current}${current.endsWith('\n') ? '' : '\n'}${block}\n`
  writeSecret(path, body)
  if (generated.length > 0) {
    ctx.log.say(`generated into docker/.env (once, 0600): ${generated.join(', ')}`)
    ctx.log.say('without this file a plain docker compose up runs the published dev defaults — prefer talaria deploy up')
  }
}

export async function runUp(ctx: Ctx, sock: string = DOCKER_SOCK): Promise<number> {
  const prefix = ensureDockerGid(ctx, sock)
  await ensureSharedSecrets(ctx)
  const op = ['up', '-d', '--build']
  ctx.log.say(plain(prefix, op))
  return deployCompose(ctx, op)
}

export function runDown(ctx: Ctx, volumes: boolean): Promise<number> {
  const op = volumes ? ['down', '--volumes'] : ['down']
  ctx.log.say(plain([], op))
  return deployCompose(ctx, op)
}

/** The api package the image build bakes in — the Dockerfile's ARG line is
 *  the build's actual input (compose passes no build args), so reading the
 *  ref from there means the CLI can never pull something other than what
 *  `up -d --build` resolves. Null when the Dockerfile declares no such ARG
 *  (or is gone): skip, don't guess. */
export function apiImageRef(root: string): string | null {
  try {
    const m = readFileSync(join(root, 'Dockerfile'), 'utf8').match(/^ARG TALARIA_API_IMAGE=(\S+)/m)
    return m?.[1] ?? null
  } catch {
    return null
  }
}

/** The image never compiles the api — the Dockerfile bakes in the pre-built
 *  package named by TALARIA_API_IMAGE, and a build resolves that FROM from
 *  the LOCAL daemon cache. Without a pull first, a redeploy wraps today's UI
 *  around yesterday's api binary and the update silently changes nothing
 *  the api does (bbills, 2026-09-03: three "already fixed" symptoms, one
 *  stale package). A failed pull dies rather than bake the stale digest on
 *  purpose — `deploy up` keeps its old reach-the-cache leniency, because
 *  that path is also the reboot-a-broken-box path. */
async function pullApiPackage(ctx: Ctx): Promise<void> {
  const ref = apiImageRef(ctx.root)
  if (ref === null) {
    ctx.log.skip('no TALARIA_API_IMAGE ARG in the Dockerfile — skipping the api package pull')
    return
  }
  ctx.log.say(`docker pull ${ref}`)
  if ((await ctx.run('docker', ['pull', ref])) !== 0) {
    ctx.log.die(
      `docker pull ${ref} failed — building now would bake the stale package the daemon already has. ` +
        'Fix reachability (or auth), then finish with `bun talaria deploy up`',
    )
  }
}

/** CONTAINER.md's update flow is "a redeploy" — for a checkout-driven host
 *  that means get the new code, pull the api package the rebuild will bake
 *  in, then the same `up -d --build` as boot. The git pull is --ff-only: an
 *  update must never synthesize a merge commit on a deploy host. */
export async function runUpdate(ctx: Ctx, sock: string = DOCKER_SOCK): Promise<number> {
  ctx.log.say('git pull --ff-only')
  if ((await ctx.run('git', ['pull', '--ff-only'], { cwd: ctx.root })) !== 0) {
    ctx.log.die(
      'git pull failed — reconcile the checkout (or fetch/checkout your way), then finish with `bun talaria deploy up`',
    )
  }
  await pullApiPackage(ctx)
  return runUp(ctx, sock)
}

export function runLogs(ctx: Ctx): Promise<number> {
  const op = ['logs', '-f']
  ctx.log.say(plain([], op))
  ctx.log.skip('following every service — Ctrl-C to detach')
  return deployCompose(ctx, op)
}

/** First-run access, the documented way: there are no generated credentials
 *  anymore — a fresh instance is CLAIMED. Point the operator at the claim
 *  screen (same port resolution as runStatus, so the URL is the one compose
 *  actually listens on). */
export async function runCreds(ctx: Ctx): Promise<number> {
  const effective = envWins(dockerEnvFile(ctx), ctx.env)
  const port = effective.TALARIA_HTTP_PORT ?? '5273'
  ctx.log.say(`first-run access: open http://localhost:${port} and claim the admin account`)
  ctx.log.say('the account you create there is the admin — there are no default credentials')
  return 0
}

/** The effective instance identity — env + docker/.env merged the way
 *  compose interpolates — then `ps`. The multi-instance traps in
 *  CONTAINER.md are all "which values did this up actually use", so status
 *  answers that in one line before the container table. */
export async function runStatus(ctx: Ctx): Promise<number> {
  const effective = envWins(dockerEnvFile(ctx), ctx.env)
  const port = effective.TALARIA_HTTP_PORT ?? '5273'
  const state = effective.TALARIA_STATE_DIR ?? '/var/lib/talaria'
  const fleet = `${effective.TALARIA_FLEET_PROJECT ?? 'talaria-fleet'}/${effective.TALARIA_FLEET_NETWORK ?? 'talaria'}`
  ctx.log.say(`http://localhost:${port} · state ${state} · fleet ${fleet}`)
  ctx.log.say(plain([], ['ps']))
  return deployCompose(ctx, ['ps'])
}

export const upCommand: Leaf = {
  kind: 'leaf',
  name: 'up',
  summary: "build + start the stack — CONTAINER.md's one command, DOCKER_GID + first-boot secrets resolved",
  usage: 'talaria deploy up',
  run: (ctx) => runUp(ctx),
}

export const downCommand: Leaf = {
  kind: 'leaf',
  name: 'down',
  summary: 'stop the stack (--volumes also deletes its data — destructive)',
  usage: 'talaria deploy down [--volumes]',
  flags: [
    {
      name: 'volumes',
      kind: 'bool',
      desc: 'also remove named volumes: pg-data, qdrant-data, minio-data — the DATABASE goes with them',
    },
  ],
  run: (ctx, args) => runDown(ctx, args.flags.volumes === true),
}

export const updateCommand: Leaf = {
  kind: 'leaf',
  name: 'update',
  summary: 'git pull --ff-only, pull the api package, then the redeploy (up -d --build)',
  usage: 'talaria deploy update',
  run: (ctx) => runUpdate(ctx),
}

export const logsCommand: Leaf = {
  kind: 'leaf',
  name: 'logs',
  summary: "follow the stack's logs (Ctrl-C to detach)",
  usage: 'talaria deploy logs',
  run: (ctx) => runLogs(ctx),
}

export const credsCommand: Leaf = {
  kind: 'leaf',
  name: 'creds',
  summary: 'where first-run access lives: the claim screen, not a generated password',
  usage: 'talaria deploy creds',
  run: (ctx) => runCreds(ctx),
}

export const statusCommand: Leaf = {
  kind: 'leaf',
  name: 'status',
  summary: 'effective port/state/fleet + compose ps',
  usage: 'talaria deploy status',
  run: (ctx) => runStatus(ctx),
}
