// talaria-api library — everything the binary mounts, importable so
// integration tests (tests/) can drive the router and the secretbox against
// committed cross-language fixtures without going through a socket.

pub mod activity;
pub use talaria_agent_auth as agent_auth;
pub mod agent_crons;
pub mod agent_defs;
pub mod agent_mcp;
pub mod agent_media;
pub mod agent_memory;
pub use talaria_agent_role_templates as agent_role_templates;
pub use talaria_agent_secrets as agent_secrets;
pub mod agent_skills;
pub mod agent_writes;
pub use talaria_agents_registry as agents_registry;
pub mod alerts;
pub mod approvals;
pub mod apps;
pub mod artifacts;
pub mod attribution;
pub use talaria_audit as audit;
pub use talaria_auth as auth;
pub use talaria_auth_config as auth_config;
pub mod boards;
pub use talaria_body as body;
pub mod brain_health;
pub use talaria_capability as capability;
pub mod capability_platform;
pub mod capability_reach;
pub mod channel_plan;
pub mod channel_replies;
pub mod channels;
pub mod chat_persist;
pub mod claim;
pub mod comms_decay;
pub use talaria_config as config;
pub mod conversations;
pub mod daily_brief;
pub use talaria_db as db;
pub mod digest;
pub mod effort_prefs;
pub mod email;
pub use talaria_error as error;
pub mod fitness;
pub mod fleet;
pub mod gaps;
pub mod gateway;
pub mod github;
pub mod google;
pub use talaria_guard_coaching as guard_coaching;
pub mod harness;
pub mod harness_model;
pub mod home;
pub mod inbox_focus;
pub use talaria_instance as instance;
pub use talaria_internal_history as internal_history;
pub mod invites;
pub mod jobs;
pub use talaria_judge as judge;
pub mod kb;
pub mod labels;
pub mod llm_keys;
pub mod mcp;
pub mod me;
pub mod mentions;
pub mod model;
pub use talaria_native_search as native_search;
pub mod notify;
pub mod org;
pub use talaria_org_domains as org_domains;
pub mod outreach;
pub use talaria_params as params;
pub use talaria_password as password;
pub use talaria_password_accounts as password_accounts;
pub use talaria_permissions as permissions;
pub mod persona;
pub mod personal_agent;
pub mod plan_doc;
pub mod plan_drafts;
pub mod platform_agents;
pub mod price_oracle;
pub use talaria_push as push;
pub use talaria_ratelimit as ratelimit;
pub mod realtime;
pub mod refs;
pub use talaria_repo_env as repo_env;
pub mod research;
pub use talaria_research_origin as research_origin;
pub mod retrieval;
pub mod routes;
pub mod runs;
pub use talaria_safe_fetch as safe_fetch;
pub mod scheduler;
pub mod search;
pub mod secret_health;
pub use talaria_secret_rotation as secret_rotation;
pub use talaria_secretbox as secretbox;
pub mod session;
pub mod skill_access;
pub use talaria_source_registry as source_registry;
pub use talaria_state as state;
pub mod statuses;
pub mod storage;
pub use talaria_task_const as task_const;
pub mod tasks;
pub use talaria_teams as teams;
pub use talaria_templates as templates;
pub mod ticket_chat;
pub mod titler;
pub use talaria_tz as tz;
pub mod update;
pub mod uploads;
pub mod users;
pub mod vision;
pub mod web_search;
pub mod work_dispatch;
pub use talaria_work_wait as work_wait;
pub mod workbench;
pub mod workchains;
pub mod workflows;
pub use talaria_workspace_handles as workspace_handles;
pub use talaria_workspace_secrets as workspace_secrets;
pub use talaria_yaml as yaml_string;
