//! yaml_string — a byte-exact port of the npm `yaml` package's `stringify`
//! (pinned ^2.9.0 in ui/package.json) for the one wire format that needs it:
//! /api/history serves agent-config revisions as `stringifyYaml(config)`, and
//! the TS emitter's bytes are the contract (clients render the raw text).
//!
//! This is a source port, not an approximation: ui/node_modules/yaml/dist/
//! stringify/{stringifyString,stringifyPair,stringifyCollection,foldFlowLines}.js
//! and schema/core/*.js are mirrored function-for-function — the dispatch
//! order (forced-double → plain eligibility → block preference → document
//! markers → core-scalar quoting → fold), the three quoted-scalar builders,
//! the literal/folded block builders, and the fold scanner itself. The pinned
//! behaviors, in brief:
//!
//! - Plain scalars fold only at single spaces (a space whose neighbors are
//!   non-space/non-tab); when the token after a fold point overflows, the
//!   fold backs up to the last *eligible* space, which is how a double space
//!   survives ("trail-space-fold" probe).
//! - Double-quoted scalars hard-chunk unbreakable runs with a trailing `\`
//!   at exactly 80 columns, and strings with newlines whose JSON form is ≥ 40
//!   units emit real doubled newlines + continuation indent instead of `\n`
//!   escapes (the multiline double-quoted form).
//! - Block scalars: content at ctx.indent (column 0 at the document root,
//!   +2 when the value contains a document marker at a line start), blank
//!   lines bare, keep-chomp (`+`) carrying its extra newlines as blank lines.
//!   A value whose lines exceed 80 uses the folded (`>`) style unless the
//!   fold would overflow, in which case it falls back to literal (`|`).
//! - Strings that would parse as YAML core-schema scalars (bools `true/
//!   True/TRUE`, null/~/empty, decimal/0o/0x ints, the float and inf/nan
//!   spellings) are quoted; keys too, and keys never fold.
//! - Numbers print as ECMAScript `String(number)`.
//!
//! All width arithmetic is in UTF-16 code units (JS `.length`), so the fold
//! scanner runs over `Vec<u16>`.
//!
//! Fixtures: api/tests/fixtures/yaml-stringify.json (generated by
//! scripts/gen-yaml-vectors.mjs against the real package) pins this module
//! byte-for-byte.

use serde_json::Value;

const LINE_WIDTH: isize = 80;
const MIN_CONTENT_WIDTH: isize = 20;
/// `doubleQuotedMinMultiLineLength` — below this JSON length, `\n` stays
/// escaped rather than becoming the real-newline multiline form.
const MIN_MULTILINE: usize = 40;
/// A plain key longer than this (plus its colon) goes to the explicit
/// `? key` / `: value` form (`stringifyPair.js:35`).
const MAX_IMPLICIT_KEY: usize = 1024;

// ── entry ─────────────────────────────────────────────────────────────────────

/// `YAML.stringify(v)` for JSON-shaped values, byte-identical to the package.
pub fn stringify(v: &Value) -> String {
    let mut out = String::new();
    match v {
        Value::Object(m) => out.push_str(&map_text(m, 0)),
        Value::Array(a) => out.push_str(&seq_text(a, 0)),
        v => out.push_str(&scalar_text(v, 0, false, None)),
    }
    out.push('\n');
    out
}

/// The text of a collection: first line at column `join` (the parent splices
/// its prefix), items joined `"\n" + join spaces` (`stringifyCollection`).
fn map_text(m: &serde_json::Map<String, Value>, join: usize) -> String {
    let ind = " ".repeat(join);
    let mut out = String::new();
    for (k, v) in m {
        let key = scalar_text(&Value::String(k.clone()), join + 2, true, None);
        // `str.length > 1024` where str = "key:" — the colon counts.
        let explicit = utf16(&key) + 1 > MAX_IMPLICIT_KEY;
        let mut line = if explicit {
            format!("? {key}\n{ind}:")
        } else {
            format!("{key}:")
        };
        if let Value::Object(_) | Value::Array(_) = v {
            let t = coll_text(v, join + 2);
            // `ws = '\n' + ctx.indent` for collections — but only for
            // implicit keys (`stringifyPair.js:79` gates on !explicitKey);
            // empty collections stay inline (`k: {}`).
            if !explicit && !(t.len() == 2 && (t == "{}" || t == "[]")) {
                line.push('\n');
                line.push_str(&ind);
                line.push_str("  ");
            } else {
                line.push(' ');
            }
            line.push_str(&t);
        } else {
            // `ctx.indentAtStart = str.length + 1` — only for implicit keys
            // with scalar values (`stringifyPair.js:82`).
            let ias = if explicit {
                None
            } else {
                Some(utf16(&key) + 2)
            };
            let t = scalar_text(v, join + 2, false, ias);
            // A fold at 0 makes the value start with '\n'; the key's space
            // is then dropped (`stringifyPair.js:135`).
            if !t.starts_with('\n') {
                line.push(' ');
            }
            line.push_str(&t);
        }
        if !out.is_empty() {
            out.push('\n');
            out.push_str(&ind);
        }
        out.push_str(&line);
    }
    if m.is_empty() { "{}".into() } else { out }
}

fn seq_text(a: &[Value], join: usize) -> String {
    let ind = " ".repeat(join);
    let mut out = String::new();
    // `itemIndent: ctx.indent + '  '` — item values stringify at join+2.
    for item in a {
        let t = match item {
            Value::Object(m) if m.is_empty() => "{}".into(),
            Value::Array(v) if v.is_empty() => "[]".into(),
            v => coll_or_scalar_text(v, join + 2),
        };
        if !out.is_empty() {
            out.push('\n');
            out.push_str(&ind);
        }
        out.push_str("- ");
        out.push_str(&t);
    }
    if a.is_empty() { "[]".into() } else { out }
}

/// A value's text at ctx.indent `at` — collections get their own join indent
/// there; scalars get it as their fold continuation.
fn coll_or_scalar_text(v: &Value, at: usize) -> String {
    match v {
        Value::Object(m) => map_text(m, at),
        Value::Array(a) => seq_text(a, at),
        v => scalar_text(v, at, false, None),
    }
}

fn coll_text(v: &Value, at: usize) -> String {
    match v {
        Value::Object(m) => map_text(m, at),
        Value::Array(a) => seq_text(a, at),
        _ => unreachable!("coll_text on scalar"),
    }
}

// ── scalars ───────────────────────────────────────────────────────────────────

fn scalar_text(v: &Value, ctx_indent: usize, implicit_key: bool, ias: Option<usize>) -> String {
    match v {
        Value::Null => "null".into(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => js_number(n),
        Value::String(s) => string_scalar(s, ctx_indent, implicit_key, ias),
        _ => unreachable!("scalar_text on collection"),
    }
}

/// `stringifyString`'s dispatch. `ctx_indent` is the scalar's continuation
/// indent (the collection writer's itemIndent; 0 at the document root).
fn string_scalar(s: &str, ctx_indent: usize, implicit_key: bool, ias: Option<usize>) -> String {
    #[derive(PartialEq)]
    enum Kind {
        Plain,
        Quoted,
        Block,
    }
    let has_nl = s.contains('\n');
    let mut kind = Kind::Plain;
    // Controls and unpaired surrogates force double quotes up front
    // (`stringifyString.js:307`); lone surrogates can't occur in serde_json.
    if s.chars().any(|c| {
        let u = c as u32;
        u <= 0x08 || (0x0b..=0x1f).contains(&u) || (0x7f..=0x9f).contains(&u)
    }) {
        kind = Kind::Quoted;
    } else if implicit_key && has_nl {
        kind = Kind::Quoted; // keys never hold newlines (`plainString:254`)
    } else if !plain_eligible(s) {
        kind = if implicit_key || !has_nl {
            Kind::Quoted
        } else {
            Kind::Block
        };
    } else if has_nl {
        // Plain JS strings never carry `type: PLAIN`, so multiline strings
        // prefer the block style wherever it's allowed (`plainString:269`).
        kind = Kind::Block;
    } else if has_line_marker(s) {
        if ctx_indent == 0 {
            kind = Kind::Block; // forceBlockIndent at the root
        } else if implicit_key && ctx_indent == 2 {
            kind = Kind::Quoted;
        }
    }
    if kind == Kind::Plain && core_scalar(s) {
        kind = Kind::Quoted;
    }
    match kind {
        Kind::Plain => {
            // `value.replace(/\n+/g, '$&\n' + indent)` — a hard break in a
            // plain scalar must double (unreachable from JSON data, which
            // routes multiline to blocks, but ported for parity).
            let ind = " ".repeat(ctx_indent);
            let mut str_s = String::new();
            let mut rest = s;
            while let Some(i) = rest.find('\n') {
                let mut j = i;
                let bytes = rest.as_bytes();
                while j < bytes.len() && bytes[j] == b'\n' {
                    j += 1;
                }
                str_s.push_str(&rest[..j]);
                str_s.push('\n');
                str_s.push_str(&ind);
                rest = &rest[j..];
            }
            str_s.push_str(rest);
            if implicit_key {
                str_s
            } else {
                u16s_to_string(&fold_flow(
                    &string_to_u16s(&str_s),
                    &ind,
                    Mode::Flow,
                    ias,
                    &mut false,
                ))
            }
        }
        Kind::Quoted => quoted_string(s, ctx_indent, implicit_key, ias),
        Kind::Block => {
            let force = ctx_indent == 0 && has_line_marker(s);
            block_string(s, ctx_indent, force)
                .unwrap_or_else(|| quoted_string(s, ctx_indent, implicit_key, ias))
        }
    }
}

/// The plain-scalar eligibility test (`plainString.js:258`).
fn plain_eligible(s: &str) -> bool {
    let mut it = s.chars();
    let Some(first) = it.next() else {
        return true; // "" is plain-eligible (then core-quoted as null)
    };
    if matches!(
        first,
        '\n' | '\t'
            | ' '
            | ','
            | '['
            | ']'
            | '{'
            | '}'
            | '#'
            | '&'
            | '*'
            | '!'
            | '|'
            | '>'
            | '\''
            | '"'
            | '%'
            | '@'
            | '`'
    ) {
        return false;
    }
    if s == "-" || s == "?" {
        return false;
    }
    if (first == '-' || first == '?') && matches!(it.next(), Some(' ') | Some('\t')) {
        return false;
    }
    let chars: Vec<char> = s.chars().collect();
    for w in chars.windows(2) {
        if matches!(w[0], '\n' | ':') && matches!(w[1], ' ' | '\t') {
            return false; // ": " or "\n " anywhere
        }
        if matches!(w[0], ' ' | '\t') && w[1] == '\n' {
            return false; // " \n"
        }
        if matches!(w[0], '\n' | '\t' | ' ') && w[1] == '#' {
            return false; // " #"
        }
    }
    !matches!(
        chars.last(),
        Some(' ') | Some('\t') | Some('\n') | Some(':')
    )
}

/// `/^(%|---|\.\.\.)/m` — a document marker at any line start
/// (`containsDocumentMarker`).
fn has_line_marker(s: &str) -> bool {
    s.split('\n')
        .any(|l| l.starts_with('%') || l.starts_with("---") || l.starts_with("..."))
}

/// Would the string parse as a YAML 1.2 core-schema scalar? The core tags'
/// test regexes (`schema/core/*.js`), which the string tag applies to values
/// and keys alike (`actualString`).
fn core_scalar(s: &str) -> bool {
    // null: "" | ~ | null | Null | NULL
    if matches!(s, "" | "~" | "null" | "Null" | "NULL") {
        return true;
    }
    // bool: [Tt]rue | TRUE | [Ff]alse | FALSE
    if matches!(s, "true" | "True" | "TRUE" | "false" | "False" | "FALSE") {
        return true;
    }
    let body = s.strip_prefix(['-', '+']).unwrap_or(s);
    let signed = body.len() < s.len();
    // 0o[0-7]+ / 0x[0-9a-fA-F]+ are sign-less
    if !signed {
        if let Some(o) = body.strip_prefix("0o")
            && !o.is_empty()
            && o.bytes().all(|b| (b'0'..=b'7').contains(&b))
        {
            return true;
        }
        if let Some(h) = body.strip_prefix("0x")
            && !h.is_empty()
            && h.bytes().all(|b| b.is_ascii_hexdigit())
        {
            return true;
        }
    }
    // `[-+]?\.(?:inf|Inf|INF)|\.(?:nan|NaN|NAN)` — inf carries a sign, nan
    // doesn't.
    if let Some(t) = body.strip_prefix('.') {
        if matches!(t, "inf" | "Inf" | "INF") {
            return true;
        }
        if !signed && matches!(t, "nan" | "NaN" | "NAN") {
            return true;
        }
    }
    // [-+]?[0-9]+
    if !body.is_empty() && body.bytes().all(|b| b.is_ascii_digit()) {
        return true;
    }
    float_shape(body)
}

/// `[-+]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)[eE][-+]?[0-9]+` (exp) or
/// `[-+]?\.[0-9]+|[0-9]+\.[0-9]*` (plain) — the mantissa half, sign stripped.
fn float_shape(b: &str) -> bool {
    let (mant, exp) = match b.find(['e', 'E']) {
        Some(i) => (&b[..i], Some(&b[i + 1..])),
        None => (b, None),
    };
    let ok_mant = if let Some(d) = mant.strip_prefix('.') {
        !d.is_empty() && d.bytes().all(|x| x.is_ascii_digit())
    } else if let Some((int, frac)) = mant.split_once('.') {
        !int.is_empty()
            && int.bytes().all(|x| x.is_ascii_digit())
            && frac.bytes().all(|x| x.is_ascii_digit())
    } else {
        !mant.is_empty() && mant.bytes().all(|x| x.is_ascii_digit())
    };
    if !ok_mant {
        return false;
    }
    // A bare dot (".") is no mantissa at all.
    if mant == "." {
        return false;
    }
    match exp {
        None => mant.contains('.'), // plain float needs the dot on a side
        Some(e) => {
            let digits = e.strip_prefix(['-', '+']).unwrap_or(e);
            !digits.is_empty() && digits.bytes().all(|x| x.is_ascii_digit())
        }
    }
}

// ── quoted scalars ────────────────────────────────────────────────────────────

/// `quotedString` — single quotes win only when a `"` is present unaccompanied
/// by a `'` (the default `singleQuote: null` sends everything else to double).
fn quoted_string(s: &str, ctx_indent: usize, implicit_key: bool, ias: Option<usize>) -> String {
    let has_d = s.contains('"');
    let has_s = s.contains('\'');
    if has_d && !has_s {
        single_quoted(s, ctx_indent, implicit_key, ias)
    } else {
        double_quoted(s, ctx_indent, implicit_key, ias)
    }
}

fn single_quoted(s: &str, ctx_indent: usize, implicit_key: bool, ias: Option<usize>) -> String {
    // A space or tab around a newline can't survive single quoting
    // (`stringifyString.js:125`).
    let bad_nl = {
        let cs: Vec<char> = s.chars().collect();
        cs.windows(2).any(|w| {
            (matches!(w[0], ' ' | '\t') && w[1] == '\n')
                || (w[0] == '\n' && matches!(w[1], ' ' | '\t'))
        })
    };
    if implicit_key && s.contains('\n') || bad_nl {
        return double_quoted(s, ctx_indent, implicit_key, ias);
    }
    // The `\n+` → run + '\n' + indent transform (hard breaks double inside
    // single quotes). Unreachable from JSON data — newlines only reach the
    // single-quote path when no space or tab borders them, and the dispatch
    // above sends every other multiline string to blocks or double quotes —
    // but ported for parity.
    let ind = cont_indent(s, ctx_indent);
    let doubled = {
        let mut out = String::new();
        let mut rest = s.replace('\'', "''");
        while let Some(i) = rest.find('\n') {
            let mut j = i;
            let bytes = rest.as_bytes();
            while j < bytes.len() && bytes[j] == b'\n' {
                j += 1;
            }
            out.push_str(&rest[..j]);
            out.push('\n');
            out.push_str(&ind);
            rest = rest.split_off(j);
        }
        out.push_str(&rest);
        out
    };
    let text = format!("'{doubled}'");
    if implicit_key {
        return text;
    }
    u16s_to_string(&fold_flow(
        &string_to_u16s(&text),
        &ind,
        Mode::Flow,
        ias,
        &mut false,
    ))
}

/// `ctx.indent || (containsDocumentMarker ? '  ' : '')` — the fold
/// continuation for quoted scalars.
fn cont_indent(s: &str, ctx_indent: usize) -> String {
    if ctx_indent > 0 {
        " ".repeat(ctx_indent)
    } else if has_line_marker(s) {
        "  ".into()
    } else {
        String::new()
    }
}

/// `doubleQuotedString`: start from the JSON.stringify form (the package's
/// escape baseline), rewrite \uXXXX to the YAML escapes, and let long
/// newlines become the real-newline multiline form.
fn double_quoted(s: &str, ctx_indent: usize, implicit_key: bool, ias: Option<usize>) -> String {
    let json = json_quote(s);
    let cont = cont_indent(s, ctx_indent);
    let t: Vec<u16> = json.encode_utf16().collect();
    let n = t.len();
    let mut out: Vec<u16> = Vec::new();
    let mut start = 0usize;
    let mut i: isize = -1;
    while {
        i += 1;
        (i as usize) < n
    } {
        let mut ch = t[i as usize];
        let iu = i as usize;
        // A space before \n escapes so folding won't eat it
        // (`stringifyString.js:42`).
        if ch == b' ' as u16 && iu + 2 < n && t[iu + 1] == b'\\' as u16 && t[iu + 2] == b'n' as u16
        {
            out.extend_from_slice(&t[start..iu]);
            out.extend("\\ ".encode_utf16());
            i += 1; // now standing on the backslash
            start = i as usize;
            ch = b'\\' as u16;
        }
        if ch == b'\\' as u16 {
            let iu = i as usize;
            match t.get(iu + 1).copied() {
                Some(c) if c == b'u' as u16 => {
                    let code: String = String::from_utf16_lossy(&t[iu + 2..(iu + 6).min(n)]);
                    out.extend_from_slice(&t[start..iu]);
                    match code.as_str() {
                        "0000" => out.extend("\\0".encode_utf16()),
                        "0007" => out.extend("\\a".encode_utf16()),
                        "000b" => out.extend("\\v".encode_utf16()),
                        "001b" => out.extend("\\e".encode_utf16()),
                        "0085" => out.extend("\\N".encode_utf16()),
                        "00a0" => out.extend("\\_".encode_utf16()),
                        "2028" => out.extend("\\L".encode_utf16()),
                        "2029" => out.extend("\\P".encode_utf16()),
                        _ if code.starts_with("00") => {
                            out.extend("\\x".encode_utf16());
                            out.extend(t[iu + 4..(iu + 6).min(n)].iter().copied());
                        }
                        _ => out.extend_from_slice(&t[iu..(iu + 6).min(n)]),
                    }
                    i += 5;
                    start = (i + 1) as usize;
                }
                Some(c) if c == b'n' as u16 => {
                    let next_is_quote = t.get(iu + 2) == Some(&(b'"' as u16));
                    if implicit_key || next_is_quote || n < MIN_MULTILINE {
                        i += 1; // keep the \n escape
                    } else {
                        // The multiline form: folding eats the first newline,
                        // so emit two, plus one per consecutive \n escape.
                        out.extend_from_slice(&t[start..iu]);
                        out.extend("\n\n".encode_utf16());
                        while t.get((i + 2) as usize) == Some(&(b'\\' as u16))
                            && t.get((i + 3) as usize) == Some(&(b'n' as u16))
                            && t.get((i + 4) as usize) != Some(&(b'"' as u16))
                        {
                            out.push(b'\n' as u16);
                            i += 2;
                        }
                        out.extend(cont.encode_utf16());
                        if t.get((i + 2) as usize) == Some(&(b' ' as u16)) {
                            out.push(b'\\' as u16);
                        }
                        i += 1;
                        start = (i + 1) as usize;
                    }
                }
                _ => i += 1, // \t \r \" \\ and friends pass through
            }
        }
    }
    let mut text = if start != 0 {
        out.extend_from_slice(&t[start..]);
        out
    } else {
        t
    };
    if !implicit_key {
        text = fold_flow(&text, &cont, Mode::Quoted, ias, &mut false);
    }
    u16s_to_string(&text)
}

/// The `JSON.stringify` baseline for a string (quotes included): exactly what
/// ES JSON escaping produces — controls below 0x20 as \u00xx (lowercase),
/// \b \t \n \f \r named, quote and backslash, everything else (including
/// \x7f–\x9f and all non-ASCII) raw.
fn json_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{8}' => out.push_str("\\b"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\u{c}' => out.push_str("\\f"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── block scalars ─────────────────────────────────────────────────────────────

/// `blockString`. `None` = the value can't take a block (a whitespace-only
/// tail after the last newline) and must be quoted instead.
fn block_string(s: &str, ctx_indent: usize, force_indent: bool) -> Option<String> {
    // `/\n[\t ]+$/` — equivalent to: the segment after the last newline is
    // nonempty and all spaces/tabs.
    if let Some(after) = s.rsplit('\n').next()
        && !after.is_empty()
        && after.chars().all(|c| c == ' ' || c == '\t')
    {
        return None;
    }
    let indent_len = if ctx_indent > 0 {
        ctx_indent
    } else if force_indent || has_line_marker(s) {
        2
    } else {
        0
    };
    let ind = " ".repeat(indent_len);
    let literal = !line_over_limit(s, indent_len);

    // chomp and the whitespace tail (`stringifyString.js:180-204`)
    let end_start = s.trim_end_matches(['\n', '\t', ' ']).len();
    let tail = &s[end_start..];
    let chomp = if !tail.contains('\n') {
        "-"
    } else if end_start == 0 || tail.find('\n') != Some(tail.len() - 1) {
        "+"
    } else {
        ""
    };
    let mut end_s = tail.to_string();
    let mut body = s[..end_start].to_string();
    if !end_s.is_empty() {
        if end_s.ends_with('\n') {
            end_s.pop();
        }
        end_s = block_end_newlines(&end_s, &ind);
    }

    // leading whitespace run (`stringifyString.js:206-222`). `start` is the
    // run through its LAST newline when one is present; a space-only run is
    // NOT extracted (JS: `startNlPos(–1) < startEnd` → substring(0, 0)) —
    // the space stays in the value, where folded output treats the line as
    // more-indented.
    let mut start_with_space = false;
    let mut start_nl: Option<usize> = None;
    for (bi, c) in body.char_indices() {
        if c == ' ' {
            start_with_space = true;
        } else if c == '\n' {
            start_nl = Some(bi);
        } else {
            break;
        }
    }
    let cut = match start_nl {
        Some(nl) => nl + 1,
        None => 0,
    };
    let start_s = body[..cut].to_string();
    body = body[cut..].to_string();
    let start_t = if start_s.is_empty() {
        start_s
    } else {
        indent_runs(&start_s, &ind)
    };
    let value_t = indent_runs(&body, &ind);

    let digit = if start_with_space {
        if indent_len > 0 { "2" } else { "1" }
    } else {
        ""
    };
    if literal {
        return Some(format!("|{digit}{chomp}\n{ind}{start_t}{value_t}{end_s}"));
    }

    // Folded (`>`) style: double the newline runs, un-double around
    // more-indented lines (their breaks stay literal), indent the runs, then
    // fold — falling back to literal if the fold overflows.
    let mut folded = double_runs(&body);
    folded = un_double_more_indented(&folded);
    folded = indent_runs(&folded, &ind);
    let input = format!("{start_t}{folded}{end_s}");
    let mut overflow = false;
    let text = fold_flow(
        &string_to_u16s(&input),
        &ind,
        Mode::Block,
        Some(indent_len),
        &mut overflow,
    );
    if overflow {
        return Some(format!("|{digit}{chomp}\n{ind}{start_t}{value_t}{end_s}"));
    }
    Some(format!(">{digit}{chomp}\n{ind}{}", u16s_to_string(&text)))
}

/// `lineLengthOverLimit` — any line longer than the width minus indent.
fn line_over_limit(s: &str, indent_len: usize) -> bool {
    let limit = LINE_WIDTH - indent_len as isize;
    if utf16(s) as isize <= limit {
        return false;
    }
    let mut start = 0usize;
    for (i, _) in s.match_indices('\n') {
        if utf16(&s[start..i]) as isize > limit {
            return true;
        }
        start = i + 1;
        if utf16(&s[start..]) as isize <= limit {
            return false;
        }
    }
    true
}

/// `value.replace(/\n+/g, '$&' + indent)` — every newline run gains the
/// continuation indent after it (interior blank lines stay bare).
fn indent_runs(s: &str, ind: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(i) = rest.find('\n') {
        let mut j = i;
        let bytes = rest.as_bytes();
        while j < bytes.len() && bytes[j] == b'\n' {
            j += 1;
        }
        out.push_str(&rest[..j]);
        out.push_str(ind);
        rest = &rest[j..];
    }
    out.push_str(rest);
    out
}

/// `value.replace(/\n+/g, '\n$&')` — each run doubled (folded-style prep).
fn double_runs(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 2);
    let mut rest = s;
    while let Some(i) = rest.find('\n') {
        let mut j = i;
        let bytes = rest.as_bytes();
        while j < bytes.len() && bytes[j] == b'\n' {
            j += 1;
        }
        out.push_str(&rest[..i]);
        out.push('\n');
        out.push_str(&rest[i..j]);
        rest = &rest[j..];
    }
    out.push_str(rest);
    out
}

/// `end.replace(blockEndNewlines)` — newline runs not at the very end gain
/// the indent (`stringifyString.js:155-158`; the lookbehind is vacuous for
/// maximal runs).
fn block_end_newlines(s: &str, ind: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(i) = rest.find('\n') {
        let mut j = i;
        let bytes = rest.as_bytes();
        while j < bytes.len() && bytes[j] == b'\n' {
            j += 1;
        }
        out.push_str(&rest[..j]);
        if j < rest.len() {
            out.push_str(ind);
        }
        rest = &rest[j..];
    }
    out.push_str(rest);
    out
}

/// The middle folded-style transform:
/// `(?:^|\n)([\t ].*)(?:([\n\t ]*)\n(?![\n\t ]))?` → `$1$2`.
/// A more-indented (space/tab-led) nonempty line keeps its trailing newline
/// runs un-doubled — those breaks are literal, not fold candidates. The
/// anchor newline before such a line is consumed (dropped) by the match.
fn un_double_more_indented(s: &str) -> String {
    let cs: Vec<char> = s.chars().collect();
    let len = cs.len();
    let mut out = String::with_capacity(s.len());
    let mut pos = 0usize;
    while pos < len {
        let anchored = pos == 0 || cs[pos - 1] == '\n';
        if anchored && matches!(cs[pos], ' ' | '\t') {
            let mut q = pos;
            while q < len && cs[q] != '\n' {
                q += 1;
            }
            // optional `([\n\t ]*)\n(?![\n\t ])`, greedy with backtracking
            let mut cut = None; // (run_start, newline index consumed through)
            if q < len {
                let mut rmax = q;
                while rmax < len && matches!(cs[rmax], '\n' | '\t' | ' ') {
                    rmax += 1;
                }
                let mut rl = rmax - q;
                loop {
                    let after = q + rl;
                    if cs.get(after) == Some(&'\n')
                        && let Some(&nx) = cs.get(after + 1)
                        && !matches!(nx, '\n' | '\t' | ' ')
                    {
                        cut = Some((q, after));
                        break;
                    }
                    if rl == 0 {
                        break;
                    }
                    rl -= 1;
                }
            }
            match cut {
                Some((rs, rn)) => {
                    if pos > 0 {
                        out.pop(); // the anchor newline was consumed
                    }
                    out.extend(&cs[pos..q]);
                    out.extend(&cs[rs..rn]);
                    pos = rn + 1;
                }
                None => {
                    if pos > 0 {
                        out.pop();
                    }
                    out.extend(&cs[pos..q]);
                    pos = q;
                }
            }
        } else {
            out.push(cs[pos]);
            pos += 1;
        }
    }
    out
}

// ── the fold scanner ──────────────────────────────────────────────────────────

#[derive(PartialEq, Clone, Copy)]
enum Mode {
    /// plain and single-quoted
    Flow,
    /// double-quoted (hard-chunks with `\` at 80)
    Quoted,
    /// folded blocks (more-indented lines skip folding)
    Block,
}

/// A direct port of `foldFlowLines` over UTF-16 units. `overflow` reports the
/// FLOW/BLOCK overflow flag (BLOCK callers use it to fall back to literal).
fn fold_flow(
    text: &[u16],
    indent: &str,
    mode: Mode,
    ias: Option<usize>,
    overflow: &mut bool,
) -> Vec<u16> {
    let n = text.len();
    let ind: Vec<u16> = indent.encode_utf16().collect();
    let ind_len = ind.len() as isize;
    let end_step = (1 + MIN_CONTENT_WIDTH).max(1 + LINE_WIDTH - ind_len);
    if n as isize <= end_step {
        return text.to_vec();
    }
    let mut folds: Vec<usize> = Vec::new();
    let mut escaped_folds: Vec<isize> = Vec::new();
    let mut end = LINE_WIDTH - ind_len;
    if let Some(ias) = ias {
        if ias as isize > LINE_WIDTH - MIN_CONTENT_WIDTH.max(2) {
            folds.push(0);
        } else {
            end = LINE_WIDTH - ias as isize;
        }
    }
    let mut split: Option<usize> = None;
    let mut prev: Option<u16> = None;
    let mut i: isize = -1;
    let mut esc_start: isize = -1;
    let mut esc_end: isize = -1;
    if mode == Mode::Block {
        // A leading more-indented region at the very start is consumed
        // before scanning (foldFlowLines.js:34-38).
        i = consume_more_indented(text, i, ind_len as usize);
        if i != -1 {
            end = i + end_step;
        }
    }
    let mut ch: Option<u16>;
    loop {
        i += 1;
        ch = text.get(i as usize).copied();
        let Some(c) = ch else { break };
        if mode == Mode::Quoted && c == b'\\' as u16 {
            esc_start = i;
            i += match text.get(i as usize + 1).copied() {
                Some(x) if x == b'x' as u16 => 3,
                Some(x) if x == b'u' as u16 => 5,
                Some(x) if x == b'U' as u16 => 9,
                _ => 1,
            };
            esc_end = i;
        }
        if c == b'\n' as u16 {
            if mode == Mode::Block {
                i = consume_more_indented(text, i, ind_len as usize);
            }
            end = i + ind_len + end_step;
            split = None;
        } else {
            if c == b' ' as u16
                && prev.is_some_and(|p| p != b' ' as u16 && p != b'\n' as u16 && p != b'\t' as u16)
                && let Some(nx) = text.get(i as usize + 1)
                && *nx != b' ' as u16
                && *nx != b'\n' as u16
                && *nx != b'\t' as u16
            {
                split = Some(i as usize);
            }
            if i >= end {
                if let Some(sp) = split {
                    folds.push(sp);
                    end = sp as isize + end_step;
                    split = None;
                } else if mode == Mode::Quoted {
                    // whitespace collected at the end may stretch past the
                    // width; skip it before cutting
                    while prev == Some(b' ' as u16) || prev == Some(b'\t' as u16) {
                        prev = ch;
                        i += 1;
                        ch = text.get(i as usize).copied();
                        *overflow = true;
                    }
                    let j = if i > esc_end + 1 {
                        i - 2
                    } else {
                        esc_start - 1
                    };
                    // Bail out rather than fold the same spot twice.
                    if escaped_folds.contains(&j) {
                        return text.to_vec();
                    }
                    folds.push(j.max(0) as usize);
                    escaped_folds.push(j);
                    end = j + end_step;
                    split = None;
                } else {
                    *overflow = true;
                }
            }
        }
        prev = ch;
    }
    if folds.is_empty() {
        return text.to_vec();
    }
    let mut res: Vec<u16> = text[..folds[0]].to_vec();
    for k in 0..folds.len() {
        let fold = folds[k];
        let stop = folds.get(k + 1).copied().unwrap_or(n);
        if fold == 0 {
            // The value overflows before it starts (long key): it moves to
            // its own line, replacing what was gathered so far.
            res = ind.clone();
            res.extend_from_slice(&text[..stop]);
            res.insert(0, b'\n' as u16);
        } else {
            if mode == Mode::Quoted && escaped_folds.contains(&(fold as isize)) {
                res.push(text[fold]);
                res.push(b'\\' as u16);
            }
            res.push(b'\n' as u16);
            res.extend_from_slice(&ind);
            res.extend_from_slice(&text[fold + 1..stop]);
        }
    }
    res
}

/// `consumeMoreIndentedLines` — skips more-indented lines (leading space/tab
/// beyond the indent) so they never hit the fold checks; returns the index of
/// the last newline in the consumed span.
fn consume_more_indented(t: &[u16], mut i: isize, indent: usize) -> isize {
    let mut end = i;
    let mut start = i + 1;
    let mut ch = t.get(start as usize).copied();
    while ch == Some(b' ' as u16) || ch == Some(b'\t' as u16) {
        if i < start + indent as isize {
            i += 1;
            ch = t.get(i as usize).copied();
        } else {
            loop {
                i += 1;
                ch = t.get(i as usize).copied();
                if ch.is_none() || ch == Some(b'\n' as u16) {
                    break;
                }
            }
            end = i;
            start = i + 1;
            ch = t.get(start as usize).copied();
        }
    }
    end
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// ECMAScript `String(number)` — the shortest roundtrip digits, reformatted
/// from Rust's `{:e}` (JS prints plain decimal while the point sits in
/// 1..=21, exponent form with an explicit `+` otherwise; `-0` keeps its sign).
pub fn js_number(n: &serde_json::Number) -> String {
    let v = n.as_f64().unwrap_or(0.0);
    if v == 0.0 {
        return if v.is_sign_positive() {
            "0".into()
        } else {
            "-0".into()
        };
    }
    if v.is_nan() {
        return "NaN".into();
    }
    if v.is_infinite() {
        return if v > 0.0 { "Infinity" } else { "-Infinity" }.into();
    }
    let neg = v < 0.0;
    let e = format!("{:e}", v.abs());
    let (digits, exp) = e.split_once('e').unwrap();
    let exp: i32 = exp.parse().unwrap();
    let digits = digits.replace('.', "");
    let point = exp + 1; // digits before the decimal point
    let mut out = String::new();
    if neg {
        out.push('-');
    }
    let k = digits.len() as i32;
    // ECMAScript `Number::toString`: plain decimal only while the point sits
    // in (-6, 21]; outside that, exponent form with an explicit `+`.
    if k <= point && point <= 21 {
        out.push_str(&digits);
        for _ in 0..(point - k) {
            out.push('0');
        }
    } else if point > 0 && point <= 21 {
        out.push_str(&digits[..point as usize]);
        out.push('.');
        out.push_str(&digits[point as usize..]);
    } else if point <= 0 && point > -6 {
        out.push_str("0.");
        for _ in 0..(-point) {
            out.push('0');
        }
        out.push_str(&digits);
    } else {
        out.push_str(&digits[..1]);
        if k > 1 {
            out.push('.');
            out.push_str(&digits[1..]);
        }
        out.push('e');
        let e10 = point - 1;
        if e10 >= 0 {
            out.push('+');
        }
        out.push_str(&e10.to_string());
    }
    out
}

fn utf16(s: &str) -> usize {
    s.chars().map(char::len_utf16).sum()
}

fn string_to_u16s(s: &str) -> Vec<u16> {
    s.encode_utf16().collect()
}

fn u16s_to_string(v: &[u16]) -> String {
    String::from_utf16_lossy(v)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn numbers_print_as_ecmascript() {
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("25").unwrap()),
            "25"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("0.1").unwrap()),
            "0.1"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("3.5").unwrap()),
            "3.5"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("-0").unwrap()),
            "-0"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("1e21").unwrap()),
            "1e+21"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("1e-7").unwrap()),
            "1e-7"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("1.5e-10").unwrap()),
            "1.5e-10"
        );
        assert_eq!(
            js_number(&serde_json::from_str::<serde_json::Number>("1e5").unwrap()),
            "100000"
        );
        assert_eq!(
            js_number(
                &serde_json::from_str::<serde_json::Number>("123456789012345678901234567890")
                    .unwrap()
            ),
            "1.2345678901234568e+29"
        );
    }

    #[test]
    fn the_sampled_agent_config_matches() {
        // The live config that started this: serde_yaml_ng's flush dashes and
        // single-quote-empty habit were the divergence.
        let v = json!({
            "raw": {"model": {"model": "qwen-3.8-27b", "base_url": "https://infer.outcroplabs.com/v1", "provider": "custom"},
                    "model_aliases": {}, "fallback_providers": []},
            "main": {"model": "qwen-3.8-27b", "endpoint": "outcrop-labs"},
            "aliases": [], "fallbacks": []
        });
        let want = "raw:\n  model:\n    model: qwen-3.8-27b\n    base_url: https://infer.outcroplabs.com/v1\n    provider: custom\n  model_aliases: {}\n  fallback_providers: []\nmain:\n  model: qwen-3.8-27b\n  endpoint: outcrop-labs\naliases: []\nfallbacks: []\n";
        assert_eq!(stringify(&v), want);
    }

    #[test]
    fn nesting_chains_inline_after_the_dash() {
        assert_eq!(stringify(&json!([["x"]])), "- - x\n");
        assert_eq!(stringify(&json!([[["x"]]])), "- - - x\n");
        assert_eq!(
            stringify(&json!(["a", ["b", ["c"]]])),
            "- a\n- - b\n  - - c\n"
        );
        assert_eq!(stringify(&json!([[{"a": 1}]])), "- - a: 1\n");
        assert_eq!(stringify(&json!({"k": [[1]]})), "k:\n  - - 1\n");
        assert_eq!(
            stringify(&json!({"a": [{"b": ["c", {"d": 0}]}]})),
            "a:\n  - b:\n      - c\n      - d: 0\n"
        );
    }

    #[test]
    fn blocks_chomp_mark_and_sit_at_column_zero_at_root() {
        assert_eq!(stringify(&json!("line1\nline2")), "|-\nline1\nline2\n");
        assert_eq!(stringify(&json!("trail\n")), "|\ntrail\n");
        assert_eq!(stringify(&json!("a\n\n")), "|+\na\n\n");
        assert_eq!(stringify(&json!("a\n\"b\"")), "|-\na\n\"b\"\n");
        assert_eq!(stringify(&json!("a\rb")), "\"a\\rb\"\n");
        assert_eq!(stringify(&json!("x\n ")), "\"x\\n \"\n");
        assert_eq!(stringify(&json!(" x\ny")), "|1-\n x\ny\n");
        assert_eq!(stringify(&json!({"k": " x\ny"})), "k: |2-\n   x\n  y\n");
        // document markers force the root block's content indent to 2
        assert_eq!(stringify(&json!("----")), "|-\n  ----\n");
        assert_eq!(stringify(&json!("...x")), "|-\n  ...x\n");
        assert_eq!(stringify(&json!("a\n---x")), "|-\n  a\n  ---x\n");
        // nested markers stay plain
        assert_eq!(stringify(&json!({"k": "---x"})), "k: ---x\n");
        // blank lines ride bare; a whitespace tail with a mid newline keeps
        assert_eq!(stringify(&json!({"k": "a\n\nb\n"})), "k: |\n  a\n\n  b\n");
        assert_eq!(stringify(&json!("\n\n")), "|+\n\n\n");
        assert_eq!(stringify(&json!("a  \n\n")), "|+\na  \n\n");
        assert_eq!(stringify(&json!("a\n \n")), "|+\na\n \n");
        assert_eq!(stringify(&json!("a \n")), "|\na \n");
        // blocks as seq items indent at the item indent
        assert_eq!(stringify(&json!(["a\nb"])), "- |-\n  a\n  b\n");
    }

    #[test]
    fn folded_blocks_take_over_when_lines_are_long() {
        let words = "word ".repeat(20).trim().to_string();
        assert_eq!(
            stringify(&json!(format!("a\n{words}\n"))),
            format!(">\na\n\n{}\n{}\n", &words[..79], &words[80..])
        );
        assert_eq!(
            stringify(&json!({"k": format!("a\n{words}\n")})),
            format!("k: >\n  a\n\n  {}\n  {}\n", &words[..74], &words[75..])
        );
        // an unbreakable long line overflows the fold → literal fallback
        let un = format!("a\n{}\nb\n", "x".repeat(90));
        assert_eq!(
            stringify(&json!(un)),
            format!("|\na\n{}\nb\n", "x".repeat(90))
        );
        // more-indented lines never fold
        let mi = format!("a\n  ind {words}\nb\n");
        assert_eq!(stringify(&json!(mi)), format!(">\na\n  ind {words}\nb\n"));
        // a leading space marks the indicator even folded
        let ls = format!(" a\n{words}\n");
        assert_eq!(
            stringify(&json!(ls)),
            format!(">1\n a\n{}\n{}\n", &words[..79], &words[80..])
        );
    }

    #[test]
    fn quotes_pick_their_style_by_content() {
        assert_eq!(stringify(&json!("")), "\"\"\n");
        assert_eq!(stringify(&json!(" ")), "\" \"\n");
        assert_eq!(stringify(&json!("123")), "\"123\"\n");
        assert_eq!(stringify(&json!("yes")), "yes\n");
        assert_eq!(stringify(&json!("True")), "\"True\"\n");
        assert_eq!(stringify(&json!("-x")), "-x\n");
        assert_eq!(stringify(&json!("!x")), "\"!x\"\n");
        assert_eq!(stringify(&json!(".Inf")), "\".Inf\"\n");
        assert_eq!(stringify(&json!("-.INF")), "\"-.INF\"\n");
        assert_eq!(stringify(&json!("0b101")), "0b101\n");
        assert_eq!(stringify(&json!("a  b")), "a  b\n");
        assert_eq!(stringify(&json!("a\tb")), "a\tb\n");
        assert_eq!(stringify(&json!("a: \"x\"")), "'a: \"x\"'\n");
        assert_eq!(stringify(&json!("'\"'")), "\"'\\\"'\"\n");
        assert_eq!(stringify(&json!("he said \"hi\"")), "he said \"hi\"\n");
        assert_eq!(stringify(&json!("\u{1}ctl")), "\"\\x01ctl\"\n");
        // core-scalar shapes
        assert_eq!(stringify(&json!("0o17")), "\"0o17\"\n");
        assert_eq!(stringify(&json!("0xFF")), "\"0xFF\"\n");
        assert_eq!(stringify(&json!("5.")), "\"5.\"\n");
        assert_eq!(stringify(&json!(".5")), "\".5\"\n");
        assert_eq!(stringify(&json!("1e3")), "\"1e3\"\n");
        assert_eq!(stringify(&json!("+.1E5")), "\"+.1E5\"\n");
        assert_eq!(stringify(&json!(".NaN")), "\".NaN\"\n");
        assert_eq!(stringify(&json!("~")), "\"~\"\n");
        assert_eq!(stringify(&json!("tRue")), "tRue\n");
        assert_eq!(stringify(&json!("2026-08-29")), "2026-08-29\n");
        // trailing/leading space and tab force quotes; a space before \n escapes
        assert_eq!(stringify(&json!("a ")), "\"a \"\n");
        assert_eq!(stringify(&json!(" a")), "\" a\"\n");
        assert_eq!(stringify(&json!("a\t")), "\"a\\t\"\n");
        assert_eq!(stringify(&json!(" \nx")), "|1-\n \nx\n");
    }

    #[test]
    fn long_lines_fold_at_eighty() {
        let words = "word ".repeat(30).trim().to_string();
        let expect = "word word word word word word word word word word word word word word word word\nword word word word word word word word word word word word word word\n";
        assert_eq!(stringify(&json!(words)), expect);
        let long = format!("verylongwordhere {}", "y".repeat(99));
        let expect = format!("verylongwordhere\n{}\n", "y".repeat(99));
        assert_eq!(stringify(&json!(long)), expect);
        // Double-quoted hard-breaks with a `\` continuation at exactly 80.
        let s = format!("zz: {}", "x".repeat(100));
        let expect = format!("\"zz:\n{}\\\n{}\"\n", "x".repeat(79), "x".repeat(21));
        assert_eq!(stringify(&json!(s)), expect);
        // Single-quoted folds at spaces but rides long runs whole.
        let s = format!("a: \"{}", "x".repeat(100));
        let expect = format!("'a:\n\"{}'\n", "x".repeat(100));
        assert_eq!(stringify(&json!(s)), expect);
        // The fold backs up past a double space to the last eligible point.
        let s = format!("{}  finalword", "word ".repeat(15).trim_end());
        let expect = format!("{}\nword  finalword\n", "word ".repeat(14).trim_end());
        assert_eq!(stringify(&json!(s)), expect);
        // Under a key the key's width counts (indentAtStart).
        let words = "word ".repeat(30).trim().to_string();
        let expect = format!("k: {}\n  {}\n", &words[..74], &words[75..]);
        assert_eq!(stringify(&json!({ "k": words })), expect);
        // A key past 60 columns sends the value to its own line (fold at 0).
        let key = "k".repeat(61);
        let s = "word ".repeat(30).trim().to_string();
        let expect = format!("{key}:\n  {}\n  {}\n", &s[..74], &s[75..]);
        assert_eq!(stringify(&json!({ key.clone(): s })), expect);
        // Seq items don't count the dash (no indentAtStart).
        let xs = "x".repeat(100);
        let expect = format!("- \"zz:\n  {}\\\n  {}\"\n", &xs[..77], &xs[77..]);
        assert_eq!(stringify(&json!([format!("zz: {xs}")])), expect);
        // Repeated hard cuts chain (`escapedFolds` only bails on the same j).
        let ys = "y".repeat(200);
        let expect = format!(
            "k: \"zz:\n  {}\\\n  {}\\\n  {}\"\n",
            &ys[..77],
            &ys[77..154],
            &ys[154..]
        );
        assert_eq!(stringify(&json!({ "k": format!("zz: {ys}") })), expect);
    }

    #[test]
    fn multiline_double_quoted_uses_real_newlines_when_long() {
        // ≥ 40 JSON units with a \n → real doubled newlines + indent.
        let s = format!("x\r{}\n{}", "y".repeat(60), "z".repeat(60));
        let expect = format!("\"x\\r{}\n\n{}\"\n", "y".repeat(60), "z".repeat(60));
        assert_eq!(stringify(&json!(s)), expect);
        // Short ones keep the escapes.
        assert_eq!(stringify(&json!("a\r\nb")), "\"a\\r\\nb\"\n");
    }

    #[test]
    fn keys_never_fold() {
        let k = "word ".repeat(20).trim().to_string();
        assert_eq!(
            stringify(&json!({ k.clone(): {"y": 1} })),
            format!("{k}:\n  y: 1\n")
        );
        // a core-scalar key quotes
        assert_eq!(stringify(&json!({"5": 1})), "\"5\": 1\n");
        assert_eq!(stringify(&json!({"": 1})), "\"\": 1\n");
        assert_eq!(stringify(&json!({"": {"": 1}})), "\"\":\n  \"\": 1\n");
        // past 1024 the explicit `? key` form
        let long_key = "k".repeat(1025);
        assert_eq!(
            stringify(&json!({ long_key.clone(): 1 })),
            format!("? {long_key}\n: 1\n")
        );
    }

    #[test]
    fn nulls_and_empties() {
        assert_eq!(stringify(&json!({"a": null})), "a: null\n");
        assert_eq!(
            stringify(&json!({"a": null, "b": null})),
            "a: null\nb: null\n"
        );
        assert_eq!(stringify(&json!({})), "{}\n");
        assert_eq!(stringify(&json!([])), "[]\n");
        assert_eq!(stringify(&json!({"k": [null]})), "k:\n  - null\n");
        assert_eq!(stringify(&json!({"m": {}, "s": []})), "m: {}\ns: []\n");
    }

    #[test]
    fn controls_force_double_quotes_and_stay_raw_past_ascii() {
        // \x7f and C1 controls are raw inside double quotes (JSON.stringify
        // leaves them unescaped; the style switch is what quotes them).
        assert_eq!(stringify(&json!("\u{7f}")), "\"\u{7f}\"\n");
        assert_eq!(stringify(&json!("\u{85}x")), "\"\u{85}x\"\n");
        // a raw tab interior stays plain; escaped only when quoted
        assert_eq!(stringify(&json!("a\tb")), "a\tb\n");
        // non-ASCII rides plain
        assert_eq!(stringify(&json!("\u{a0}x")), "\u{a0}x\n");
        assert_eq!(stringify(&json!("\u{2028}x")), "\u{2028}x\n");
    }
}
