// The emoji vocabulary: a curated Slack-style set, not a full unicode browser.
// Names are the `:shortcode:` tokens; first name is canonical (shown in menus).
export interface EmojiEntry {
  ch: string
  names: string[]
}

export const EMOJI: EmojiEntry[] = [
  { ch: '👍', names: ['thumbsup', '+1'] },
  { ch: '👎', names: ['thumbsdown', '-1'] },
  { ch: '✅', names: ['white_check_mark', 'check', 'done'] },
  { ch: '❌', names: ['x', 'no'] },
  { ch: '👀', names: ['eyes', 'looking'] },
  { ch: '🎉', names: ['tada', 'party'] },
  { ch: '❤️', names: ['heart', 'love'] },
  { ch: '😂', names: ['joy', 'lol'] },
  { ch: '🚀', names: ['rocket', 'ship'] },
  { ch: '🙏', names: ['pray', 'thanks'] },
  { ch: '🔥', names: ['fire', 'lit'] },
  { ch: '💯', names: ['100'] },
  { ch: '😄', names: ['smile'] },
  { ch: '😃', names: ['smiley'] },
  { ch: '😀', names: ['grinning'] },
  { ch: '😁', names: ['grin'] },
  { ch: '😆', names: ['laughing'] },
  { ch: '😅', names: ['sweat_smile'] },
  { ch: '🤣', names: ['rofl'] },
  { ch: '🙂', names: ['slightly_smiling_face'] },
  { ch: '😉', names: ['wink'] },
  { ch: '😊', names: ['blush'] },
  { ch: '😍', names: ['heart_eyes'] },
  { ch: '🤩', names: ['star_struck'] },
  { ch: '😘', names: ['kissing_heart'] },
  { ch: '😜', names: ['stuck_out_tongue_winking_eye'] },
  { ch: '🤔', names: ['thinking', 'hmm'] },
  { ch: '🤨', names: ['raised_eyebrow'] },
  { ch: '😐', names: ['neutral_face'] },
  { ch: '😴', names: ['sleeping'] },
  { ch: '😷', names: ['mask'] },
  { ch: '🤯', names: ['exploding_head', 'mind_blown'] },
  { ch: '😎', names: ['sunglasses', 'cool'] },
  { ch: '🥳', names: ['partying_face'] },
  { ch: '😢', names: ['cry'] },
  { ch: '😭', names: ['sob'] },
  { ch: '😤', names: ['triumph'] },
  { ch: '😡', names: ['rage', 'angry'] },
  { ch: '🤬', names: ['cursing'] },
  { ch: '😱', names: ['scream'] },
  { ch: '😬', names: ['grimacing'] },
  { ch: '🙄', names: ['roll_eyes'] },
  { ch: '😳', names: ['flushed'] },
  { ch: '🥺', names: ['pleading_face'] },
  { ch: '😇', names: ['innocent'] },
  { ch: '🤗', names: ['hugs'] },
  { ch: '🤫', names: ['shushing_face'] },
  { ch: '🤝', names: ['handshake', 'deal'] },
  { ch: '👋', names: ['wave', 'hello'] },
  { ch: '👏', names: ['clap'] },
  { ch: '🙌', names: ['raised_hands', 'hooray'] },
  { ch: '👌', names: ['ok_hand', 'ok'] },
  { ch: '✌️', names: ['v', 'peace'] },
  { ch: '🤞', names: ['crossed_fingers'] },
  { ch: '💪', names: ['muscle', 'strong'] },
  { ch: '🖖', names: ['vulcan_salute'] },
  { ch: '🫡', names: ['salute'] },
  { ch: '☝️', names: ['point_up'] },
  { ch: '👇', names: ['point_down'] },
  { ch: '👆', names: ['point_up_2'] },
  { ch: '👈', names: ['point_left'] },
  { ch: '👉', names: ['point_right'] },
  { ch: '🧠', names: ['brain'] },
  { ch: '🫀', names: ['anatomical_heart'] },
  { ch: '💡', names: ['bulb', 'idea'] },
  { ch: '⚡', names: ['zap', 'lightning'] },
  { ch: '⭐', names: ['star'] },
  { ch: '✨', names: ['sparkles'] },
  { ch: '☀️', names: ['sunny'] },
  { ch: '🌙', names: ['crescent_moon'] },
  { ch: '🌈', names: ['rainbow'] },
  { ch: '☁️', names: ['cloud'] },
  { ch: '🌧️', names: ['rain'] },
  { ch: '❄️', names: ['snowflake'] },
  { ch: '☕', names: ['coffee'] },
  { ch: '🍺', names: ['beer'] },
  { ch: '🍕', names: ['pizza'] },
  { ch: '🍔', names: ['hamburger', 'burger'] },
  { ch: '🌮', names: ['taco'] },
  { ch: '🍩', names: ['doughnut', 'donut'] },
  { ch: '🎂', names: ['birthday', 'cake'] },
  { ch: '🍿', names: ['popcorn'] },
  { ch: '🐛', names: ['bug'] },
  { ch: '🐞', names: ['beetle'] },
  { ch: '🦋', names: ['butterfly'] },
  { ch: '🐢', names: ['turtle', 'slow'] },
  { ch: '🐇', names: ['rabbit', 'fast'] },
  { ch: '🐈', names: ['cat'] },
  { ch: '🐕', names: ['dog'] },
  { ch: '🦄', names: ['unicorn'] },
  { ch: '🐙', names: ['octopus'] },
  { ch: '🦈', names: ['shark'] },
  { ch: '🔧', names: ['wrench'] },
  { ch: '🔨', names: ['hammer'] },
  { ch: '🛠️', names: ['hammer_and_wrench', 'tools'] },
  { ch: '⚙️', names: ['gear'] },
  { ch: '🔒', names: ['lock', 'locked'] },
  { ch: '🔓', names: ['unlock'] },
  { ch: '🔑', names: ['key'] },
  { ch: '🧪', names: ['test_tube', 'experiment'] },
  { ch: '🧭', names: ['compass'] },
  { ch: '🔍', names: ['mag', 'search'] },
  { ch: '📌', names: ['pushpin', 'pin'] },
  { ch: '📎', names: ['paperclip'] },
  { ch: '📝', names: ['memo', 'note'] },
  { ch: '📄', names: ['page_facing_up', 'doc'] },
  { ch: '📚', names: ['books'] },
  { ch: '📦', names: ['package', 'shipped'] },
  { ch: '📈', names: ['chart_with_upwards_trend', 'chart_up'] },
  { ch: '📉', names: ['chart_with_downwards_trend', 'chart_down'] },
  { ch: '📊', names: ['bar_chart'] },
  { ch: '📅', names: ['calendar'] },
  { ch: '⏰', names: ['alarm_clock'] },
  { ch: '⏳', names: ['hourglass'] },
  { ch: '💰', names: ['moneybag', 'money'] },
  { ch: '💸', names: ['money_with_wings'] },
  { ch: '🏆', names: ['trophy', 'win'] },
  { ch: '🥇', names: ['first_place'] },
  { ch: '🎯', names: ['dart', 'target'] },
  { ch: '🎲', names: ['game_die', 'dice'] },
  { ch: '🎮', names: ['video_game'] },
  { ch: '🎧', names: ['headphones'] },
  { ch: '🎵', names: ['musical_note', 'music'] },
  { ch: '📣', names: ['mega', 'announcement'] },
  { ch: '🔔', names: ['bell'] },
  { ch: '🚨', names: ['rotating_light', 'alert'] },
  { ch: '⚠️', names: ['warning'] },
  { ch: '🛑', names: ['stop_sign', 'stop'] },
  { ch: '🚧', names: ['construction', 'wip'] },
  { ch: '🐌', names: ['snail'] },
  { ch: '💤', names: ['zzz'] },
  { ch: '💥', names: ['boom', 'collision'] },
  { ch: '💫', names: ['dizzy'] },
  { ch: '💬', names: ['speech_balloon'] },
  { ch: '💭', names: ['thought_balloon'] },
  { ch: '👻', names: ['ghost'] },
  { ch: '🤖', names: ['robot'] },
  { ch: '💀', names: ['skull', 'dead'] },
  { ch: '🤡', names: ['clown'] },
  { ch: '🫠', names: ['melting_face'] },
  { ch: '🍾', names: ['champagne'] },
  { ch: '🥂', names: ['clinking_glasses', 'cheers'] },
  { ch: '🌱', names: ['seedling'] },
  { ch: '🌊', names: ['ocean', 'wave_water'] },
  { ch: '🏔️', names: ['mountain'] },
  { ch: '🗿', names: ['moai'] },
  { ch: '♻️', names: ['recycle'] },
  { ch: '💚', names: ['green_heart'] },
  { ch: '💙', names: ['blue_heart'] },
  { ch: '💜', names: ['purple_heart'] },
  { ch: '🖤', names: ['black_heart'] },
  { ch: '💔', names: ['broken_heart'] },
]

const byName = new Map<string, string>()
for (const e of EMOJI) for (const n of e.names) byName.set(n, e.ch)

/** Prefix-then-substring match over shortcode names. */
export function searchEmoji(q: string, limit = 24): EmojiEntry[] {
  const needle = q.toLowerCase().trim()
  if (!needle) return EMOJI.slice(0, limit)
  const starts = EMOJI.filter((e) => e.names.some((n) => n.startsWith(needle)))
  const contains = EMOJI.filter((e) => !starts.includes(e) && e.names.some((n) => n.includes(needle)))
  return [...starts, ...contains].slice(0, limit)
}

/** Replace complete `:shortcode:` tokens with their emoji. Unknown codes are
 *  left alone — ":shrug:" you typed on purpose survives verbatim. */
export function emojify(text: string): string {
  return text.replace(/:([a-z0-9_+-]+):/gi, (all, name: string) => byName.get(name.toLowerCase()) ?? all)
}
