#!/bin/sh
# Talaria container entrypoint. The image carries no config: the environment
# is the ONLY channel (real env always wins — server-entry.js skips .env keys
# already in process.env, and this script follows the same contract). What the
# environment doesn't supply, the entrypoint generates ONCE into the persistent
# state dir and re-reads on later boots:
#
#   $STATE_DIR/env/generated.env   secrets + first-boot admin credentials
#   $STATE_DIR/fleet/              chassis.yml + .env (user-editable after)
#
# State must be a HOST BIND mounted at the SAME path inside the container
# (default /var/lib/talaria): the fleet renderer bakes absolute host paths
# into agent bind mounts, and the host daemon — not this container — resolves
# them. A named volume would be invisible to the agents.
#
# Subcommands (same image, different roles — see docker/compose.yml):
#   render-searxng   render the SearXNG settings file (one-shot init service;
#                    SearXNG reads its secret from settings.yml, not the env)
# With no argument: full boot — secrets, seeds, dependency gate, exec the app.
#
# POSIX sh (busybox ash): the runtime image has no bash, and nothing here
# needs it — no brace expansion, no [[ ]], no arrays.
set -eu

APP_DIR=/app
STATE_DIR="${TALARIA_STATE_DIR:-/var/lib/talaria}"
GEN_ENV="$STATE_DIR/env/generated.env"
APP_UID=10001
APP_GID=10001

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
warn() { printf '\033[33m! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# Hex secret via bun's webcrypto — the one crypto source guaranteed present
# (the runtime image has no openssl, and busybox tools vary). Guarded: a broken
# bun must abort the boot, never mint an empty secret that then persists.
rand_hex() {
  _hex=$(bun -e "console.log(Buffer.from(globalThis.crypto.getRandomValues(new Uint8Array($1))).toString('hex'))" 2>/dev/null) \
    || die "bun failed — cannot generate secrets"
  case $_hex in
    *[!0-9a-f]*|'') die "bun produced invalid secret output" ;;
  esac
  printf '%s' "$_hex"
}

# ── State tree ───────────────────────────────────────────────────────────────
mkdir_state() {
  mkdir -p "$STATE_DIR/uploads" \
           "$STATE_DIR/fleet/agents" \
           "$STATE_DIR/fleet/skills" \
           "$STATE_DIR/fleet/hooks" \
           "$STATE_DIR/apps" \
           "$STATE_DIR/env" 2>/dev/null || {
    # The one failure that actually happens: docker auto-created the bind
    # source as root (or the operator forgot the chown) and uid 10001 can't
    # write. Name the exact fix rather than dying with a bare EACCES.
    die "cannot write $STATE_DIR as $(id -u):$(id -g) — on the HOST run:
  mkdir -p $STATE_DIR && chown $APP_UID:$APP_GID $STATE_DIR"
  }
}

# ── Secrets bootstrap ────────────────────────────────────────────────────────
# For each var: real env wins (nothing generated); else an existing
# generated.env line wins (persistence across container recreation); else
# generate and append. Same lengths as `talaria setup` so a container
# instance and a host install hold interchangeable secrets.
bootstrap_secrets() {
  if [ ! -f "$GEN_ENV" ]; then
    (umask 077 && printf '# Generated by the Talaria container entrypoint — first boot only.\n# Real environment always wins over this file. Back it up with the database\n# (docs/ENCRYPTION.md): every stored secret is sealed with TALARIA_SECRET_KEY.\n' > "$GEN_ENV")
  fi

  ensure_secret TALARIA_SECRET_KEY 32   # encryption root — NEVER rotates
  ensure_secret AUTH_SECRET 32          # session signing — safe to rotate
  ensure_secret SEARXNG_SECRET 32       # rendered into the searxng settings
  ensure_secret TALARIA_AGENT_KEY 32    # app's hop to the toolkit service

  # No admin is generated here: a fresh instance is CLAIMED in the app — the
  # first visitor creates the admin account. The banner below says so.
}

ensure_secret() { # <name> <bytes>
  printenv "$1" >/dev/null 2>&1 && return 0
  grep -q "^$1=" "$GEN_ENV" 2>/dev/null && return 0
  printf '%s=%s\n' "$1" "$(rand_hex "$2")" >> "$GEN_ENV"
}

# Export generated values ONLY for vars the real env doesn't set — the
# server-entry.js precedence, applied one layer earlier.
export_generated() {
  [ -f "$GEN_ENV" ] || return 0
  while IFS='=' read -r k v; do
    case $k in ''|'#'*) continue ;; esac
    printenv "$k" >/dev/null 2>&1 || export "$k=$v"
  done < "$GEN_ENV"
}

# ── Fleet config seeds (only if missing — user edits must survive) ──────────
seed_fleet() {
  if [ ! -f "$STATE_DIR/fleet/chassis.yml" ]; then
    cp "$APP_DIR/scripts/chassis.template.yml" "$STATE_DIR/fleet/chassis.yml"
    say "seeded fleet/chassis.yml from the template"
  fi
  if [ ! -f "$STATE_DIR/fleet/.env" ]; then
    cat > "$STATE_DIR/fleet/.env" <<'EOF'
# Fleet env — compose interpolation + per-agent HERMES_KEY_* (Talaria appends
# those automatically when you create agents). Fill in your LLM endpoint to
# give agents a brain; the app itself runs fine without.
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
#HERMES_IMAGE=nousresearch/hermes-agent:latest
EOF
    say "seeded fleet/.env"
  fi
  chmod 700 "$STATE_DIR/fleet" 2>/dev/null || true
  chmod 600 "$GEN_ENV" 2>/dev/null || true
}

# When the entrypoint runs as root (the searxng init service does, so it can
# write the compose-created settings volume), hand everything it made back to
# the app user: the app container runs unprivileged and must both read these
# and write SIBLINGS (the renderer adds fleet/agents/<slug>/ at every render).
# Non-recursive on purpose — uploads can be large; only the bootstrap leaves
# (env dir + the state tree skeleton) are ours to fix.
chown_state_if_root() {
  [ "$(id -u)" = 0 ] || return 0
  chown "$APP_UID:$APP_GID" \
    "$STATE_DIR" \
    "$STATE_DIR/uploads" \
    "$STATE_DIR/fleet" \
    "$STATE_DIR/fleet/agents" \
    "$STATE_DIR/fleet/skills" \
    "$STATE_DIR/fleet/hooks" \
    "$STATE_DIR/apps" \
    "$STATE_DIR/env" 2>/dev/null || true
  chown -R "$APP_UID:$APP_GID" "$STATE_DIR/env" 2>/dev/null || true
}

# ── SearXNG settings render (init-service role) ─────────────────────────────
render_searxng() {
  target="${SEARXNG_SETTINGS_TARGET:-/etc/searxng/settings.yml}"
  mkdir -p "$(dirname "$target")"
  # Same substitution the dev stack's renderer performs (cli/src/searxng.ts);
  # hex secrets cannot collide with the | delimiter. Always rendered (the
  # init runs once per `up` — cheaper than freshness bookkeeping).
  sed "s|__SEARXNG_SECRET__|${SEARXNG_SECRET:?SEARXNG_SECRET unset and not generated}|g" \
    "$APP_DIR/docker/searxng/settings.template.yml" > "$target"
  chmod 644 "$target"
  say "rendered $target"
}

# ── Dispatch ─────────────────────────────────────────────────────────────────
case "${1:-}" in
  render-searxng)
    # Init service: the FIRST thing to touch state on a fresh host, so it
    # owns first-boot generation; the app then depends_on its completion and
    # finds everything present (no two writers, no race).
    mkdir_state
    bootstrap_secrets
    export_generated
    render_searxng
    chown_state_if_root
    exit 0
    ;;
  *)
    mkdir_state
    bootstrap_secrets
    export_generated
    seed_fleet

    # The claim replaces generated credentials: an operator reading the logs
    # on a first boot needs the one-line version of "where do I sign in".
    # Stateless (no marker) on purpose — a restored backup gets the same
    # pointer, and unlike a password it can never be stale or wrong.
    say "first boot: claim the admin account at /claim once the app is up"

    say "waiting for dependencies (postgres, redis)"
    bun "$APP_DIR/docker/await-deps.mjs"

    say "starting Talaria on :${PORT:-5273}"
    exec bun server-entry.js
    ;;
esac
