// Per-app Postgres: one compose project per installed app, spawned on
// first use / install and destroyed on uninstall. App data never shares
// Talaria's database — a runaway query, a filled disk, or a DROP TABLE in
// an app cannot touch the platform catalog. The store API is unchanged;
// only the process behind it is.
import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, chmodSync } from 'node:fs'
import { join } from 'node:path'
import { spawn } from 'node:child_process'
import postgres, { type Sql } from 'postgres'
import { getSetting, setSetting } from './audit'
import { open, seal, secretboxFailure } from './secretbox'
import { slugOk, appsDir } from './app-build/paths'

const PASSWORDS_KEY = 'app_db_passwords'
const DEFAULT_IMAGE = 'docker.io/library/postgres:16-alpine'

const pools = new Map<string, Sql>()

function instanceId(): string {
  return process.env.TALARIA_WORKTREE || process.env.TALARIA_DEVBOX || 'talaria'
}

export function appDbContainer(slug: string): string {
  return `talaria-appdb-${instanceId()}-${slug}`
}

export function appDataDir(slug: string): string {
  const root = process.env.TALARIA_APP_DATA_DIR || join(appsDir(), '..', 'app-data')
  return join(root, slug)
}

function inImage(): boolean {
  return process.env.TALARIA_INSTALL === 'image' || process.env.TALARIA_RUNTIME === 'prod-server'
}

function composeFile(slug: string): string {
  return join(appDataDir(slug), 'docker-compose.yml')
}

function envFile(slug: string): string {
  return join(appDataDir(slug), 'db.env')
}

function dumpFile(slug: string): string {
  return join(appDataDir(slug), 'dump.sql')
}

/** Compose file for one app DB. Password lives in db.env (0600), never here. */
export function composeYaml(opts: { image: string; container: string; network: string | null }): string {
  const lines = [
    '# Generated by Talaria — do not edit.',
    'services:',
    '  postgres:',
    `    image: ${opts.image}`,
    `    container_name: ${opts.container}`,
    '    restart: unless-stopped',
    '    security_opt:',
    '      - no-new-privileges:true',
    '    env_file:',
    '      - db.env',
    '    volumes:',
    '      - ./pg:/var/lib/postgresql/data',
  ]
  if (opts.network) {
    lines.push(
      '    networks:',
      '      - appdb',
      'networks:',
      '  appdb:',
      '    external: true',
      `    name: ${opts.network}`,
      '',
    )
  } else {
    lines.push('    ports:', '      - "127.0.0.1::5432"', '')
  }
  return lines.join('\n')
}

function readPasswordFile(path: string): string | null {
  if (!existsSync(path)) return null
  const m = readFileSync(path, 'utf8').match(/^POSTGRES_PASSWORD=(.*)$/m)
  const pass = m?.[1]?.trim() ?? ''
  return pass || null
}

function writePasswordFile(path: string, password: string): void {
  writeFileSync(path, `POSTGRES_USER=talaria\nPOSTGRES_PASSWORD=${password}\nPOSTGRES_DB=talaria\n`, {
    mode: 0o600,
  })
  chmodSync(path, 0o600)
}

async function loadOrCreatePassword(slug: string): Promise<string> {
  const fail = secretboxFailure()
  if (fail) throw new Error(`app db password: ${fail}`)
  const fromFile = readPasswordFile(envFile(slug))
  const stored = await getSetting<Record<string, string>>(PASSWORDS_KEY, {})
  let pass = fromFile
  if (!pass && stored[slug]) {
    try {
      pass = open(stored[slug])
    } catch {
      pass = null
    }
  }
  if (!pass) pass = randomBytes(24).toString('base64url')
  let sealedOk = false
  if (stored[slug]) {
    try {
      sealedOk = open(stored[slug]) === pass
    } catch {
      sealedOk = false
    }
  }
  if (!sealedOk) {
    await setSetting(PASSWORDS_KEY, { ...stored, [slug]: seal(pass) })
  }
  writePasswordFile(envFile(slug), pass)
  return pass
}

async function forgetPassword(slug: string): Promise<void> {
  const stored = await getSetting<Record<string, string>>(PASSWORDS_KEY, {})
  if (!(slug in stored)) return
  const next = { ...stored }
  delete next[slug]
  await setSetting(PASSWORDS_KEY, next)
}

async function docker(
  args: string[],
  timeoutMs = 60_000,
  stdin?: string,
): Promise<{ ok: boolean; stdout: string; stderr: string }> {
  const child = spawn('docker', args, { stdio: [stdin != null ? 'pipe' : 'ignore', 'pipe', 'pipe'] })
  let stdout = ''
  let stderr = ''
  child.stdout?.on('data', (c: Buffer) => {
    stdout += c.toString()
  })
  child.stderr?.on('data', (c: Buffer) => {
    stderr += c.toString()
  })
  return await new Promise((resolve) => {
    const t = setTimeout(() => {
      child.kill('SIGKILL')
      resolve({ ok: false, stdout, stderr: stderr || `docker ${args[0]} timed out` })
    }, timeoutMs)
    if (stdin != null) child.stdin?.end(stdin)
    child.on('close', (code) => {
      clearTimeout(t)
      resolve({ ok: code === 0, stdout: stdout.trim(), stderr: stderr.trim() })
    })
    child.on('error', (e) => {
      clearTimeout(t)
      resolve({ ok: false, stdout, stderr: e instanceof Error ? e.message : String(e) })
    })
  })
}


async function compose(slug: string, args: string[], timeoutMs = 120_000): Promise<{ ok: boolean; stdout: string; stderr: string }> {
  return docker(['compose', '-p', appDbContainer(slug), '-f', composeFile(slug), ...args], timeoutMs)
}

async function runningNetwork(): Promise<string | null> {
  const named = process.env.TALARIA_APP_DB_NETWORK
  if (named) return named
  // Inside the image the app is on `internal`; attach app DBs there so the
  // fleet network never sees postgres (compose.yml: agents can reach the app,
  // never postgres).
  const self = process.env.HOSTNAME
  if (!self || !inImage()) return null
  const inspect = await docker(['inspect', '-f', '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}\n{{end}}', self])
  const nets = inspect.stdout.split('\n').map((s) => s.trim()).filter(Boolean)
  return nets.find((n) => n.endsWith('_internal') || n === 'internal') ?? nets[0] ?? null
}

async function pinnedImage(): Promise<string> {
  const tag = process.env.TALARIA_APP_DB_IMAGE || process.env.TALARIA_PG_IMAGE || DEFAULT_IMAGE
  const r = await docker(['image', 'inspect', '-f', '{{json .RepoDigests}}', tag], 15_000)
  if (r.ok) {
    try {
      const digests = JSON.parse(r.stdout) as unknown
      if (Array.isArray(digests) && typeof digests[0] === 'string' && digests[0]) return digests[0]
    } catch {
      /* tag fallback */
    }
  }
  return tag
}

async function containerState(name: string): Promise<'running' | 'exited' | 'missing'> {
  const r = await docker(['inspect', '-f', '{{.State.Running}}', name], 10_000)
  if (!r.ok) return 'missing'
  return r.stdout === 'true' ? 'running' : 'exited'
}

async function waitHealthy(name: string, timeoutMs = 60_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    const r = await docker(['exec', name, 'pg_isready', '-U', 'talaria', '-d', 'talaria'], 8_000)
    if (r.ok) return true
    await new Promise<void>((resolve) => setTimeout(resolve, 400))
  }
  return false
}


async function publishedPort(name: string): Promise<number | null> {
  const r = await docker(['port', name, '5432/tcp'], 10_000)
  if (!r.ok) return null
  const m = r.stdout.match(/:(\d+)\s*$/)
  return m ? Number(m[1]) : null
}

async function spawnContainer(slug: string, password: string): Promise<void> {
  const name = appDbContainer(slug)
  const dir = appDataDir(slug)
  mkdirSync(join(dir, 'pg'), { recursive: true, mode: 0o700 })
  writePasswordFile(envFile(slug), password)
  writeFileSync(
    composeFile(slug),
    composeYaml({ image: await pinnedImage(), container: name, network: await runningNetwork() }),
  )
  let up = await compose(slug, ['up', '-d'], 180_000)
  if (!up.ok) {
    await docker(['rm', '-f', name], 30_000)
    up = await compose(slug, ['up', '-d'], 180_000)
  }
  if (!up.ok) throw new Error(`spawn app db ${slug}: ${up.stderr || up.stdout || 'docker compose up failed'}`)
}

export function appDbUrl(_slug: string, port: number | null, host: string, password: string): string {
  const pass = encodeURIComponent(password)
  const hostname = host.includes(':') ? `[${host}]` : host
  const p = port ?? 5432
  return `postgres://talaria:${pass}@${hostname}:${p}/talaria`
}


async function connectUrl(slug: string, password: string): Promise<string> {
  const name = appDbContainer(slug)
  if (inImage()) return appDbUrl(slug, 5432, name, password)
  const port = await publishedPort(name)
  if (port == null) throw new Error(`app db ${slug} has no published port`)
  return appDbUrl(slug, port, '127.0.0.1', password)
}

const SCHEMA = `
create table if not exists docs (
  collection text not null,
  id uuid not null default gen_random_uuid(),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (collection, id)
);
create index if not exists docs_updated_idx on docs (collection, updated_at desc);
`

async function applyDump(slug: string): Promise<void> {
  const path = dumpFile(slug)
  if (!existsSync(path)) return
  const sql = readFileSync(path, 'utf8')
  const r = await docker(
    ['exec', '-i', appDbContainer(slug), 'psql', '-U', 'talaria', '-d', 'talaria', '-v', 'ON_ERROR_STOP=1', '-q'],
    180_000,
    sql,
  )
  if (!r.ok) throw new Error(`restore app db ${slug}: ${r.stderr || r.stdout || 'psql failed'}`)
  rmSync(path)
}

/** Spawn (if needed) and return a pooled client for this app's own Postgres. */
export async function appSql(slug: string): Promise<Sql> {
  if (!slugOk(slug)) throw new Error('bad slug')
  const hit = pools.get(slug)
  if (hit) return hit
  const password = await loadOrCreatePassword(slug)
  const name = appDbContainer(slug)
  const state = await containerState(name)
  if (state !== 'running') await spawnContainer(slug, password)
  if (!(await waitHealthy(name))) throw new Error(`app db ${slug} did not become ready`)
  await applyDump(slug)
  const sql = postgres(await connectUrl(slug, password), {
    max: 8,
    idle_timeout: 20,
    connect_timeout: 15,
    onnotice: () => {},
  })
  await sql.unsafe(SCHEMA)
  pools.set(slug, sql)
  return sql
}

export async function dropAppDatabase(slug: string): Promise<void> {
  if (!slugOk(slug)) return
  const sql = pools.get(slug)
  if (sql) {
    pools.delete(slug)
    try {
      await sql.end({ timeout: 2 })
    } catch {
      /* already gone */
    }
  }
  if (existsSync(composeFile(slug))) {
    await compose(slug, ['down', '--remove-orphans'], 60_000)
  }
  await docker(['rm', '-f', appDbContainer(slug)], 30_000)
  const dir = appDataDir(slug)
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true })
  await forgetPassword(slug).catch(() => {})
}
