#!/usr/bin/env bash
# Talaria first-time dev setup — blank machine → ready-to-run stack.
# Idempotent: existing files are left alone; run it again any time.
#
#   ./scripts/setup.sh        then:        ./scripts/dev.sh
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip() { printf '  \033[2m– %s (exists, kept)\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

rand() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

say "Checking prerequisites"
command -v docker >/dev/null || die "docker is required (https://docs.docker.com/get-docker/)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
command -v node >/dev/null || die "node is required (>= 20)"
[ "$(node -e 'console.log(process.versions.node.split(".")[0])')" -ge 20 ] || die "node >= 20 required (found $(node -v))"
ok "docker, compose, node $(node -v)"

PG_PORT="${TALARIA_PG_PORT:-5544}"
REDIS_PORT="${TALARIA_REDIS_PORT:-6399}"

say "App secrets + config (ui/.env)"
if [ -f ui/.env ]; then
  skip "ui/.env"
  ADMIN_EMAIL="(unchanged — see ui/.env)"
  ADMIN_PASS="(unchanged)"
else
  ADMIN_EMAIL="admin@talaria.local"
  ADMIN_PASS="$(rand 9)"
  cat > ui/.env <<EOF
# Talaria dev config — generated by scripts/setup.sh $(date -u +%F). Safe to edit.

# Durable state
DATABASE_URL=postgres://talaria:talaria@127.0.0.1:${PG_PORT}/talaria
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}

# Session signing (safe to rotate — only invalidates live logins).
AUTH_SECRET=$(rand 32)

# Encryption root key (KEK) for secrets at rest. DEDICATED and STABLE: keep it
# constant — changing it makes every encrypted secret unrecoverable. Worktrees
# MUST share this exact value (scripts/worktree.sh copies it) so a second stack
# can decrypt data seeded from this one.
TALARIA_SECRET_KEY=$(rand 32)

# Password sign-in. Format: email:password[,email:password...]
AUTH_PASSWORD_ENABLED=1
AUTH_USERS=${ADMIN_EMAIL}:${ADMIN_PASS}
AUTH_ADMIN_EMAILS=${ADMIN_EMAIL}

# Google sign-in (off until you add real credentials)
AUTH_GOOGLE_ENABLED=0
AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=

# Agents authenticate to Talaria's APIs with this key + x-agent-name header
TALARIA_AGENT_KEY=$(rand 32)
EOF
  ok "ui/.env generated"
fi

say "Fleet config plane (fleet/)"
mkdir -p fleet/skills fleet/hooks fleet/agents stack
if [ -f fleet/chassis.yml ]; then skip "fleet/chassis.yml"; else
  cp scripts/chassis.template.yml fleet/chassis.yml && ok "fleet/chassis.yml (from template)"
fi
if [ -f fleet/.env ]; then skip "fleet/.env"; else
  cat > fleet/.env <<'EOF'
# Fleet env — compose interpolation + per-agent HERMES_KEY_* (Talaria appends
# those automatically when you create agents). Fill in your LLM endpoint to
# give agents a brain; the app itself runs fine without.
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
#HERMES_IMAGE=nousresearch/hermes-agent:latest
EOF
  ok "fleet/.env generated (add your LLM endpoint before starting agents)"
fi

say "Docker plumbing"
docker network inspect talaria >/dev/null 2>&1 && skip "network talaria" || {
  docker network create talaria >/dev/null && ok "network talaria"
}
docker compose -f docker/dev-compose.yml pull -q 2>/dev/null || true
ok "postgres + redis images ready"

say "App dependencies"
if [ -d ui/node_modules ]; then skip "ui/node_modules"; else
  (cd ui && npm install --no-fund --no-audit) && ok "npm install"
fi

say "Git convenience"
# `git wt <name>` → an isolated dev worktree (own DB seeded from main). Using this
# instead of a plain `git worktree add` keeps a second app off your main DB.
git config alias.wt '!bash scripts/worktree.sh' 2>/dev/null && ok "git wt → scripts/worktree.sh" || skip "git alias"

echo
printf '\033[1;32mSetup complete.\033[0m\n\n'
echo "  Start everything:   ./scripts/dev.sh"
echo "  App:                http://localhost:5273"
echo "  Sign in:            ${ADMIN_EMAIL}  /  ${ADMIN_PASS}"
echo
echo "  First steps in the app: Settings → add an LLM endpoint on /models,"
echo "  then design your first agent on /agents (Muse will draft it)."
