#!/usr/bin/env bash
# Talaria first-time dev setup — blank machine → ready-to-run stack.
# Idempotent: existing files are left alone; run it again any time.
#
#   ./scripts/setup.sh        then:        ./scripts/dev.sh
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip() { printf '  \033[2m– %s (exists, kept)\033[0m\n' "$*"; }
warn() { printf '  \033[33m! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

rand() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

say "Checking prerequisites"
command -v docker >/dev/null || die "docker is required (https://docs.docker.com/get-docker/)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
command -v node >/dev/null || die "node is required (>= 20)"
[ "$(node -e 'console.log(process.versions.node.split(".")[0])')" -ge 20 ] || die "node >= 20 required (found $(node -v))"
ok "docker, compose, node $(node -v)"

PG_PORT="${TALARIA_PG_PORT:-5544}"
REDIS_PORT="${TALARIA_REDIS_PORT:-6399}"

say "App secrets + config (ui/.env)"
if [ -f ui/.env ]; then
  skip "ui/.env"
  ADMIN_EMAIL="(unchanged — see ui/.env)"
  ADMIN_PASS="(unchanged)"
  # An install that predates TALARIA_SECRET_KEY has been wrapping its secrets
  # with AUTH_SECRET all along (secretbox.ts kekMaterial falls back to it). That
  # is invisible until somebody rotates AUTH_SECRET — which ui/.env itself calls
  # safe — and then every provider key, agent secret and OAuth token in the
  # database is unrecoverable. Pin the CURRENT effective value so the fallback
  # stops being load-bearing. Never generate a fresh one here: this file is
  # skipped precisely because the database is already sealed with what it holds.
  if ! grep -q '^TALARIA_SECRET_KEY=..*' ui/.env; then
    existing=$(grep -m1 '^AUTH_SECRET=' ui/.env | cut -d= -f2-)
    if [ -n "$existing" ]; then
      sed -i '/^TALARIA_SECRET_KEY=$/d' ui/.env
      cat >> ui/.env <<EOF

# Pinned by scripts/setup.sh $(date -u +%F): this instance was sealing secrets
# with AUTH_SECRET via the fallback in server/secretbox.ts. Same value, now
# explicit — so AUTH_SECRET can be rotated again without destroying them.
# NEVER change this line; see docs/ENCRYPTION.md.
TALARIA_SECRET_KEY=$existing
EOF
      ok "TALARIA_SECRET_KEY pinned to the existing AUTH_SECRET (the value already in use)"
    else
      warn "ui/.env has neither TALARIA_SECRET_KEY nor AUTH_SECRET — the app cannot seal secrets until one is set"
    fi
  fi
else
  ADMIN_EMAIL="admin@talaria.local"
  ADMIN_PASS="$(rand 9)"
  cat > ui/.env <<EOF
# Talaria dev config — generated by scripts/setup.sh $(date -u +%F). Safe to edit.

# Durable state
DATABASE_URL=postgres://talaria:talaria@127.0.0.1:${PG_PORT}/talaria
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}

# Session signing (safe to rotate — only invalidates live logins).
AUTH_SECRET=$(rand 32)

# Encryption root key (KEK) for secrets at rest. DEDICATED and STABLE: keep it
# constant — changing it makes every encrypted secret unrecoverable. Worktrees
# MUST share this exact value (scripts/worktree.sh copies it) so a second stack
# can decrypt data seeded from this one.
TALARIA_SECRET_KEY=$(rand 32)

# Password sign-in. Format: email:password[,email:password...]
AUTH_PASSWORD_ENABLED=1
AUTH_USERS=${ADMIN_EMAIL}:${ADMIN_PASS}
AUTH_ADMIN_EMAILS=${ADMIN_EMAIL}

# Google sign-in (off until you add real credentials)
AUTH_GOOGLE_ENABLED=0
AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=

# Agents authenticate to Talaria's APIs with their OWN tak_ credential, minted per
# agent and written to fleet/.env by the fleet renderer. This org-wide key is the
# app's own hop to the toolkit service, and a legacy fallback for containers built
# before per-agent keys (set TALARIA_AGENT_KEY_LEGACY=off to close that window).
TALARIA_AGENT_KEY=$(rand 32)

# Built-in object storage (the talaria-minio-dev container). dev.sh exports
# these so the container and the app agree; Admin → Storage → "Built-in bucket".
TALARIA_S3_ACCESS_KEY=talaria
TALARIA_S3_SECRET_KEY=$(rand 24)
EOF
  ok "ui/.env generated"
fi

say "Fleet config plane (fleet/)"
mkdir -p fleet/skills fleet/hooks fleet/agents stack
if [ -f fleet/chassis.yml ]; then skip "fleet/chassis.yml"; else
  cp scripts/chassis.template.yml fleet/chassis.yml && ok "fleet/chassis.yml (from template)"
fi
if [ -f fleet/.env ]; then skip "fleet/.env"; else
  cat > fleet/.env <<'EOF'
# Fleet env — compose interpolation + per-agent HERMES_KEY_* (Talaria appends
# those automatically when you create agents). Fill in your LLM endpoint to
# give agents a brain; the app itself runs fine without.
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
#HERMES_IMAGE=nousresearch/hermes-agent:latest
EOF
  ok "fleet/.env generated (add your LLM endpoint before starting agents)"
fi

say "Docker plumbing"
if ! docker info >/dev/null 2>&1; then
  # Don't fake success (the old `pull || true` printed ✓ with the daemon down).
  warn "docker daemon not running — start Docker Desktop, then re-run ./scripts/setup.sh"
else
  docker network inspect talaria >/dev/null 2>&1 && skip "network talaria" || {
    docker network create talaria >/dev/null && ok "network talaria"
  }
  if docker compose -f docker/dev-compose.yml pull -q; then
    ok "infra images ready (postgres, redis, qdrant, embeddings, minio)"
  else
    warn "image pull incomplete — dev.sh will retry; see errors above"
  fi
fi

say "App dependencies"
if [ -d ui/node_modules ]; then skip "ui/node_modules"; else
  (cd ui && npm install --no-fund --no-audit) && ok "npm install"
fi

# mcp/ is a SEPARATE package that compiles to mcp/dist/index.js — the fleet's
# Talaria toolkit, spawned by the app (ui/src/server/mcp-service.ts). dist is
# gitignored, so a fresh clone has no toolkit at all until this runs; dev.sh
# rebuilds it whenever mcp/src moves. Not optional: without it every agent's
# tool calls fail and the only trace is one stderr line from mcp-service.
say "Fleet toolkit (mcp/)"
if [ -d mcp/node_modules ]; then skip "mcp/node_modules"; else
  (cd mcp && npm install --no-fund --no-audit) && ok "npm install (mcp)"
fi
(cd mcp && npm run build) && ok "mcp/dist built" || die "mcp/ failed to build — the fleet toolkit will not start; fix mcp/src and re-run"

say "Git convenience"
# `git wt <name>` → an isolated dev worktree (own DB seeded from main). Using this
# instead of a plain `git worktree add` keeps a second app off your main DB.
git config alias.wt '!bash scripts/worktree.sh' 2>/dev/null && ok "git wt → scripts/worktree.sh" || skip "git alias"

echo
printf '\033[1;32mSetup complete.\033[0m\n\n'
echo "  Start everything:   ./scripts/dev.sh"
echo "  App:                http://localhost:5273"
echo "  Sign in:            ${ADMIN_EMAIL}  /  ${ADMIN_PASS}"
echo
echo "  First steps in the app: Settings → add an LLM endpoint on /models,"
echo "  then design your first agent on /agents (Muse will draft it)."
