#!/usr/bin/env bash
# Talaria first-time dev setup — blank machine → ready-to-run stack.
# Idempotent: existing files are left alone; run it again any time.
#
#   ./scripts/setup.sh        then:        ./scripts/dev.sh
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip() { printf '  \033[2m– %s (exists, kept)\033[0m\n' "$*"; }
warn() { printf '  \033[33m! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

rand() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

say "Checking prerequisites"
command -v docker >/dev/null || die "docker is required (https://docs.docker.com/get-docker/)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
command -v node >/dev/null || die "node is required (>= 20 — it executes the vite/vitest/tsc toolchain)"
[ "$(node -e 'console.log(process.versions.node.split(".")[0])')" -ge 20 ] || die "node >= 20 required (found $(node -v))"
# Bun is the runner and installer for the whole repo (see the root package.json);
# node stays a floor because the toolchain binaries carry node shebangs.
command -v bun >/dev/null || die "bun is required (https://bun.sh — e.g. 'mise use -g bun@latest')"
ok "docker, compose, node $(node -v), bun $(bun --version)"

PG_PORT="${TALARIA_PG_PORT:-5544}"
REDIS_PORT="${TALARIA_REDIS_PORT:-6399}"
SEARCH_PORT="${TALARIA_SEARCH_PORT:-8888}"

say "App secrets + config (ui/.env)"
if [ -f ui/.env ]; then
  skip "ui/.env"
  ADMIN_EMAIL="(unchanged — see ui/.env)"
  ADMIN_PASS="(unchanged)"
  # An install that predates TALARIA_SECRET_KEY has been wrapping its secrets
  # with AUTH_SECRET all along (secretbox.ts kekMaterial falls back to it). That
  # is invisible until somebody rotates AUTH_SECRET — which ui/.env itself calls
  # safe — and then every provider key, agent secret and OAuth token in the
  # database is unrecoverable. Pin the CURRENT effective value so the fallback
  # stops being load-bearing. Never generate a fresh one here: this file is
  # skipped precisely because the database is already sealed with what it holds.
  if ! grep -q '^TALARIA_SECRET_KEY=..*' ui/.env; then
    existing=$(grep -m1 '^AUTH_SECRET=' ui/.env | cut -d= -f2-)
    if [ -n "$existing" ]; then
      sed -i '/^TALARIA_SECRET_KEY=$/d' ui/.env
      cat >> ui/.env <<EOF

# Pinned by scripts/setup.sh $(date -u +%F): this instance was sealing secrets
# with AUTH_SECRET via the fallback in server/secretbox.ts. Same value, now
# explicit — so AUTH_SECRET can be rotated again without destroying them.
# NEVER change this line; see docs/ENCRYPTION.md.
TALARIA_SECRET_KEY=$existing
EOF
      ok "TALARIA_SECRET_KEY pinned to the existing AUTH_SECRET (the value already in use)"
    else
      warn "ui/.env has neither TALARIA_SECRET_KEY nor AUTH_SECRET — the app cannot seal secrets until one is set"
    fi
  fi
else
  ADMIN_EMAIL="admin@talaria.local"
  ADMIN_PASS="$(rand 9)"
  cat > ui/.env <<EOF
# Talaria dev config — generated by scripts/setup.sh $(date -u +%F). Safe to edit.

# Durable state
DATABASE_URL=postgres://talaria:talaria@127.0.0.1:${PG_PORT}/talaria
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}

# Live web search. Talaria runs its own SearXNG (docker/dev-compose.yml) so an
# agent on a model with no native browsing can still answer a question about the
# world — no API key, no per-query bill, no query leaving this machine. Point it
# at an instance you already run to use that one instead.
SEARXNG_URL=http://127.0.0.1:${SEARCH_PORT}
# Signs SearXNG's own preference cookies. Rendered into
# docker/searxng/settings.local.yml by scripts/dev.sh — SearXNG reads its secret
# from that file rather than the environment.
SEARXNG_SECRET=$(rand 32)

# Session signing (safe to rotate — only invalidates live logins).
AUTH_SECRET=$(rand 32)

# Encryption root key (KEK) for secrets at rest. DEDICATED and STABLE: keep it
# constant — changing it makes every encrypted secret unrecoverable. Worktrees
# MUST share this exact value (scripts/worktree.sh copies it) so a second stack
# can decrypt data seeded from this one.
TALARIA_SECRET_KEY=$(rand 32)

# Password sign-in. Format: email:password[,email:password...]
AUTH_PASSWORD_ENABLED=1
AUTH_USERS=${ADMIN_EMAIL}:${ADMIN_PASS}
AUTH_ADMIN_EMAILS=${ADMIN_EMAIL}

# Google sign-in (off until you add real credentials)
AUTH_GOOGLE_ENABLED=0
AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=

# Agents authenticate to Talaria's APIs with their OWN tak_ credential, minted per
# agent and written to fleet/.env by the fleet renderer. This org-wide key is the
# app's own hop to the toolkit service, and a legacy fallback for containers built
# before per-agent keys (set TALARIA_AGENT_KEY_LEGACY=off to close that window).
TALARIA_AGENT_KEY=$(rand 32)

# Built-in object storage (the talaria-minio-dev container). dev.sh exports
# these so the container and the app agree; Admin → Storage → "Built-in bucket".
TALARIA_S3_ACCESS_KEY=talaria
TALARIA_S3_SECRET_KEY=$(rand 24)
EOF
  ok "ui/.env generated"
fi

say "Fleet config plane (fleet/)"
mkdir -p fleet/skills fleet/hooks fleet/agents stack
if [ -f fleet/chassis.yml ]; then
  skip "fleet/chassis.yml"
  # The chassis is user-owned config, so it is never overwritten — but one
  # shape of it cannot work, and silently leaves every agent crash-looping:
  # cap_drop ALL with no cap_add. s6-overlay needs SETUID/SETGID to drop to the
  # hermes uid and CHOWN/DAC_OVERRIDE to bootstrap /opt/data; without them the
  # cont-init hooks exit 111 and the container never gets past `cd /opt/data`.
  if grep -q '^\s*-\s*ALL\s*$' fleet/chassis.yml && ! grep -q '^\s*cap_add:' fleet/chassis.yml; then
    warn "fleet/chassis.yml drops ALL capabilities with no cap_add — agents will crash-loop."
    warn "  Copy the cap_add block from scripts/chassis.template.yml, then restart your agents."
  fi
else
  cp scripts/chassis.template.yml fleet/chassis.yml && ok "fleet/chassis.yml (from template)"
fi
if [ -f fleet/.env ]; then skip "fleet/.env"; else
  cat > fleet/.env <<'EOF'
# Fleet env — compose interpolation + per-agent HERMES_KEY_* (Talaria appends
# those automatically when you create agents). Fill in your LLM endpoint to
# give agents a brain; the app itself runs fine without.
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
#HERMES_IMAGE=nousresearch/hermes-agent:latest
EOF
  ok "fleet/.env generated (add your LLM endpoint before starting agents)"
fi

say "Docker plumbing"
if ! docker info >/dev/null 2>&1; then
  # Don't fake success (the old `pull || true` printed ✓ with the daemon down).
  warn "docker daemon not running — start Docker Desktop, then re-run ./scripts/setup.sh"
else
  docker network inspect talaria >/dev/null 2>&1 && skip "network talaria" || {
    docker network create talaria >/dev/null && ok "network talaria"
  }
  if docker compose -f docker/dev-compose.yml pull -q; then
    ok "infra images ready (postgres, redis, qdrant, embeddings, minio, searxng)"
  else
    warn "image pull incomplete — dev.sh will retry; see errors above"
  fi
fi

say "App dependencies"
if [ -d ui/node_modules ]; then skip "ui/node_modules"; else
  (cd ui && bun install) && ok "bun install"
fi

# mcp/ is a SEPARATE package that compiles to mcp/dist/index.js — the fleet's
# Talaria toolkit, spawned by the app (ui/src/server/mcp-service.ts). dist is
# gitignored, so a fresh clone has no toolkit at all until this runs; dev.sh
# rebuilds it whenever mcp/src moves. Not optional: without it every agent's
# tool calls fail and the only trace is one stderr line from mcp-service.
say "Fleet toolkit (mcp/)"
if [ -d mcp/node_modules ]; then skip "mcp/node_modules"; else
  (cd mcp && bun install) && ok "bun install (mcp)"
fi
(cd mcp && bun run build) && ok "mcp/dist built" || die "mcp/ failed to build — the fleet toolkit will not start; fix mcp/src and re-run"

say "Git convenience"
# `git wt <name>` → an isolated dev worktree (own DB seeded from main). Using this
# instead of a plain `git worktree add` keeps a second app off your main DB.
git config alias.wt '!bash scripts/worktree.sh' 2>/dev/null && ok "git wt → scripts/worktree.sh" || skip "git alias"

# ── Verify what we just produced ─────────────────────────────────────────────
# This block exists because an install once shipped with a ui/.env that LOOKED
# right and a database nothing could read. Every check here corresponds to a
# way that actually happened — none of them are hypothetical.
say "Verifying"

# `|| true` is load-bearing: `set -o pipefail` makes the pipeline inherit
# grep's exit status, so a variable that is simply ABSENT would abort the whole
# script under `set -e` — and every check below is about absent variables.
env_val() { grep -m1 "^$1=" ui/.env | cut -d= -f2- || true; }

ROOT_KEY=$(env_val TALARIA_SECRET_KEY)
ROOT_FILE=$(env_val TALARIA_SECRET_KEY_FILE)
if [ -n "$ROOT_KEY" ]; then
  # Generation can fail quietly: `rand` falls back to /dev/urandom + od, and a
  # missing tool there yields an empty value that writes a syntactically valid
  # but load-bearing-empty line. Empty means the app silently falls back to
  # AUTH_SECRET — the exact fallback this file exists to stop relying on.
  [ "${#ROOT_KEY}" -ge 32 ] || die "TALARIA_SECRET_KEY in ui/.env is only ${#ROOT_KEY} chars — generation failed. Delete the line and re-run, or set it by hand: openssl rand -base64 48"
  ok "encryption root set (${#ROOT_KEY} chars)"
elif [ -n "$ROOT_FILE" ]; then
  [ -r "$ROOT_FILE" ] || die "TALARIA_SECRET_KEY_FILE points at $ROOT_FILE, which this user cannot read"
  ok "encryption root from key file"
else
  warn "no TALARIA_SECRET_KEY in ui/.env — secrets cannot be sealed until one is set (see docs/ENCRYPTION.md)"
fi

# The environment WINS over ui/.env at runtime. A stale export in a shell
# profile is how one install ran `vite dev` and `node server-entry.js` against
# two different roots, sealed under one and unable to read under the other,
# with nothing rotated and nothing to see in any config file.
if [ -n "${TALARIA_SECRET_KEY:-}" ] && [ -n "$ROOT_KEY" ] && [ "${TALARIA_SECRET_KEY}" != "$ROOT_KEY" ]; then
  warn "TALARIA_SECRET_KEY is EXPORTED in your shell and differs from ui/.env."
  warn "The exported value wins at runtime, so secrets will be sealed with it —"
  warn "and anything started without that export will not be able to read them."
  warn "Unset it, or make the two match. See docs/ENCRYPTION.md."
fi

for v in DATABASE_URL REDIS_URL; do
  [ -n "$(env_val "$v")" ] || die "$v missing from ui/.env — the app cannot start"
done
ok "database + redis configured"

echo
printf '\033[1;32mSetup complete.\033[0m\n\n'
echo "  Start everything:   ./scripts/dev.sh"
echo "  App:                http://localhost:5273"
echo "  Sign in:            ${ADMIN_EMAIL}  /  ${ADMIN_PASS}"
echo
echo "  First steps in the app: Settings → add an LLM endpoint on /models,"
echo "  then design your first agent on /agents (Muse will draft it)."
echo
echo "  Back up TALARIA_SECRET_KEY from ui/.env somewhere a snapshot isn't."
echo "  Every stored secret is sealed with it, and a database restored without"
echo "  it cannot read its own secrets. Admin → Secrets shows what it holds."
