#!/usr/bin/env bash
# Spin up an ISOLATED dev worktree — its own git worktree, its own Postgres +
# Redis (seeded from your main dev DB), its own ui/.env on unique ports. It
# shares nothing mutable with the main environment, so you can hack in it without
# any risk of breaking your primary dev stack.
#
#   ./scripts/worktree.sh <name> [base-ref]
#
# Then:  cd ../talaria-<name>/ui && bun run dev   (prints the exact command)
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

NAME="${1:-}"
BASE="${2:-HEAD}"
[ -n "$NAME" ] || { echo "usage: ./scripts/worktree.sh <name> [base-ref]" >&2; exit 1; }
[[ "$NAME" =~ ^[a-z0-9][a-z0-9-]*$ ]] || { echo "name must be lowercase-kebab" >&2; exit 1; }

say(){ printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok(){ printf '  \033[32m✓\033[0m %s\n' "$*"; }
die(){ printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# Allocate the first FREE port slot (app 53xx / pg 56xx / redis 65xx) so any
# number of worktrees can run at once without colliding.
port_free(){ ! (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }
N=0
for c in $(seq 1 89); do
  if port_free $((5300+c)) && port_free $((5600+c)) && port_free $((6500+c)); then N=$c; break; fi
done
[ "$N" -gt 0 ] || die "no free port slot — tear down some worktrees (docker compose -p talaria-wt-<n> down -v)"
APP_PORT=$((5300 + N)); PG_PORT=$((5600 + N)); REDIS_PORT=$((6500 + N))
WT="$ROOT/../talaria-$NAME"
PROJECT="talaria-wt-$NAME"
PGC="talaria-pg-$NAME"; REDISC="talaria-redis-$NAME"

command -v docker >/dev/null || die "docker required"
[ -f ui/.env ] || die "run ./scripts/setup.sh in the main checkout first (need ui/.env)"
MAIN_PGC="${TALARIA_PG_CONTAINER:-talaria-postgres-dev}"
docker inspect "$MAIN_PGC" >/dev/null 2>&1 || die "main Postgres ($MAIN_PGC) isn't running — start the main stack first"
[ -e "$WT" ] && die "$WT already exists"

say "Git worktree ($WT, branch wt/$NAME)"
git worktree add "$WT" -b "wt/$NAME" "$BASE" >/dev/null
ok "worktree created"

say "Isolated infra — Postgres :$PG_PORT, Redis :$REDIS_PORT"
TALARIA_PG_CONTAINER="$PGC" TALARIA_PG_PORT="$PG_PORT" \
TALARIA_REDIS_CONTAINER="$REDISC" TALARIA_REDIS_PORT="$REDIS_PORT" \
  docker compose -f docker/dev-compose.yml -p "$PROJECT" up -d >/dev/null
for i in $(seq 1 40); do docker exec "$PGC" pg_isready -U talaria -d talaria >/dev/null 2>&1 && break; sleep 1; done
ok "infra up"

say "Seeding the DB from your main environment"
docker exec "$MAIN_PGC" pg_dump -U talaria -d talaria --clean --if-exists 2>/dev/null | docker exec -i "$PGC" psql -U talaria -d talaria -q >/dev/null
ok "seeded (a point-in-time copy of main)"

say "Worktree ui/.env (own DB, shared encryption root)"
# Copy main's env, then repoint state + app port. TALARIA_SECRET_KEY is KEPT so
# the seeded (encrypted) secrets decrypt in this stack. AUTH_SECRET is kept too.
SECRET_KEY=$(grep -E '^TALARIA_SECRET_KEY=' ui/.env | cut -d= -f2- || true)
grep -vE '^(DATABASE_URL|REDIS_URL|PORT)=' ui/.env > "$WT/ui/.env"
[ -n "$SECRET_KEY" ] || echo "# NOTE: main ui/.env has no TALARIA_SECRET_KEY — the KEK falls back to AUTH_SECRET (shared here, so seeded secrets decrypt)." >> "$WT/ui/.env"
cat >> "$WT/ui/.env" <<EOF

# ── isolated worktree "$NAME" (generated by scripts/worktree.sh) ──
# This marker tells dev.sh the worktree has its own stack; without it, dev.sh
# refuses to run in a linked worktree (so a plain \`git worktree add\` can't point
# a second app at the main DB). See docs/WORKTREES.md.
TALARIA_WORKTREE=$NAME
DATABASE_URL=postgres://talaria:talaria@127.0.0.1:$PG_PORT/talaria
REDIS_URL=redis://127.0.0.1:$REDIS_PORT
PORT=$APP_PORT
EOF
ok "ui/.env written"

say "Sharing node_modules"
[ -d "$WT/ui/node_modules" ] || ln -s "$ROOT/ui/node_modules" "$WT/ui/node_modules"
ok "linked"

echo
printf '\033[1;32mWorktree "%s" ready — fully isolated from main.\033[0m\n\n' "$NAME"
echo "  Run it:   cd $WT/ui && bun run dev -- --port $APP_PORT"
echo "  App:      http://localhost:$APP_PORT   (Postgres :$PG_PORT · Redis :$REDIS_PORT)"
echo
echo "  Tear down when done:"
echo "    docker compose -p $PROJECT down -v"
echo "    git worktree remove $WT && git branch -D wt/$NAME"
