// `talaria setup` — first-time dev setup: blank machine → ready-to-run
// stack. Idempotent: existing files are left alone; run it again any time.
// Port of scripts/setup.sh. Follow it with `bun talaria dev`.

import { accessSync, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, constants } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { join } from 'node:path'
import type { Ctx } from '../ctx'
import type { Leaf } from '../cli'
import { envValue } from '../envfile'
import { ensureNetwork } from '../compose'

const rand = (bytes: number): string => randomBytes(bytes).toString('hex')

export async function runSetup(ctx: Ctx): Promise<number> {
  const root = ctx.root

  ctx.log.say('Checking prerequisites')
  const need = async (cmd: string, args: string[], how: string) => {
    try {
      await ctx.exec(cmd, args)
    } catch {
      ctx.log.die(how)
    }
  }
  await need('docker', ['--version'], 'docker is required (https://docs.docker.com/get-docker/)')
  await need('docker', ['compose', 'version'], 'docker compose v2 is required')
  await need('bun', ['--version'], 'bun is required (https://bun.sh — e.g. \'mise use -g bun@latest\')')
  // node stays a floor because the toolchain binaries (vite, vitest, tsc)
  // carry node shebangs — bun runs THEM under node. This CLI runs under bun,
  // so process.versions.node is the same node bun embeds; the check is about
  // what `bun run` will execute.
  const nodeMajor = parseInt(process.versions.node.split('.')[0]!, 10)
  if (!(nodeMajor >= 20)) ctx.log.die(`node >= 20 required (found ${process.versions.node})`)
  let bunVersion = ''
  try {
    bunVersion = (await ctx.exec('bun', ['--version'])).stdout.trim()
  } catch {
    /* the need() above already died */
  }
  ctx.log.ok(`docker, compose, node ${process.versions.node}, bun ${bunVersion}`)

  const PG_PORT = ctx.env.TALARIA_PG_PORT ?? '5544'
  const REDIS_PORT = ctx.env.TALARIA_REDIS_PORT ?? '6399'
  const SEARCH_PORT = ctx.env.TALARIA_SEARCH_PORT ?? '8888'

  ctx.log.say('App secrets + config (ui/.env)')
  const uiEnvPath = join(root, 'ui/.env')
  let adminEmail = '(unchanged — see ui/.env)'
  let adminPass = '(unchanged)'
  if (existsSync(uiEnvPath)) {
    ctx.log.skip('ui/.env (exists, kept)')
    await pinSecretKey(ctx, uiEnvPath)
  } else {
    adminEmail = 'admin@talaria.local'
    adminPass = rand(9)
    const date = ctx.now().toISOString().slice(0, 10)
    writeFileSync(
      uiEnvPath,
      `# Talaria dev config — generated by \`talaria setup\` ${date}. Safe to edit.

# Durable state
DATABASE_URL=postgres://talaria:talaria@127.0.0.1:${PG_PORT}/talaria
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}

# Live web search. Talaria runs its own SearXNG (docker/dev-compose.yml) so an
# agent on a model with no native browsing can still answer a question about the
# world — no API key, no per-query bill, no query leaving this machine. Point it
# at an instance you already run to use that one instead.
SEARXNG_URL=http://127.0.0.1:${SEARCH_PORT}
# Signs SearXNG's own preference cookies. Rendered into
# docker/searxng/settings.local.yml by \`talaria dev\` — SearXNG reads its secret
# from that file rather than the environment.
SEARXNG_SECRET=${rand(32)}

# Session signing (safe to rotate — only invalidates live logins).
AUTH_SECRET=${rand(32)}

# Encryption root key (KEK) for secrets at rest. DEDICATED and STABLE: keep it
# constant — changing it makes every encrypted secret unrecoverable. Worktrees
# MUST share this exact value (\`talaria worktree\` copies it) so a second stack
# can decrypt data seeded from this one.
TALARIA_SECRET_KEY=${rand(32)}

# Password sign-in. Format: email:password[,email:password...]
AUTH_PASSWORD_ENABLED=1
AUTH_USERS=${adminEmail}:${adminPass}
AUTH_ADMIN_EMAILS=${adminEmail}

# Google sign-in (off until you add real credentials)
AUTH_GOOGLE_ENABLED=0
AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=

# Agents authenticate to Talaria's APIs with their OWN tak_ credential, minted per
# agent and written to fleet/.env by the fleet renderer. This org-wide key is the
# app's own hop to the toolkit service, and a legacy fallback for containers built
# before per-agent keys (set TALARIA_AGENT_KEY_LEGACY=off to close that window).
TALARIA_AGENT_KEY=${rand(32)}

# Built-in object storage (the talaria-minio-dev container). \`talaria dev\`
# exports these so the container and the app agree; Admin → Storage → "Built-in bucket".
TALARIA_S3_ACCESS_KEY=talaria
TALARIA_S3_SECRET_KEY=${rand(24)}
`,
    )
    ctx.log.ok('ui/.env generated')
  }

  ctx.log.say('Fleet config plane (fleet/)')
  mkdirSync(join(root, 'fleet/skills'), { recursive: true })
  mkdirSync(join(root, 'fleet/hooks'), { recursive: true })
  mkdirSync(join(root, 'fleet/agents'), { recursive: true })
  mkdirSync(join(root, 'stack'), { recursive: true })
  const chassisPath = join(root, 'fleet/chassis.yml')
  if (existsSync(chassisPath)) {
    ctx.log.skip('fleet/chassis.yml (exists, kept)')
    // The chassis is user-owned config, so it is never overwritten — but one
    // shape of it cannot work, and silently leaves every agent crash-looping:
    // cap_drop ALL with no cap_add. s6-overlay needs SETUID/SETGID to drop to
    // the hermes uid and CHOWN/DAC_OVERRIDE to bootstrap /opt/data; without
    // them the cont-init hooks exit 111 and the container never gets past
    // `cd /opt/data`.
    const chassis = readFileSync(chassisPath, 'utf8')
    if (/^\s*-\s*ALL\s*$/m.test(chassis) && !/^\s*cap_add:/m.test(chassis)) {
      ctx.log.warn('fleet/chassis.yml drops ALL capabilities with no cap_add — agents will crash-loop.')
      ctx.log.warn('  Copy the cap_add block from scripts/chassis.template.yml, then restart your agents.')
    }
  } else {
    copyFileSync(join(root, 'scripts/chassis.template.yml'), chassisPath)
    ctx.log.ok('fleet/chassis.yml (from template)')
  }
  const fleetEnvPath = join(root, 'fleet/.env')
  if (!existsSync(fleetEnvPath)) {
    writeFileSync(
      fleetEnvPath,
      `# Fleet env — compose interpolation + per-agent HERMES_KEY_* (Talaria appends
# those automatically when you create agents). Fill in your LLM endpoint to
# give agents a brain; the app itself runs fine without.
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
#HERMES_IMAGE=nousresearch/hermes-agent:latest
`,
    )
    ctx.log.ok('fleet/.env generated (add your LLM endpoint before starting agents)')
  } else {
    ctx.log.skip('fleet/.env (exists, kept)')
  }

  ctx.log.say('Docker plumbing')
  try {
    await ctx.exec('docker', ['info'])
  } catch {
    // Don't fake success (the old `pull || true` printed ✓ with the daemon down).
    ctx.log.warn('docker daemon not running — start Docker Desktop, then re-run `bun talaria setup`')
  }
  try {
    // Daemon reachable: network + images. A pull that fails warns — dev
    // retries it on first bring-up.
    const net = await ensureNetwork(ctx, 'talaria')
    if (net === 'created') ctx.log.ok('network talaria')
    else ctx.log.skip('network talaria (exists, kept)')
    const pull = await ctx.run('docker', [
      'compose',
      '-f',
      join(root, 'docker/dev-compose.yml'),
      'pull',
      '-q',
    ])
    if (pull === 0) ctx.log.ok('infra images ready (postgres, redis, qdrant, embeddings, minio, searxng)')
    else ctx.log.warn('image pull incomplete — `talaria dev` will retry; see errors above')
  } catch {
    /* daemon check already warned */
  }

  ctx.log.say('App dependencies')
  if (existsSync(join(root, 'ui/node_modules'))) {
    ctx.log.skip('ui/node_modules (exists, kept)')
  } else {
    const code = await ctx.run('bun', ['install'], { cwd: join(root, 'ui') })
    if (code !== 0) ctx.log.die('bun install failed in ui/')
    ctx.log.ok('bun install')
  }

  // mcp/ is a SEPARATE package that compiles to mcp/dist/index.js — the
  // fleet's Talaria toolkit, spawned by the app (ui/src/server/mcp-service.ts).
  // dist is gitignored, so a fresh clone has no toolkit at all until this
  // runs. Not optional: without it every agent's tool calls fail and the only
  // trace is one stderr line from mcp-service.
  ctx.log.say('Fleet toolkit (mcp/)')
  if (!existsSync(join(root, 'mcp/node_modules'))) {
    const code = await ctx.run('bun', ['install'], { cwd: join(root, 'mcp') })
    if (code !== 0) ctx.log.die('bun install failed in mcp/')
    ctx.log.ok('bun install (mcp)')
  } else {
    ctx.log.skip('mcp/node_modules (exists, kept)')
  }
  const build = await ctx.run('bun', ['run', 'build'], { cwd: join(root, 'mcp') })
  if (build !== 0) ctx.log.die('mcp/ failed to build — the fleet toolkit will not start; fix mcp/src and re-run')
  ctx.log.ok('mcp/dist built')

  ctx.log.say('Git convenience')
  // `git wt <name>` → an isolated dev worktree (own DB seeded from main).
  // Using this instead of a plain `git worktree add` keeps a second app off
  // your main DB.
  try {
    await ctx.exec('git', ['config', 'alias.wt', '!bun cli/bin/talaria.ts worktree'])
    ctx.log.ok('git wt → talaria worktree')
  } catch {
    ctx.log.skip('git alias')
  }

  // ── Verify what we just produced ─────────────────────────────────────────
  // This block exists because an install once shipped with a ui/.env that
  // LOOKED right and a database nothing could read. Every check here
  // corresponds to a way that actually happened — none are hypothetical.
  ctx.log.say('Verifying')
  const envText = existsSync(uiEnvPath) ? readFileSync(uiEnvPath, 'utf8') : ''
  const rootKey = envValue(envText, 'TALARIA_SECRET_KEY')
  const rootFile = envValue(envText, 'TALARIA_SECRET_KEY_FILE')
  if (rootKey) {
    // Generation can fail quietly; an empty-ish value writes a syntactically
    // valid but load-bearing-empty line. Empty means the app silently falls
    // back to AUTH_SECRET — the exact fallback this file exists to stop
    // relying on.
    if (rootKey.length < 32) {
      ctx.log.die(
        `TALARIA_SECRET_KEY in ui/.env is only ${rootKey.length} chars — generation failed. ` +
          'Delete the line and re-run, or set it by hand: openssl rand -base64 48',
      )
    }
    ctx.log.ok(`encryption root set (${rootKey.length} chars)`)
  } else if (rootFile) {
    try {
      accessSync(rootFile, constants.R_OK)
    } catch {
      ctx.log.die(`TALARIA_SECRET_KEY_FILE points at ${rootFile}, which this user cannot read`)
    }
    ctx.log.ok('encryption root from key file')
  } else {
    ctx.log.warn('no TALARIA_SECRET_KEY in ui/.env — secrets cannot be sealed until one is set (see docs/ENCRYPTION.md)')
  }

  // The environment WINS over ui/.env at runtime. A stale export in a shell
  // profile is how one install ran `vite dev` and `node server-entry.js`
  // against two different roots, sealed under one and unable to read under
  // the other, with nothing rotated and nothing to see in any config file.
  const exported = ctx.env.TALARIA_SECRET_KEY
  if (exported && rootKey && exported !== rootKey) {
    ctx.log.warn('TALARIA_SECRET_KEY is EXPORTED in your shell and differs from ui/.env.')
    ctx.log.warn('The exported value wins at runtime, so secrets will be sealed with it —')
    ctx.log.warn('and anything started without that export will not be able to read them.')
    ctx.log.warn('Unset it, or make the two match. See docs/ENCRYPTION.md.')
  }

  for (const v of ['DATABASE_URL', 'REDIS_URL']) {
    if (!envValue(envText, v)) ctx.log.die(`${v} missing from ui/.env — the app cannot start`)
  }
  ctx.log.ok('database + redis configured')

  ctx.log.say('Setup complete.')
  ctx.log.raw(`
  Start everything:   bun talaria dev
  App:                http://localhost:5273
  Sign in:            ${adminEmail}  /  ${adminPass}

  First steps in the app: Settings → add an LLM endpoint on /models,
  then design your first agent on /agents (Muse will draft it).

  Back up TALARIA_SECRET_KEY from ui/.env somewhere a snapshot isn't.
  Every stored secret is sealed with it, and a database restored without
  it cannot read its own secrets. Admin → Secrets shows what it holds.
`)
  return 0
}

/** An install that predates TALARIA_SECRET_KEY has been wrapping its secrets
 *  with AUTH_SECRET all along (secretbox.ts kekMaterial falls back to it).
 *  That is invisible until somebody rotates AUTH_SECRET — which ui/.env
 *  itself calls safe — and then every provider key, agent secret and OAuth
 *  token in the database is unrecoverable. Pin the CURRENT effective value so
 *  the fallback stops being load-bearing. Never generate a fresh one here:
 *  this file is skipped precisely because the database is already sealed
 *  with what it holds. */
async function pinSecretKey(ctx: Ctx, uiEnvPath: string): Promise<void> {
  const text = readFileSync(uiEnvPath, 'utf8')
  if (/^TALARIA_SECRET_KEY=..*/m.test(text)) return
  const existing = envValue(text, 'AUTH_SECRET')
  if (!existing) {
    ctx.log.warn('ui/.env has neither TALARIA_SECRET_KEY nor AUTH_SECRET — the app cannot seal secrets until one is set')
    return
  }
  const date = ctx.now().toISOString().slice(0, 10)
  const kept = text
    .split('\n')
    .filter((l) => l !== 'TALARIA_SECRET_KEY=')
    .join('\n')
  writeFileSync(
    uiEnvPath,
    `${kept}
# Pinned by \`talaria setup\` ${date}: this instance was sealing secrets
# with AUTH_SECRET via the fallback in server/secretbox.ts. Same value, now
# explicit — so AUTH_SECRET can be rotated again without destroying them.
# NEVER change this line; see docs/ENCRYPTION.md.
TALARIA_SECRET_KEY=${existing}
`,
  )
  ctx.log.ok('TALARIA_SECRET_KEY pinned to the existing AUTH_SECRET (the value already in use)')
}

export const setupCommand: Leaf = {
  kind: 'leaf',
  name: 'setup',
  summary: 'first-run dev bootstrap: secrets, fleet config, images, deps',
  usage: 'talaria setup',
  run: runSetup,
}
