// `talaria box new` — a containerized dev environment per task: a full clone
// of the repo on its own branch, its own stateful sidecars seeded from the
// primary dev environment, its own private fleet, and the agent CLIs inside.
// Port of scripts/devbox `new` + `build`. Full story: docs/DEVBOX.md.

import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Ctx } from '../../ctx'
import type { Leaf } from '../../cli'
import { compose, waitFor } from '../../compose'
import { envValue, writeSecret } from '../../envfile'
import { portSlot } from '../../paths'
import { renderSearxng } from '../../searxng'
import { runSeed } from './seed'
import { boxDir, boxState, checkName, COMPOSE_FILE, IMAGE } from './shared'

/** The primary's ui/.env lines a box must NOT inherit — everything that names
 *  a primary-side service gets re-pointed at the box's own below. Everything
 *  else rides verbatim: TALARIA_SECRET_KEY/AUTH_* MUST, or sealed secrets
 *  seeded from the primary couldn't decrypt (the worktree rule). */
const STRIP_RE = /^(DATABASE_URL|REDIS_URL|PORT|SEARXNG_URL|TALARIA_QDRANT_URL|TALARIA_EMBED_URL|TALARIA_S3_.*)=/

/** The box's ui/.env: the primary's, minus the strip-list, plus the box block.
 *  Pure so the strip-list is testable. */
export function boxUiEnv(primaryEnv: string, o: { name: string; state: string; s3: { bucket: string; key: string; secret: string } }): string {
  const kept = primaryEnv
    .split('\n')
    .filter((l) => !STRIP_RE.test(l))
    .join('\n')
  return `${kept}

# ── devbox "${o.name}" (generated by \`talaria box new\`) ──
# This marker tells \`talaria dev\` the box owns its infra — it must not try to
# bring up the primary dev stack through the mounted docker socket.
TALARIA_DEVBOX=${o.name}
DATABASE_URL=postgres://talaria:talaria@postgres:5432/talaria
REDIS_URL=redis://redis:6379
TALARIA_QDRANT_URL=http://qdrant:6333
TALARIA_S3_URL=http://minio:9000
TALARIA_S3_BUCKET=${o.s3.bucket}
TALARIA_S3_ACCESS_KEY=${o.s3.key}
TALARIA_S3_SECRET_KEY=${o.s3.secret}
TALARIA_EMBED_URL=http://talaria-embeddings-dev:80
SEARXNG_URL=http://talaria-searxng-dev:8080
TALARIA_MCP_GW_URL=http://devbox:5273/api/mcp/gw
TALARIA_GATEWAY_SELF_URL=http://devbox:5273/api/llm/v1
TALARIA_AGENT_DIAL=container
TALARIA_FLEET_PROJECT=devbox-${o.name}-fleet
TALARIA_FLEET_DIR=${o.state}/fleet
TALARIA_APPS_DIR=${o.state}/apps
TALARIA_UPLOADS_DIR=${o.state}/uploads
PORT=5273
`
}

/** compose.override.yml — extra env/volumes for the box, merged into its
 *  compose whenever the file exists. Written only when there is something to
 *  put in it: an unset var must be TRULY ABSENT, not present-and-empty (an
 *  empty CLAUDE_CODE_OAUTH_TOKEN would shadow real auth). One environment
 *  block for both sources — the bash version appended a second `environment:`
 *  key under SSH forwarding and docker's duplicate-key merge drops the token.
 *  Pure so that shape is testable. */
export function overrideYaml(o: { token?: string; sshSock?: string }): string | null {
  if (!o.token && !o.sshSock) return null
  const lines = [
    '# Written by `talaria box new` (--claude-token and/or SSH agent forwarding).',
    '# Manual edits welcome — this file merges into the box compose whenever it',
    "# exists. NEVER set CLAUDE_CODE_OAUTH_TOKEN and ANTHROPIC_AUTH_TOKEN together.",
    'services:',
    '  devbox:',
  ]
  if (o.sshSock) lines.push('    volumes:', `      - ${o.sshSock}:/ssh-agent`)
  lines.push('    environment:')
  if (o.token) lines.push(`      CLAUDE_CODE_OAUTH_TOKEN: '${o.token}'`)
  if (o.sshSock) lines.push('      SSH_AUTH_SOCK: /ssh-agent')
  return `${lines.join('\n')}\n`
}

/** Rebuild the toolchain image. `--network=host` is load-bearing on hosts
 *  whose daemon has no working upstream DNS: apt/npm inside the build
 *  otherwise resolve nothing (docs/CONTAINER.md, Troubleshooting). */
export async function runBuild(ctx: Ctx, noCache = false): Promise<number> {
  ctx.log.say(`Building ${IMAGE} (context: repo root — the Dockerfile COPYs nothing from it)`)
  const args = ['build', '--network=host']
  if (noCache) args.push('--no-cache')
  args.push('-f', join(ctx.root, 'docker/devbox.Dockerfile'), '-t', IMAGE, ctx.root)
  const code = await ctx.run('docker', args)
  if (code !== 0) return code
  ctx.log.ok('built')
  return 0
}

export async function runNew(ctx: Ctx, name: string, o: { branch?: string; from?: string; noInstall?: boolean; token?: string; qdrant?: boolean } = {}): Promise<number> {
  const root = ctx.root
  checkName(ctx, name)
  try {
    await ctx.exec('docker', ['--version'])
  } catch {
    ctx.log.die('docker is required')
  }
  if (!existsSync(join(root, 'ui/.env'))) {
    ctx.log.die('run `bun talaria setup` in the primary checkout first (need ui/.env)')
  }
  const box = boxDir(ctx, name)
  if (existsSync(box)) ctx.log.die(`${box} already exists`)

  // The primary stack is the seed source, and hosts the shared stateless
  // services (embeddings, search) the box dials by container name.
  ctx.log.say('Primary dev stack (seed source + shared TEI/SearXNG)')
  const devSpec = { files: [join(root, 'docker/dev-compose.yml')] }
  if ((await compose(ctx, devSpec, ['up', '-d', 'postgres'])) !== 0) {
    ctx.log.die("primary postgres won't start — it is the seed source")
  }
  try {
    renderSearxng(ctx)
  } catch {
    /* non-fatal, same posture as the old `render-searxng.sh || true` */
  }
  for (const svc of ['embeddings', 'searxng']) {
    if ((await compose(ctx, devSpec, ['up', '-d', svc])) !== 0) {
      ctx.log.warn(`${svc} didn't start — the box will run degraded without it (same posture as \`talaria dev\`)`)
    }
  }
  try {
    await ctx.exec('docker', ['inspect', 'talaria-dev_default'])
  } catch {
    ctx.log.die('primary dev network talaria-dev_default is missing — bring the stack up once')
  }

  try {
    await ctx.exec('docker', ['image', 'inspect', IMAGE])
  } catch {
    if ((await runBuild(ctx)) !== 0) ctx.log.die(`building ${IMAGE} failed`)
  }

  // One host port per box, worktree.sh's slot scan.
  const appPort = await portSlot(5301, 5389)
  if (appPort === null) ctx.log.die('no free app port in 5301-5389 — tear down some devboxes')
  const state = boxState(ctx, name)
  const branch = o.branch ?? `agent/${name}`
  const hostRepo = join(box, 'talaria')

  ctx.log.say(`Repo clone → ${hostRepo} (branch ${branch} from ${o.from ?? 'HEAD'})`)
  mkdirSync(box, { recursive: true })
  // --local: hardlinked objects — near-free on btrfs and safe against a gc in
  // the primary (git prune is hardlink-aware). Committed refs only: the
  // primary's uncommitted work does NOT ride into a box.
  await ctx.exec('git', ['clone', '--quiet', '--local', root, hostRepo], { timeoutMs: 300_000 })
  const branchExists = await (async () => {
    try {
      await ctx.exec('git', ['-C', hostRepo, 'show-ref', '--verify', '--quiet', `refs/heads/${branch}`])
      return true
    } catch {
      return false
    }
  })()
  if (branchExists) {
    await ctx.exec('git', ['-C', hostRepo, 'checkout', '--quiet', branch])
  } else {
    try {
      await ctx.exec('git', ['-C', hostRepo, 'checkout', '--quiet', '-b', branch, o.from ?? 'HEAD'])
    } catch {
      ctx.log.die(`ref ${o.from ?? 'HEAD'} unusable (committed refs only — the primary's uncommitted work doesn't ride into boxes)`)
    }
  }
  // Pushes leave the box: the local-clone origin points at this checkout.
  let origin: string
  try {
    origin = (await ctx.exec('git', ['-C', root, 'remote', 'get-url', 'origin'])).stdout.trim()
  } catch {
    ctx.log.die('the primary checkout has no `origin` remote — pushes out of the box need one')
  }
  await ctx.exec('git', ['-C', hostRepo, 'remote', 'set-url', 'origin', origin])
  // apps/leadworks and apps/waypoint are gitignored subrepos that are part of
  // local builds — copy them or the box's builds silently differ from the
  // primary's. Same for the installed node_modules (snapshot; bun install
  // below reconciles lockfile drift). btrfs reflinks make these near-free —
  // hence cp, not fs.cp.
  for (const p of ['apps/leadworks', 'apps/waypoint', 'ui/node_modules', 'mcp/node_modules']) {
    if (existsSync(join(root, p))) {
      await ctx.exec('cp', ['-a', '--reflink=auto', join(root, p), join(hostRepo, p)], { timeoutMs: 600_000 })
    }
  }
  const head = (await ctx.exec('git', ['-C', hostRepo, 'log', '--oneline', '-1'])).stdout.split('\n')[0]!.slice(0, 60)
  ctx.log.ok(`cloned ${head}`)

  ctx.log.say('Box compose env')
  mkdirSync(join(state, 'fleet'), { recursive: true })
  mkdirSync(join(state, 'apps'), { recursive: true })
  mkdirSync(join(state, 'uploads'), { recursive: true })
  const uiEnv = readFileSync(join(root, 'ui/.env'), 'utf8')
  const s3 = {
    key: envValue(uiEnv, 'TALARIA_S3_ACCESS_KEY') ?? 'talaria',
    secret: envValue(uiEnv, 'TALARIA_S3_SECRET_KEY') ?? 'talaria-dev-secret',
    bucket: envValue(uiEnv, 'TALARIA_S3_BUCKET') ?? 'talaria',
  }
  let dockerGid: number
  try {
    dockerGid = statSync('/var/run/docker.sock').gid
  } catch {
    ctx.log.die('no docker socket at /var/run/docker.sock — Docker must be running')
  }
  // Paths here are canonical by construction (root and devboxHome both
  // realpath'd) — they land verbatim in compose.env and must exist identically
  // INSIDE the box, where the host's symlink spellings do not.
  writeSecret(
    join(box, 'compose.env'),
    `BOX_NAME=${name}
BOX_APP_PORT=${appPort}
BOX_HOST_REPO=${hostRepo}
BOX_HOST_STATE=${state}
BOX_HOME=${ctx.env.HOME ?? ''}
DOCKER_GID=${dockerGid}
BOX_S3_ACCESS_KEY=${s3.key}
BOX_S3_SECRET_KEY=${s3.secret}
`,
  )
  // Auth/provider env rides the override file (see overrideYaml for why it is
  // a file at all). SSH agent forwarding, when the invoker has one: lets
  // `git push` out of the box without copying keys (the key itself never
  // enters the box).
  const override = overrideYaml({ token: o.token, sshSock: ctx.env.SSH_AUTH_SOCK })
  if (override) {
    writeSecret(join(box, 'compose.override.yml'), override)
    if (ctx.env.SSH_AUTH_SOCK) ctx.log.ok('SSH agent forwarded')
  }
  ctx.log.ok(`compose.env written (app → 127.0.0.1:${appPort})`)

  ctx.log.say('Box stack (devbox + postgres + redis + qdrant + minio)')
  if ((await compose(ctx, { files: [join(root, COMPOSE_FILE)], project: `devbox-${name}`, envFile: join(box, 'compose.env') }, ['up', '-d', '--quiet-pull'])) !== 0) {
    ctx.log.die('box stack failed to start')
  }
  const pgReady = await waitFor(
    ctx,
    'box postgres',
    async () => {
      try {
        await ctx.exec('docker', ['exec', `devbox-${name}-postgres`, 'pg_isready', '-U', 'talaria', '-d', 'talaria'])
        return true
      } catch {
        return false
      }
    },
    60,
  )
  if (!pgReady) ctx.log.die('box postgres never became ready')
  await waitFor(
    ctx,
    'box redis',
    async () => {
      try {
        await ctx.exec('docker', ['exec', `devbox-${name}-redis`, 'redis-cli', 'ping'])
        return true
      } catch {
        return false
      }
    },
    20,
  )
  ctx.log.ok(`stack up (project devbox-${name})`)

  ctx.log.say('Box ui/.env (own services, shared encryption root)')
  writeFileSync(join(hostRepo, 'ui/.env'), boxUiEnv(uiEnv, { name, state, s3 }))
  ctx.log.ok('ui/.env written')

  ctx.log.say('Seeding starter data from the primary dev environment')
  await runSeed(ctx, name, { qdrant: o.qdrant })

  if (!o.noInstall) {
    ctx.log.say('Dependencies + toolkit build (snapshot copies reconciled against the lockfile)')
    try {
      await ctx.exec(
        'docker',
        ['exec', `devbox-${name}`, 'sh', '-lc', 'cd ui && bun install --frozen-lockfile && cd ../mcp && bun install --frozen-lockfile && bun run build'],
        { cwd: hostRepo, timeoutMs: 600_000 },
      )
    } catch (e) {
      ctx.log.die(`install/build inside the box failed: ${e instanceof Error ? e.message : String(e)}`)
    }
    ctx.log.ok('installed + mcp built')
  }

  writeFileSync(
    join(box, 'box.env'),
    `BOX_NAME=${name}
BRANCH=${branch}
BASE=${o.from ?? 'HEAD'}
APP_PORT=${appPort}
PROJECT=devbox-${name}
FLEET_PROJECT=devbox-${name}-fleet
CREATED=${ctx.now().toISOString()}
`,
  )

  ctx.log.raw(`
Devbox "${name}" ready.

  Enter:      bun talaria box enter ${name}            (bash)
              bun talaria box enter ${name} claude     (Claude Code)
              bun talaria box enter ${name} opencode
  Run the app (inside):  bun talaria dev        →  http://127.0.0.1:${appPort}
  Credentials: identical to the primary dev stack

  Tear down when done:   bun talaria box rm ${name}
`)
  return 0
}

/** A failed `new` must not leave a half-built box behind: `box rm` refuses
 *  anything without box.env, so a partial would block the name until somebody
 *  found the directory. Only a directory WE created (it did not exist on
 *  entry) and that never completed (no box.env) is removed — anything else
 *  that happens to sit there is untouchable. */
export async function newGuarded(ctx: Ctx, args: { positionals: string[]; flags: Record<string, string | boolean> }): Promise<number> {
  const name = args.positionals[0]!
  const box = boxDir(ctx, name)
  const preexisting = existsSync(box)
  try {
    return await runNew(ctx, name, {
      branch: args.flags.branch as string | undefined,
      from: args.flags.from as string | undefined,
      noInstall: args.flags['no-install'] === true,
      token: args.flags['claude-token'] as string | undefined,
      qdrant: args.flags.qdrant === true,
    })
  } catch (e) {
    if (!preexisting && existsSync(box) && !existsSync(join(box, 'box.env'))) {
      ctx.log.warn(`new did not complete — removing the partial ${box}`)
      rmSync(box, { recursive: true, force: true })
    }
    throw e
  }
}

export const newCommand: Leaf = {
  kind: 'leaf',
  name: 'new',
  summary: 'create a devbox: clone + own sidecars, seeded from the primary stack',
  usage: 'talaria box new <name> [--branch <b>] [--from <ref>] [--no-install] [--claude-token <tok>] [--qdrant]',
  positionals: { name: 'name', required: true },
  flags: [
    { name: 'branch', kind: 'value', desc: 'branch for the clone (default: agent/<name>)' },
    { name: 'from', kind: 'value', desc: 'ref to branch from (default: HEAD — committed refs only)' },
    { name: 'no-install', kind: 'bool', desc: 'skip the in-box bun install + mcp build' },
    { name: 'claude-token', kind: 'value', desc: 'CLAUDE_CODE_OAUTH_TOKEN for Claude Code inside the box' },
    { name: 'qdrant', kind: 'bool', desc: 'also round-trip the Qdrant index (derived; default off)' },
  ],
  run: (ctx, args) => newGuarded(ctx, args),
}
