[package]
name = "talaria-fitness-toolbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
talaria-fitness-talaria-tools = { workspace = true }
talaria-fitness-world = { workspace = true }
talaria-harness = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
