[package]
name = "talaria-google-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
talaria-body = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
talaria-gateway = { workspace = true }
talaria-secretbox = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
