[package]
name = "talaria-update-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
talaria-update-layout = { workspace = true }
talaria-update-state = { workspace = true }
tracing = { workspace = true }
base64 = { workspace = true }
url = { workspace = true }
