[package]
name = "talaria-update-docker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
talaria-fleet-docker = { workspace = true }
talaria-update-layout = { workspace = true }
talaria-update-registry = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
